# Getting Data

### Imports
- import the libraries used for data loading, cleaning, and sampling

In [43]:
import pandas as pd

### Survey Year
- set the BRFSS year used to build the file path

In [44]:
year = '2018'

### Load CSV
- load the 2018 BRFSS CSV into a dataframe

In [45]:
brfss_2018_df = pd.read_csv(f'/Users/rj/Data/615-BRFSS/csv/brfss{year}.csv')

/var/folders/57/5sgkm84x0n56wy8nmy7v5p700000gn/T/ipykernel_4148/1669952944.py:1: DtypeWarning: Columns (0: dlyother) have mixed types. Specify dtype option on import or set low_memory=False.
  brfss_2018_df = pd.read_csv(f'/Users/rj/Data/615-BRFSS/csv/brfss{year}.csv')

### Dataset Shape
- inspect the number of rows and columns in the raw 2018 BRFSS file

In [46]:
brfss_2018_df.shape

(437436, 276)

### Display Settings
- show more columns when previewing the dataframe
- display the first few rows of the raw dataset

In [47]:
pd.set_option('display.max_columns', 500)
brfss_2018_df.head()

,Unnamed: 0,x.state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,x.psu,ctelenm1,pvtresd1,colghous,statere1,cellfon4,ladult,numadult,nummen,numwomen,safetime,ctelnum1,cellfon5,cadult,pvtresd3,cclghous,cstate1,landline,hhadult,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,exerany2,sleptim1,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd1,havarth3,addepev2,chckdny1,diabete3,diabage2,lastden4,rmvteth4,sex1,marital,educa,renthom1,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income2,weight2,height3,pregnant,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,stopsmk2,lastsmk2,usenow3,alcday5,avedrnk2,drnk3ge5,maxdrnks,flushot6,flshtmy2,imfvplac,pneuvac4,fall12mn,fallinj3,seatbelt,drnkdri2,hadmam,howlong,hadpap2,lastpap2,hpvtest,hplsttst,hadhyst2,pcpsaad3,pcpsadi1,pcpsare1,psatest1,psatime,pcpsars1,bldstool,lstblds3,hadsigm3,hadsgco1,lastsig3,hivtst6,hivtstd3,hivrisk5,pdiabtst,prediab1,insulin,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,medicare,hlthcvr1,delayme1,dlyother,nocov121,lstcovrg,drvisits,medscos1,carercvd,medbill1,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel2,crgvlng1,crgvhrs1,crgvprb2,crgvpers,crgvhous,crgvmst3,crgvexpt,ecigaret,ecignow,marijan1,usemrjn2,rsnmrjn1,adsleep,slepday1,slepsno2,slepbrth,adpleas1,addown1,feelnerv,stopwory,copdcogh,copdflem,copdbrth,copdbtst,copdsmok,indortan,numburn3,sunprtct,wkdayout,wkendout,lcsfirst,lcslast,lcsnumcg,lcsctscn,cncrdiff,cncrage,cncrtyp1,csrvtrt2,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl1,pcpsade1,pcdmdec1,profexam,lengexam,hpvadvc2,hpvadsht,tetanus1,shingle2,somale,sofemale,trnsgndr,rcsgendr,rcsrltn2,casthdx2,casthno2,qstver,qstlang,x.metstat,x.urbstat,mscode,x.ststr,x.strwt,x.rawrake,x.wt2rake,x.imprace,x.chispnc,x.crace1,x.cprace,x.cllcpwt,x.dualuse,x.dualcor,x.llcpwt2,x.llcpwt,x.rfhlth,x.phys14d,x.ment14d,x.hcvu651,x.totinda,x.michd,x.ltasth1,x.casthm1,x.asthms1,x.drdxar1,x.exteth3,x.alteth3,x.denvst3,x.prace1,x.mrace1,x.hispanc,x.race,x.raceg21,x.racegr3,x.race.g1,x.ageg5yr,x.age65yr,x.age80,x.age.g,htin4,htm4,wtkg3,x.bmi5,x.bmi5cat,x.rfbmi5,x.chldcnt,x.educag,x.incomg,x.smoker3,x.rfsmok3,drnkany5,drocdy3.,x.rfbing5,x.drnkwek,x.rfdrhv6,x.flshot6,x.pneumo3,x.rfseat2,x.rfseat3,x.drnkdrv,x.rfmam21,x.mam5022,x.rfpap34,x.rfpsa22,x.rfblds3,x.col10yr,x.hfob3yr,x.fs5yr,x.fobtfs,x.crcrec,x.aidtst3
0,1,1,1,1052018,1,5,2018,1100,2018000001,2018000001,1.0,1.0,NaN,1.0,2.0,NaN,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,30.0,88.0,30.0,1.0,1.0,2.0,1.0,2.0,7.0,2.0,2.0,2.0,2.0,NaN,1.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,1.0,2,3.0,6.0,1.0,2.0,NaN,1.0,2.0,2.0,88.0,6.0,130.0,504.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102017.0,5.0,1.0,88.0,NaN,1.0,NaN,1.0,2.0,1.0,5.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,2.0,2.0,5.0,11011,65.664883,1.0,65.664883,1,NaN,NaN,NaN,NaN,1,0.549324,457.961320,173.185135,1,3,1,9,2,2.0,1,1,3,1.0,2,1.0,1,1.0,1.0,2,1.0,1.0,1.0,1.0,13,2,80,6,64.0,163.0,5897.0,2231.0,2.0,1,1,4,4,4,1,2,0,1,0,1,1.0,1.0,1,1,9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
1,2,1,1,1122018,1,12,2018,1100,2018000002,2018000002,1.0,1.0,NaN,1.0,2.0,NaN,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,88.0,88.0,NaN,2.0,1.0,1.0,2.0,1.0,5.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,2.0,8.0,2,5.0,6.0,2.0,2.0,NaN,2.0,2.0,1.0,2.0,4.0,200.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,NaN,3.0,202.0,2.0,88.0,2.0,2.0,NaN,NaN,2.0,NaN,NaN,1.0,88.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,1.0,1.0,1.0,11012,131.566539,1.0,131.566539,2,NaN,NaN,NaN,NaN,1,0.549324,917.573942,1540.504315,1,1,1,2,1,2.0,1,1,3,2.0,1,NaN,2,2.0,2.0,2,2.0,2.0,2.0,2.0,3,1,33,2,65.0,165.0,9072.0,3328.0,4.0,2,3,4,2,1,2,1,7,1,93,1,NaN,NaN,1,1,2,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
2,3,1,1,1082018,1,8,2018,1100,2018000003,2018000003,1.0,1.0,NaN,1.0,2.0,NaN,1.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,10.0,88.0,88.0,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,2.0,1.0,57.0,1.0,7.0,2,3.0,4.0,1.0,2.0,NaN,8.0,2.0,7.0,88.0,3.0,142.0,410.0,NaN,2.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,92017.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,7.0,9.0,NaN,7.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,NaN,2.0,NaN,2.0,NaN,NaN,1.0,101.0,101.0,4.0,4.0,4.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,2.0,1.0,5.0,11011,65.664883,1.0,65.664883,1,NaN,NaN,NaN,NaN,9,NaN,935.658879,607.098051,2,2,1,9,1,2.0,1,1,3,2.0,9,9.0,1,1.0,1.0,2,1.0,1.0,1.0,1.0,12,2,76,6,58.0,147.0,6441.0,2968.0,3.0,2,1,2,2,4,1,2,0,1,0,1,1.0,1.0,1,1,9,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
3,4,1,1,1032018,1,3,2018,1100,2018000004,2018000004,1.0,1.0,NaN,1.0,2.0,NaN,1.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,3.0,1.0,1,2.0,4.0,1.0,2.0,NaN,8.0,2.0,7.0,88.0,3.0,190.0,510.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,92017.0,5.0,1.0,88.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,NaN,NaN,2.0,NaN,1.0,2.0,6.0,2.0,NaN,2.0,7.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,77.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,1.0,1.0,2.0,11011,65.664883,1.0,65.664883,1,NaN,NaN,NaN,NaN,9,NaN,935.658879,822.672162,1,1,1,9,1,2.0,1,1,3,2.0,2,1.0,2,1.0,1.0,2,1.0,1.0,1.0,1.0,10,2,66,6,70.0,178.0,8618.0,2726.0,3.0,2,1,2,2,4,1,2,0,1,0,1,1.0,1.0,1,1,9,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0
4,5,1,1,1122018,1,12,2018,1100,2018000005,2018000005,1.0,1.0,NaN,1.0,2.0,NaN,2.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,2.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,1.0,8.0,2,1.0,6.0,1.0,2.0,NaN,1.0,2.0,1.0,2.0,99.0,7777.0,503.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,NaN,NaN,1.0,NaN,1.0,1.0,1.0,2.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,88.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1.0,2.0,1.0,5.0,11012,131.566539,2.0,263.133079,1,NaN,NaN,NaN,NaN,1,0.549324,1835.147884,2229.728350,1,1,1,1,2,2.0,1,1,3,2.0,1,NaN,1,1.0,1.0,2,1.0,1.0,1.0,1.0,5,1,40,3,63.0,160.0,NaN,NaN,NaN,9,3,4,9,4,1,2,0,1,0,1,NaN,NaN,1,1,9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0

### Diabetes Status Subset
- create a full-population dataframe using only `diabete3`
- drop missing values for the diabetes-status variable

In [48]:
diabetes_status_df = brfss_2018_df[['diabete3']].dropna()
diabetes_status_df.shape

(437412, 1)

### Clean Diabetes Status
- remove invalid `diabete3` codes for don't know and refused
- inspect the remaining diabetes-status counts

In [49]:
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete3'] != 7]
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete3'] != 9]
diabetes_status_df['diabete3'].value_counts().sort_index()

diabete3
1.0     60703
2.0      3857
3.0    363757
4.0      8263
Name: count, dtype: int64

### Recode Diabetes Target
- convert BRFSS diabetes codes into the `0/1/2` target used in the reference notebook

In [50]:
diabetes_status_df['Diabetes_012'] = diabetes_status_df['diabete3'].replace({
    2: 0,
    4: 0,
    3: 1,
    1: 2,
})

diabetes_status_df.groupby(['Diabetes_012']).size()

Diabetes_012
0.0     12120
1.0    363757
2.0     60703
dtype: int64

### Feature List
- define the diabetes-management variables and covariates used in the paper-style analysis dataframe

In [51]:
columns = [
"diabedu",
"feetchk3",
"bldsugar",
"doctdiab",
"chkhemo3",
"feetchk",
"eyeexam1",
"menthlth",
"educa",
"x.ageg5yr",
"sex1",
"marital",
"employ1",
"income2",
"x.urbstat",
"persdoc2",
"hlthpln1",
"addepev2",
"diabete3",
"diabage2"
]

### Select Analysis Columns
- build `features_df` from the selected diabetes-management variables

In [52]:
features_df = brfss_2018_df[columns].copy()

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [53]:
features_df.shape

(437436, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [54]:
features_df.head()

,diabedu,feetchk3,bldsugar,doctdiab,chkhemo3,feetchk,eyeexam1,menthlth,educa,x.ageg5yr,sex1,marital,employ1,income2,x.urbstat,persdoc2,hlthpln1,addepev2,diabete3,diabage2
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,13,2,3.0,2.0,6.0,2.0,1.0,1.0,2.0,3.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,3,2,5.0,1.0,4.0,1.0,1.0,2.0,2.0,3.0,NaN
2,1.0,101.0,101.0,4.0,4.0,4.0,2.0,88.0,4.0,12,2,3.0,7.0,3.0,1.0,1.0,1.0,1.0,1.0,57.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,4.0,10,1,2.0,7.0,3.0,1.0,1.0,1.0,2.0,3.0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,5,2,1.0,1.0,99.0,1.0,2.0,1.0,2.0,3.0,NaN

# Cleaning

### Drop Missing Values
- remove rows with missing values across the selected diabetes-management variables

In [55]:
features_df = features_df.dropna()
features_df.shape

(16610, 20)

### diabedu
- whether respondent ever took a diabetes management class
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [56]:
features_df = features_df[features_df['diabedu'] != 7]
features_df = features_df[features_df['diabedu'] != 9]
features_df['diabedu'] = features_df['diabedu'].replace({2: 0})
features_df['diabedu'].unique()

array([1., 0.])

### feetchk3
- how often respondent checks their feet for sores or irritation
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [57]:
features_df = features_df[features_df['feetchk3'] != 777]
features_df = features_df[features_df['feetchk3'] != 999]
features_df['feetchk3'].unique()

array([101., 207., 404., 102., 888., 204., 103., 201., 330., 202., 301.,
       402., 302., 203., 401., 205., 106., 105., 104., 304., 315., 107.,
       206., 303., 406., 333., 231., 408., 410., 110., 305., 320., 130.,
       450., 365., 403., 124., 310., 405., 108., 475., 175., 210., 214.,
       350., 375., 470., 114., 412., 230., 220., 409., 360., 120., 415.,
       499., 209., 308., 436., 208., 306., 407., 411., 199., 399., 465.,
       115., 222., 395., 174., 311., 190., 109., 331.])

### bldsugar
- how often respondent checks blood sugar
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [58]:
features_df = features_df[features_df['bldsugar'] != 777]
features_df = features_df[features_df['bldsugar'] != 999]
features_df['bldsugar'].unique()

array([101., 403., 103., 203., 102., 201., 888., 205., 404., 202., 204.,
       405., 107., 104., 402., 206., 302., 301., 308., 207., 304., 303.,
       105., 106., 305., 108., 306., 210., 312., 215., 401., 330., 307.,
       230., 320., 331., 315., 406., 198., 490., 325., 120., 365., 110.,
       248., 375., 360., 424., 214., 475., 220., 212., 150., 109., 410.,
       472., 467., 125., 420., 488., 316., 430., 412., 363., 321., 370.,
       452., 421., 407., 450., 310., 333., 216., 499., 408., 409., 228.,
       208., 318., 448., 115., 112., 188., 209., 130., 199., 399., 222.,
       221., 114., 111., 123., 175., 309., 218., 345.])

### doctdiab
- number of times respondent saw a health professional for diabetes in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining counts as numeric values

In [59]:
features_df = features_df[features_df['doctdiab'] != 77]
features_df = features_df[features_df['doctdiab'] != 99]
features_df['doctdiab'].unique()

array([ 4.,  3.,  7.,  2., 88., 12.,  1., 10.,  8.,  5.,  6., 11., 24.,
        9., 15., 25., 20., 36., 18., 30., 50., 43., 14., 13., 16., 52.,
       48., 33., 76., 35., 45., 17., 40., 60., 28., 39., 47., 22.])

### chkhemo3
- number of A1c checks in the past year
- remove `77` and `99` because they represent don't know / refused
- keep the remaining numeric counts so you can later convert this into at least twice per year vs less than twice

In [60]:
features_df = features_df[features_df['chkhemo3'] != 77]
features_df = features_df[features_df['chkhemo3'] != 99]
features_df['chkhemo3'].unique()

array([ 4.,  3.,  2.,  1., 88.,  8., 12.,  5.,  6., 98., 15., 10.,  7.,
        9., 43., 20., 76., 30., 24., 52., 25., 60., 13., 14., 40., 48.,
       11., 18., 74., 33., 50., 36.])

### feetchk
- number of times respondent had their feet checked by a health professional in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining values as valid counts so this can later be recoded into annual foot check vs not annual foot check

In [61]:
features_df = features_df[features_df['feetchk'] != 77]
features_df = features_df[features_df['feetchk'] != 99]
features_df['feetchk'].unique()

array([ 4.,  2.,  1., 88.,  3., 12.,  5.,  6.,  7., 50., 52.,  8., 24.,
       15., 58., 10., 47., 20., 18., 60., 30., 76.,  9., 48., 21., 11.,
       13., 73., 26., 36., 14., 25., 32., 44., 45., 40., 16., 56.])

### eyeexam1
- how recently respondent had a dilated eye exam
- remove `7` and `9` because they represent don't know / refused
- keep the remaining categories so you can later convert this into annual exam vs not annual

In [62]:
features_df = features_df[features_df['eyeexam1'] != 7]
features_df = features_df[features_df['eyeexam1'] != 9]
features_df['eyeexam1'].unique()

array([2., 1., 3., 4., 8.])

### menthlth
- number of bad mental health days in the past 30 days
- change `88` to `0` because BRFSS uses `88` for none
- remove `77` and `99` because they indicate don't know / refused
- keep this as a count variable from `0` to `30`

In [63]:
features_df['menthlth'] = features_df['menthlth'].replace({88: 0})
features_df = features_df[features_df['menthlth'] != 77]
features_df = features_df[features_df['menthlth'] != 99]
features_df['menthlth'].unique()

array([ 0., 30., 15., 12., 10.,  3.,  2.,  1., 14., 25.,  6.,  5.,  8.,
       20.,  4.,  7.,  9., 29., 13., 21., 17., 28., 22., 16., 18., 27.,
       11., 24., 26., 19., 23.])

### educa
- respondent education level
- remove `9` because it represents refused / missing
- keep the remaining categories as an ordinal education variable

In [64]:
features_df = features_df[features_df['educa'] != 9]
features_df['educa'].unique()

array([4., 3., 5., 6., 2., 1.])

### x.ageg5yr
- respondent age group
- remove `14` because it corresponds to missing / refused rather than a real age group
- keep the remaining ordered age-group categories as valid responses

In [65]:
features_df = features_df[features_df['x.ageg5yr'] != 14]
features_df['x.ageg5yr'].unique()

array([12,  8, 11, 10,  6,  9, 13,  7,  2,  5,  4,  3,  1])

### sex1
- whether respondent is male
- change `2` to `0` so female is `0` and male remains `1`
- this makes the variable binary and easier to interpret in modeling

In [66]:
features_df['sex1'] = features_df['sex1'].replace({2: 0})
features_df['sex1'].unique()

array([0, 1, 9, 7])

### marital
- respondent marital or partnered status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into married/partnered vs not married/partnered

In [67]:
features_df = features_df[features_df['marital'] != 9]
features_df['marital'].unique()

array([3., 1., 2., 4., 6., 5.])

### employ1
- respondent employment status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into employed vs not employed

In [68]:
features_df = features_df[features_df['employ1'] != 9]
features_df['employ1'].unique()

array([7., 1., 8., 5., 2., 3., 4., 6.])

### income2
- annual household income category
- remove `77` and `99` because they represent don't know / refused
- keep the remaining categories as an ordinal income variable

In [69]:
features_df = features_df[features_df['income2'] != 77]
features_df = features_df[features_df['income2'] != 99]
features_df['income2'].unique()

array([3., 8., 4., 2., 6., 5., 7., 1.])

### x.urbstat
- whether respondent lives in an urban or rural county
- inspect values here because this is a derived variable
- if only valid categories are present, no additional cleaning is needed

In [70]:
features_df['x.urbstat'].unique()

array([1., 2.])

### persdoc2
- whether respondent has at least one personal health care provider
- remove `7` and `9` because they represent don't know / refused
- keep the valid categories, then collapse later if you want at least one provider vs none

In [71]:
features_df = features_df[features_df['persdoc2'] != 7]
features_df = features_df[features_df['persdoc2'] != 9]
features_df['persdoc2'].unique()

array([1., 2., 3.])

### hlthpln1
- whether respondent has any health care coverage
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no coverage is `0` and yes remains `1`

In [72]:
features_df = features_df[features_df['hlthpln1'] != 7]
features_df = features_df[features_df['hlthpln1'] != 9]
features_df['hlthpln1'] = features_df['hlthpln1'].replace({2: 0})
features_df['hlthpln1'].unique()

array([1., 0.])

### addepev2
- whether respondent was ever told they had a depressive disorder
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [73]:
features_df = features_df[features_df['addepev2'] != 7]
features_df = features_df[features_df['addepev2'] != 9]
features_df['addepev2'] = features_df['addepev2'].replace({2: 0})
features_df['addepev2'].unique()

array([1., 0.])

### diabete3
- remove `7` and `9` because they represent don't know / refused
- inspect the remaining diabetes-status values in the diabetes-management subset
- keep this as an inspection step rather than forcing the dataset to diagnosed diabetes only

In [74]:
features_df = features_df[features_df['diabete3'] != 7]
features_df = features_df[features_df['diabete3'] != 9]
features_df.groupby(['diabete3']).size()

diabete3
1.0    11423
dtype: int64

### diabage2
- respondent age when first told they had diabetes
- remove `98` and `99` because they represent don't know / refused
- keep the remaining values as a numeric age-at-diagnosis variable

In [75]:
features_df = features_df[features_df['diabage2'] != 98]
features_df = features_df[features_df['diabage2'] != 99]
features_df['diabage2'].unique()

array([57., 46., 60., 48., 58., 73., 67., 62., 70., 14., 78., 66., 61.,
       52., 19., 38., 50., 47., 45., 65., 68., 54., 63., 40., 76., 29.,
       42., 35., 12., 36., 71., 55., 56., 28., 22., 53., 43., 41., 23.,
       72., 15., 30., 69., 64., 33., 26., 74., 39., 59., 20.,  8., 84.,
       32., 25., 51., 80., 82., 49., 34., 24., 75., 18., 37.,  9., 44.,
       27., 10.,  6., 31., 16.,  3., 79.,  5.,  4., 81., 17., 13., 77.,
       90., 85., 11., 21.,  7.,  1., 89.,  2., 94., 87., 83., 93., 86.,
       88.])

### Rename Management Columns
- rename the cleaned diabetes-management variables to readable analysis names before EDA and export

In [76]:
features_df = features_df.rename(columns={
    'diabedu': 'Diabetes_Class',
    'feetchk3': 'Foot_Self_Check_Freq',
    'bldsugar': 'Blood_Sugar_Check_Freq',
    'doctdiab': 'Doctor_Visit_Diabetes_Freq',
    'chkhemo3': 'A1C_Check_Freq',
    'feetchk': 'Professional_Foot_Check_Freq',
    'eyeexam1': 'Eye_Exam_Recency',
    'menthlth': 'Bad_Mental_Health_Days',
    'educa': 'Education',
    'x.ageg5yr': 'Age_Group',
    'sex1': 'Male',
    'marital': 'Marital_Status',
    'employ1': 'Employment_Status',
    'income2': 'Income',
    'x.urbstat': 'Urban_Rural_Status',
    'persdoc2': 'Personal_Doctor',
    'hlthpln1': 'Health_Coverage',
    'addepev2': 'Depressive_Disorder',
    'diabete3': 'Diabetes_Status',
    'diabage2': 'Diabetes_Age'
})

In [77]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
2,1.0,101.0,101.0,4.0,4.0,4.0,2.0,0.0,4.0,12,0,3.0,7.0,3.0,1.0,1.0,1.0,1.0,1.0,57.0
8,0.0,101.0,403.0,3.0,3.0,2.0,1.0,0.0,4.0,8,1,1.0,1.0,8.0,2.0,1.0,1.0,0.0,1.0,46.0
13,0.0,207.0,103.0,4.0,2.0,2.0,3.0,0.0,4.0,11,0,3.0,7.0,4.0,1.0,1.0,1.0,0.0,1.0,60.0
21,0.0,102.0,101.0,7.0,1.0,88.0,4.0,30.0,5.0,6,0,1.0,1.0,4.0,2.0,1.0,0.0,1.0,1.0,48.0
29,0.0,888.0,203.0,3.0,2.0,3.0,2.0,15.0,3.0,10,1,3.0,1.0,6.0,1.0,1.0,1.0,0.0,1.0,58.0

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [78]:
features_df.shape

(10964, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [79]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
2,1.0,101.0,101.0,4.0,4.0,4.0,2.0,0.0,4.0,12,0,3.0,7.0,3.0,1.0,1.0,1.0,1.0,1.0,57.0
8,0.0,101.0,403.0,3.0,3.0,2.0,1.0,0.0,4.0,8,1,1.0,1.0,8.0,2.0,1.0,1.0,0.0,1.0,46.0
13,0.0,207.0,103.0,4.0,2.0,2.0,3.0,0.0,4.0,11,0,3.0,7.0,4.0,1.0,1.0,1.0,0.0,1.0,60.0
21,0.0,102.0,101.0,7.0,1.0,88.0,4.0,30.0,5.0,6,0,1.0,1.0,4.0,2.0,1.0,0.0,1.0,1.0,48.0
29,0.0,888.0,203.0,3.0,2.0,3.0,2.0,15.0,3.0,10,1,3.0,1.0,6.0,1.0,1.0,1.0,0.0,1.0,58.0

In [80]:
features_df.tail()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
426414,1.0,103.0,103.0,4.0,3.0,4.0,2.0,7.0,5.0,9,1,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,50.0
426419,1.0,301.0,102.0,2.0,2.0,2.0,2.0,0.0,5.0,8,1,1.0,1.0,7.0,2.0,2.0,1.0,0.0,1.0,35.0
426429,0.0,101.0,401.0,1.0,1.0,1.0,2.0,0.0,5.0,12,1,6.0,7.0,8.0,1.0,1.0,1.0,0.0,1.0,65.0
426475,0.0,888.0,401.0,1.0,1.0,88.0,3.0,0.0,5.0,9,0,1.0,2.0,6.0,1.0,1.0,1.0,0.0,1.0,57.0
426481,1.0,202.0,202.0,20.0,20.0,10.0,1.0,0.0,4.0,10,1,1.0,8.0,4.0,1.0,1.0,1.0,0.0,1.0,50.0

### Save Management Dataset
- save the cleaned diabetes module dataframe to CSV

In [83]:
features_df.to_csv('../data/clean/2018_brfss_diabetes_module_features.csv', index=False)