# Getting Data

### Imports

In [1145]:
import pandas as pd

### Define Your Path

In [1146]:
path = '/Users/rj/Repos/615-ML-Project/data/raw/csv'

### Survey Year

In [1147]:
year = '2020'

### Load CSV

In [1148]:
df = pd.read_csv(f'{path}/brfss{year}.csv')

### Dataset Shape

In [1149]:
df.shape

(401958, 279)

### Display Settings

In [1150]:
pd.set_option('display.max_columns', 500)
df.head()

,x.state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,x.psu,ctelenm1,pvtresd1,colghous,statere1,celphone,ladult1,colgsex,numadult,landsex,nummen,numwomen,respslct,safetime,ctelnum1,cellfon5,cadult1,cellsex,pvtresd3,cclghous,cstate1,landline,hhadult,sexvar,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,exerany2,sleptim1,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd2,havarth4,addepev3,chckdny2,diabete4,diabage3,lastden4,rmvteth4,marital,educa,renthom1,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income2,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,stopsmk2,lastsmk2,usenow3,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,flshtmy3,shingle2,pneuvac4,fall12mn,fallinj4,seatbelt,drnkdri2,hadmam,howlong,hadpap2,lastpap2,hpvtest,hplsttst,hadhyst2,pcpsaad3,pcpsadi1,pcpsare1,psatest1,psatime,pcpsars1,colnscpy,colntest,sigmscpy,sigmtest,bldstol1,lstblds4,stooldna,sdnatest,vircolon,vclntest,hivtst7,hivtstd3,hivrisk5,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hlthcvr1,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvalzd,crgvper1,crgvhou1,crgvexpt,ecigaret,ecignow,marijan1,usemrjn2,rsnmrjn1,lcsfirst,lcslast,lcsnumcg,lcsctscn,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,pcpsade1,pcdmdec1,hpvadvc4,hpvadsht,tetanus1,imfvpla1,birthsex,somale,sofemale,trnsgndr,acedeprs,acedrink,acedrugs,aceprisn,acedivrc,acepunch,acehurt1,aceswear,acetouch,acetthem,acehvsex,rcsgendr,rcsrltn2,casthdx2,casthno2,qstver,qstlang,x.metstat,x.urbstat,mscode,x.ststr,x.strwt,x.rawrake,x.wt2rake,x.imprace,x.chispnc,x.crace1,x.cprace,x.cllcpwt,x.dualuse,x.dualcor,x.llcpwt2,x.llcpwt,x.rfhlth,x.phys14d,x.ment14d,x.hcvu651,x.totinda,x.michd,x.ltasth1,x.casthm1,x.asthms1,x.drdxar2,x.exteth3,x.alteth3,x.denvst3,x.prace1,x.mrace1,x.hispanc,x.race,x.raceg21,x.racegr3,x.raceprv,x.sex,x.ageg5yr,x.age65yr,x.age80,x.age.g,htin4,htm4,wtkg3,x.bmi5,x.bmi5cat,x.rfbmi5,x.chldcnt,x.educag,x.incomg,x.smoker3,x.rfsmok3,drnkany5,drocdy3.,x.rfbing5,x.drnkwk1,x.rfdrhv7,x.flshot7,x.pneumo3,x.rfseat2,x.rfseat3,x.drnkdrv,x.rfmam22,x.mam5023,x.rfpap35,x.rfpsa23,x.clnscpy,x.sgmscpy,x.sgms10y,x.rfblds4,x.stoldna,x.vircoln,x.sbontim,x.crcrec1,x.aidtst4
0,1,1,1042020,1,4,2020,1100,2020000001,2020000001,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,3.0,30.0,3.0,2.0,3.0,1.0,4.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,35.0,1.0,2.0,2.0,6.0,1.0,2.0,NaN,1.0,2.0,4.0,88.0,1.0,NaN,106.0,507.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,1.0,3.0,1.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0,21994.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,1,0.465411,460.002849,284.335672,1,2,3,2,1,2.0,2,2,1,1.0,2,NaN,1,1.0,1.0,2,1.0,1.0,1.0,1.0,2,8,1,56,5,67.0,170.0,4808.0,1660.0,1.0,1,1,4,1,1,2,2,0,1,0,1,NaN,NaN,1,1,9,2.0,2.0,NaN,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
1,1,1,2072020,2,7,2020,1200,2020000002,2020000002,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,NaN,1.0,1.0,3.0,6.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,170.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,2,NaN,NaN,NaN,NaN,1,0.465411,460.002849,171.283329,1,1,1,9,1,2.0,2,1,2,1.0,2,1.0,1,2.0,2.0,2,2.0,2.0,2.0,2.0,2,10,2,65,6,64.0,163.0,7711.0,2918.0,3.0,2,1,4,9,9,9,9,900,9,99900,9,9.0,9.0,9,9,9,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
2,1,1,1232020,1,23,2020,1100,2020000003,2020000003,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,7.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,7777.0,508.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11012,279.748901,1.0,279.748901,2,NaN,NaN,NaN,NaN,1,0.465411,1847.859106,1334.368863,1,1,1,9,1,2.0,1,1,3,1.0,9,9.0,1,2.0,2.0,2,2.0,2.0,2.0,2.0,2,10,2,65,6,68.0,173.0,NaN,NaN,NaN,9,1,3,5,4,1,2,0,1,0,1,1.0,2.0,1,1,9,1.0,1.0,1.0,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0
3,1,1,1092020,1,9,2020,1100,2020000004,2020000004,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,2.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,1.0,3.0,4.0,1.0,9.0,NaN,9.0,2.0,5.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,2.0,NaN,1.0,7.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,9,NaN,1472.417322,1297.486618,1,1,1,9,2,2.0,1,1,3,2.0,2,1.0,9,1.0,1.0,2,1.0,1.0,1.0,1.0,2,13,2,80,6,NaN,NaN,NaN,NaN,NaN,9,1,2,9,4,1,2,0,1,0,1,2.0,2.0,1,1,9,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,1,1,1042020,1,4,2020,1100,2020000005,2020000005,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,8.0,3.0,6.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,77.0,NaN,126.0,506.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,1.0,2.0,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,NaN,7.0,NaN,7.0,NaN,2.0,NaN,7.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,9,NaN,1472.417322,454.815127,1,1,1,9,1,2.0,1,1,3,2.0,1,1.0,9,1.0,1.0,2,1.0,1.0,1.0,1.0,2,13,2,80,6,66.0,168.0,5715.0,2034.0,2.0,1,1,4,9,4,1,2,0,1,0,1,1.0,1.0,1,1,9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

### Feature List

In [1151]:
features = [
    # Core 1: Health Status
    'genhlth',
    # Core 2: Healthy Days
    'physhlth',
    'menthlth',
    'poorhlth',
    # Core 3: Health Care Access
    'hlthpln1',
    'persdoc2',
    'medcost',
    'checkup1',
    # Core 4: Exercise
    'exerany2',
    # Core Section 5: Inadequate Sleep
    'sleptim1',
    # Core Section 6: Chronic Health Conditions
    'cvdinfr4',
    'cvdcrhd4',
    'cvdstrk3',
    'asthma3',
    'asthnow',
    'chcscncr',
    'chcocncr',
    'chccopd2',
    'havarth4',
    'addepev3',
    'chckdny2',
    'diabete4',
    'diabage3',
    # Core Section 7: Oral Health
    'lastden4',
    'rmvteth4',
    # Core Section 8: Demographics
    'x.ageg5yr',
    'x.hispanc',
    'x.mrace1',
    'x.prace1',
    'marital',
    'educa',
    'renthom1',
    'x.urbstat',
    'numhhol3',
    'numphon3',
    'cpdemo1b',
    'veteran3',
    'employ1',
    'children',
    'income2',
    'pregnant',
    'weight2',
    'height3',
    # Core Section 9: Disability
    'deaf',
    'blind',
    'decide',
    'diffwalk',
    'diffdres',
    'diffalon',
    # Core Section 10: Tobacco Use
    'smoke100',
    'smokday2',
    'stopsmk2',
    'lastsmk2',
    'usenow3',
    # Core Section 11: Alcohol Consumption
    'alcday5',
    'avedrnk3',
    'drnk3ge5',
    'maxdrnks',
    # Core Section 12: Immunization
    'flushot7',
    'shingle2',
    'pneuvac4',
    # Core Section 13: Falls
    'fall12mn',
    'fallinj4',
    # Core Section 14: Seat Belt Use and Drinking and Driving
    'seatbelt',
    'drnkdri2',
    # Core Section 15: Breast and Cervical Cancer Screening
    'hadmam',
    'howlong',
    'hadpap2',
    'lastpap2',
    'hpvtest',
    'hplsttst',
    'hadhyst2',
    # Core Section 16: Prostate Cancer Screening
    'pcpsaad3',
    'pcpsadi1',
    'pcpsare1',
    'psatest1',
    'psatime',
    'pcpsars1',
    # Core Section 17: Colorectal Cancer Screening
    'colnscpy',
    'colntest',
    'sigmscpy',
    'sigmtest',
    'bldstol1',
    'lstblds4',
    'stooldna',
    'sdnatest',
    'vircolon',
    'vclntest',
    # Core Section 18: H.I.V./AIDS
    'hivtst7',
    'hivtstd3',
    'hivrisk5',
    # Module 1: Prediabetes
    'pdiabtst',
    'prediab1',
    # Module 2: Diabetes
    'insulin1',
    'bldsugar',
    'feetchk3',
    'doctdiab',
    'chkhemo3',
    'feetchk',
    'eyeexam1',
    'diabeye',
    'diabedu',
    # Module 3: ME/CFS
    'toldcfs',
    'havecfs',
    'workcfs',
    # Module 4: Hepatitis Treatment 
    'toldhepc',
    'trethepc',
    'prirhepc',
    'havehepc',
    'havehepb',
    'medshepb',
    # Module 5: Health Care Access
    'hlthcvr1',
    'cimemlos',
    'cdhouse',
    'cdassist',
    'cdhelp',
    'cdsocial',
    'cddiscus',
    # Module 7: Caregiver
    'caregiv1',
    'crgvrel4',
    'crgvlng1',
    'crgvhrs1',
    'crgvprb3',
    'crgvper1',
    'crgvhou1',
    'crgvexpt',
    # Module 8: E-Cigarettes
    'ecigaret',
    'ecignow',
    # Module 9: Marijuana Use
    'marijan1',
    'usemrjn2',
    'rsnmrjn1',
    # Module 10: Lung Cancer Screening
    'lcsfirst',
    'lcslast',
    'lcsnumcg',
    'lcsctscn',
    # Module 11: Cancer Survivorship: Type of Cancer
    'cncrdiff',
    'cncrage',
    'cncrtyp1',
    # Module 12: Cancer Survivorship: Course of Treatment
    'csrvtrt3',
    'csrvdoc1',
    'csrvsum',
    'csrvrtrn',
    'csrvinst',
    'csrvinsr',
    'csrvdein',
    'csrvclin',
    # Module 13: Cancer Survivorship: Pain Management
    'csrvpain',
    'csrvctl2',
    # Module 14: Prostate Cancer Screening Decision Making
    'pcpsade1',
    'pcdmdec1',
    # Module 15: Adult Human Papillomavirus (HPV) - Vaccination
    'hpvadvc4',
    'hpvadsht',
    # Module 16: Tetanus Diphtheria (Tdap) (Adults)
    'tetanus1',
    # Module 17: Place of Flu Vaccination
    # Module 18: Industry and Occupation
    # Module 19: Sex at Birth
    'birthsex',
    # Module 20: Sexual Orientation and Gender Identity (SOGI)
    'somale',
    'sofemale',
    'trnsgndr',
    # Module 21: Adverse Childhood Experiences
    # Module 22: Random Child Selection
    'rcsgendr',
    'rcsrltn2',
    # Module 23: Childhood Asthma Prevalence
    'casthdx2',
    'casthno2',
    # Asthma Call-Back Permission Script
]

In [1152]:
df_copy = df[features].copy()

### Analysis Shape

In [1153]:
df_copy.shape

(401958, 161)

### Analysis Preview

In [1154]:
df_copy.head()

,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,exerany2,sleptim1,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd2,havarth4,addepev3,chckdny2,diabete4,diabage3,lastden4,rmvteth4,x.ageg5yr,x.hispanc,x.mrace1,x.prace1,marital,educa,renthom1,x.urbstat,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income2,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,stopsmk2,lastsmk2,usenow3,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,shingle2,pneuvac4,fall12mn,fallinj4,seatbelt,drnkdri2,hadmam,howlong,hadpap2,lastpap2,hpvtest,hplsttst,hadhyst2,pcpsaad3,pcpsadi1,pcpsare1,psatest1,psatime,pcpsars1,colnscpy,colntest,sigmscpy,sigmtest,bldstol1,lstblds4,stooldna,sdnatest,vircolon,vclntest,hivtst7,hivtstd3,hivrisk5,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hlthcvr1,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvper1,crgvhou1,crgvexpt,ecigaret,ecignow,marijan1,usemrjn2,rsnmrjn1,lcsfirst,lcslast,lcsnumcg,lcsctscn,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,pcpsade1,pcdmdec1,hpvadvc4,hpvadsht,tetanus1,birthsex,somale,sofemale,trnsgndr,rcsgendr,rcsrltn2,casthdx2,casthno2
0,2.0,3.0,30.0,3.0,2.0,3.0,1.0,4.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,35.0,1.0,2.0,8,2,1.0,1.0,2.0,6.0,1.0,1.0,2.0,NaN,1.0,2.0,4.0,88.0,1.0,NaN,106.0,507.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,2.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,3.0,1.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0,21994.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,NaN,1.0,1.0,10,2,2.0,2.0,3.0,6.0,1.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,170.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,7.0,10,2,2.0,2.0,1.0,5.0,1.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,7777.0,508.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,2.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,1.0,13,2,1.0,1.0,3.0,4.0,1.0,1.0,9.0,NaN,9.0,2.0,5.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,2.0,2.0,88.0,NaN,1.0,NaN,2.0,NaN,1.0,7.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,8.0,13,2,1.0,1.0,3.0,6.0,2.0,1.0,2.0,NaN,8.0,2.0,7.0,88.0,77.0,NaN,126.0,506.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,1.0,2.0,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,NaN,7.0,NaN,7.0,NaN,2.0,NaN,7.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning

## Core 1: Health Status

### genhlth
**Question:** Would you say that in general your health is excellent, very good, good, fair, or poor?
- `1` = Excellent
- `2` = Very Good
- `3` = Good
- `4` = Fair
- `5` = Poor
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1155]:
df_copy['genhlth'] = df_copy['genhlth'].replace([7, 9], pd.NA)
df_copy['genhlth'].value_counts(dropna=False)

genhlth
2.0     138139
3.0     119502
1.0      81660
4.0      46239
5.0      15457
<NA>       953
NaN          8
Name: count, dtype: int64

## Core 2: Healthy Days

### physhlth
**Question:** For how many days during the past 30 days was your physical health not good?
- `1-30` = number of bad physical health days in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [1156]:
df_copy['physhlth'] = df_copy['physhlth'].replace({88: 0})
df_copy['physhlth'] = df_copy['physhlth'].replace([77, 99], pd.NA)
df_copy['physhlth'].value_counts(dropna=False)

physhlth
0.0     278671
30.0     25049
2.0      17864
1.0      12492
3.0      10371
5.0       9192
<NA>      8686
10.0      6707
15.0      6247
7.0       5692
4.0       5396
20.0      4018
14.0      3561
6.0       1531
25.0      1460
8.0       1149
21.0       774
12.0       735
28.0       574
29.0       265
9.0        234
18.0       214
16.0       172
27.0       165
17.0       129
13.0       117
11.0       108
22.0       106
24.0        87
26.0        83
23.0        62
19.0        42
NaN          5
Name: count, dtype: int64

### menthlth
**Question:** For how many days during the past 30 days was your mental health not good?
- `1-30` = number of bad mental health days in past 30 days
- `77` = Don't know / Not sure
- `88` = None
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [1157]:
df_copy['menthlth'] = df_copy['menthlth'].replace({88: 0})
df_copy['menthlth'] = df_copy['menthlth'].replace([77, 99], pd.NA)
df_copy['menthlth'].value_counts(dropna=False)

menthlth
0.0     255707
30.0     22297
2.0      19591
5.0      16705
10.0     12656
3.0      12500
15.0     12006
1.0      11144
<NA>      7924
20.0      6544
7.0       6524
4.0       6344
14.0      2475
25.0      2394
6.0       1794
8.0       1314
12.0       909
28.0       643
21.0       436
29.0       400
18.0       255
9.0        252
16.0       189
27.0       166
17.0       159
13.0       137
22.0       114
11.0       109
24.0        88
23.0        77
26.0        76
19.0        24
NaN          5
Name: count, dtype: int64

### poorhlth
**Question:** During the past 30 days, for how many days did poor physical or mental health keep you from doing your usual activities?
- `1-30` = number of days poor physical or mental health kept respondent from usual activities in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [1158]:
df_copy['poorhlth'] = df_copy['poorhlth'].replace({88: 0})
df_copy['poorhlth'] = df_copy['poorhlth'].replace([77, 99], pd.NA)
df_copy['poorhlth'].value_counts(dropna=False)

poorhlth
NaN     200343
0.0     111321
30.0     15239
2.0      10626
5.0       8550
1.0       8011
15.0      7308
3.0       6945
10.0      6854
<NA>      5267
7.0       4259
20.0      4226
4.0       3888
14.0      2342
25.0      1511
6.0       1220
8.0       1010
12.0       654
21.0       519
28.0       331
9.0        231
18.0       195
16.0       183
29.0       137
17.0       126
27.0       121
13.0       111
22.0       107
11.0        89
26.0        80
24.0        70
23.0        48
19.0        36
Name: count, dtype: int64

## Core 3: Health Care Access

### hlthpln1
**Question:** Do you have any kind of health care coverage?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1159]:
df_copy['hlthpln1'] = df_copy['hlthpln1'].replace({2: 0})
df_copy['hlthpln1'] = df_copy['hlthpln1'].replace([7, 9], pd.NA)
df_copy['hlthpln1'].value_counts(dropna=False)

hlthpln1
1.0     365862
0.0      34034
<NA>      2059
NaN          3
Name: count, dtype: int64

### persdoc2
**Question:** Do you have one person you think of as your personal doctor or health care provider, more than one, or none?
- `1` = Yes, only one personal doctor
- `2` = More than one
- `3` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1160]:
df_copy['persdoc2'] = df_copy['persdoc2'].replace([7, 9], pd.NA)
df_copy['persdoc2'].value_counts(dropna=False)

persdoc2
1.0     302667
3.0      69995
2.0      27254
<NA>      2039
NaN          3
Name: count, dtype: int64

### medcost
**Question:** Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1161]:
df_copy['medcost'] = df_copy['medcost'].replace({2: 0})
df_copy['medcost'] = df_copy['medcost'].replace([7, 9], pd.NA)
df_copy['medcost'].value_counts(dropna=False)

medcost
0.0     366252
1.0      34568
<NA>      1135
NaN          3
Name: count, dtype: int64

### checkup1
**Question:** About how long has it been since you last visited a doctor for a routine checkup?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 5 years
- `4` = 5 or more years ago
- `7` = Don't know / Not sure
- `8` = Never
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1162]:
df_copy['checkup1'] = df_copy['checkup1'].replace([7, 9], pd.NA)
df_copy['checkup1'].value_counts(dropna=False)

checkup1
1.0     311146
2.0      45429
3.0      20448
4.0      17828
<NA>      5020
8.0       2082
NaN          5
Name: count, dtype: int64

## Core 4: Exercise

### exerany2
**Question:** During the past month, other than your regular job, did you participate in any physical activities or exercises?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1163]:
df_copy['exerany2'] = df_copy['exerany2'].replace({2: 0})
df_copy['exerany2'] = df_copy['exerany2'].replace([7, 9], pd.NA)
df_copy['exerany2'].value_counts(dropna=False)

exerany2
1.0     305883
0.0      95393
<NA>       679
NaN          3
Name: count, dtype: int64

## Core Section 5: Inadequate Sleep

### sleptim1
**Question:** On average, how many hours of sleep do you get in a 24-hour period?
- `1-24` = number of hours of sleep in a 24-hour period
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1164]:
df_copy['sleptim1'] = df_copy['sleptim1'].replace([77, 99], pd.NA)
df_copy['sleptim1'].value_counts(dropna=False)

sleptim1
8.0     122257
7.0     118786
6.0      82622
5.0      24431
9.0      19836
4.0       9985
10.0      9982
<NA>      4691
12.0      2865
3.0       2680
2.0       1102
1.0        762
11.0       595
14.0       309
16.0       308
15.0       258
18.0       142
13.0       140
20.0        92
24.0        53
17.0        27
22.0        13
23.0        10
19.0         7
NaN          3
21.0         2
Name: count, dtype: int64

## Core Section 6: Chronic Health Conditions

### cvdinfr4
**Question:** What is the respondent's status for heart attack?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1165]:
df_copy['cvdinfr4'] = df_copy['cvdinfr4'].replace({2: 0})
df_copy['cvdinfr4'] = df_copy['cvdinfr4'].replace([7, 9], pd.NA)
df_copy['cvdinfr4'].value_counts(dropna=False)

cvdinfr4
0.0     377918
1.0      21957
<NA>      2077
NaN          6
Name: count, dtype: int64

### cvdcrhd4
**Question:** What is the respondent's status for coronary heart disease?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1166]:
df_copy['cvdcrhd4'] = df_copy['cvdcrhd4'].replace({2: 0})
df_copy['cvdcrhd4'] = df_copy['cvdcrhd4'].replace([7, 9], pd.NA)
df_copy['cvdcrhd4'].value_counts(dropna=False)

cvdcrhd4
0.0     376058
1.0      22598
<NA>      3299
NaN          3
Name: count, dtype: int64

### cvdstrk3
**Question:** What is the respondent's status for stroke?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1167]:
df_copy['cvdstrk3'] = df_copy['cvdstrk3'].replace({2: 0})
df_copy['cvdstrk3'] = df_copy['cvdstrk3'].replace([7, 9], pd.NA)
df_copy['cvdstrk3'].value_counts(dropna=False)

cvdstrk3
0.0     385095
1.0      15677
<NA>      1183
NaN          3
Name: count, dtype: int64

### asthma3
**Question:** What is the respondent's status for ever asthma?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1168]:
df_copy['asthma3'] = df_copy['asthma3'].replace({2: 0})
df_copy['asthma3'] = df_copy['asthma3'].replace([7, 9], pd.NA)
df_copy['asthma3'].value_counts(dropna=False)

asthma3
0.0     346449
1.0      54142
<NA>      1364
NaN          3
Name: count, dtype: int64

### asthnow
**Question:** What is the respondent's status for current asthma?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1169]:
df_copy['asthnow'] = df_copy['asthnow'].replace({2: 0})
df_copy['asthnow'] = df_copy['asthnow'].replace([7, 9], pd.NA)
df_copy['asthnow'].value_counts(dropna=False)

asthnow
NaN     347817
1.0      37996
0.0      14586
<NA>      1559
Name: count, dtype: int64

### chcscncr
**Question:** What is the respondent's status for skin cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1170]:
df_copy['chcscncr'] = df_copy['chcscncr'].replace({2: 0})
df_copy['chcscncr'] = df_copy['chcscncr'].replace([7, 9], pd.NA)
df_copy['chcscncr'].value_counts(dropna=False)

chcscncr
0.0     364269
1.0      36414
<NA>      1272
NaN          3
Name: count, dtype: int64

### chcocncr
**Question:** What is the respondent's status for other cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1171]:
df_copy['chcocncr'] = df_copy['chcocncr'].replace({2: 0})
df_copy['chcocncr'] = df_copy['chcocncr'].replace([7, 9], pd.NA)
df_copy['chcocncr'].value_counts(dropna=False)

chcocncr
0.0     363989
1.0      36786
<NA>      1180
NaN          3
Name: count, dtype: int64

### chccopd2
**Question:** What is the respondent's status for copd?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1172]:
df_copy['chccopd2'] = df_copy['chccopd2'].replace({2: 0})
df_copy['chccopd2'] = df_copy['chccopd2'].replace([7, 9], pd.NA)
df_copy['chccopd2'].value_counts(dropna=False)

chccopd2
0.0     368560
1.0      31443
<NA>      1950
NaN          5
Name: count, dtype: int64

### havarth4
**Question:** What is the respondent's status for arthritis?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1173]:
df_copy['havarth4'] = df_copy['havarth4'].replace({2: 0})
df_copy['havarth4'] = df_copy['havarth4'].replace([7, 9], pd.NA)
df_copy['havarth4'].value_counts(dropna=False)

havarth4
0.0     275176
1.0     124479
<NA>      2298
NaN          5
Name: count, dtype: int64

### addepev3
**Question:** What is the respondent's status for depressive disorder?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1174]:
df_copy['addepev3'] = df_copy['addepev3'].replace({2: 0})
df_copy['addepev3'] = df_copy['addepev3'].replace([7, 9], pd.NA)
df_copy['addepev3'].value_counts(dropna=False)

addepev3
0.0     324035
1.0      75820
<NA>      2097
NaN          6
Name: count, dtype: int64

### chckdny2
**Question:** What is the respondent's status for kidney disease?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1175]:
df_copy['chckdny2'] = df_copy['chckdny2'].replace({2: 0})
df_copy['chckdny2'] = df_copy['chckdny2'].replace([7, 9], pd.NA)
df_copy['chckdny2'].value_counts(dropna=False)

chckdny2
0.0     385427
1.0      15015
<NA>      1510
NaN          6
Name: count, dtype: int64

### diabete4
**Question:** What is the respondent's diabetes status?
- `1` = Yes
- `2` = Yes, but female told only during pregnancy
- `3` = No
- `4` = No, pre-diabetes or borderline diabetes
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1176]:
df_copy['diabete4'] = df_copy['diabete4'].replace([7, 9], pd.NA)
df_copy['diabete4'].value_counts(dropna=False)

diabete4
3.0     337064
1.0      52094
4.0       8612
2.0       3374
<NA>       808
NaN          6
Name: count, dtype: int64

### diabage3
**Question:** What is the respondent's diabetes age?
- `1-97` = age in years (`97` means 97 or older)
- `98` = Don't know / Not sure
- `99` = Refused
- cleaning: set `98` and `99` to `pd.NA`

In [1177]:
df_copy['diabage3'] = df_copy['diabage3'].replace([98, 99], pd.NA)
df_copy['diabage3'].value_counts(dropna=False)

diabage3
NaN     349864
50.0      4770
60.0      3680
<NA>      3429
55.0      3146
         ...
89.0        11
92.0         4
94.0         3
91.0         3
93.0         3
Name: count, Length: 96, dtype: int64

## Core Section 7: Oral Health

### lastden4
**Question:** What is the respondent's dental visit recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 5 years
- `4` = 5 or more years ago
- `7` = Don't know / Not sure
- `8` = Never
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1178]:
df_copy['lastden4'] = df_copy['lastden4'].replace([7, 9], pd.NA)
df_copy['lastden4'].value_counts(dropna=False)

lastden4
1.0     267045
2.0      49671
4.0      41865
3.0      36441
<NA>      4660
8.0       2269
NaN          7
Name: count, dtype: int64

### rmvteth4
**Question:** How many of your permanent teeth have been removed because of tooth decay or gum disease?
- `1` = 1 to 5 teeth removed
- `2` = 6 or more, but not all
- `3` = All
- `8` = None
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1179]:
df_copy['rmvteth4'] = df_copy['rmvteth4'].replace([7, 9, 77, 99], pd.NA)
df_copy['rmvteth4'].value_counts(dropna=False)

rmvteth4
8.0     209239
1.0     116271
2.0      41906
3.0      24745
<NA>      9790
NaN          7
Name: count, dtype: int64

## Core Section 8: Demographics

### x.ageg5yr
**Question:** What is the respondent's age group?
- `1` = Age 18 to 24
- `2` = Age 25 to 29
- `3` = Age 30 to 34
- `4` = Age 35 to 39
- `5` = Age 40 to 44
- `6` = Age 45 to 49
- `7` = Age 50 to 54
- `8` = Age 55 to 59
- `9` = Age 60 to 64
- `10` = Age 65 to 69
- `11` = Age 70 to 74
- `12` = Age 75 to 79
- `13` = Age 80 or older
- `14` = Don't know / Refused / Missing
- cleaning: set `14` to `pd.NA`

In [1180]:
df_copy['x.ageg5yr'] = df_copy['x.ageg5yr'].replace([14], pd.NA)
df_copy['x.ageg5yr'].value_counts(dropna=False)

x.ageg5yr
10      41570
9       41151
11      37972
8       36219
13      31456
7       31110
12      26607
6       26428
5       25729
1       25648
4       25492
3       23408
2       20911
<NA>     8257
Name: count, dtype: int64

### x.hispanc
**Question:** What is the respondent's status for hispanic?
- `1` = Hispanic
- `2` = Not Hispanic
- `9` = Refused
- cleaning: recode `2 -> 0`; set `9` to `pd.NA`

In [1181]:
df_copy['x.hispanc'] = df_copy['x.hispanc'].replace({2: 0})
df_copy['x.hispanc'] = df_copy['x.hispanc'].replace([9], pd.NA)
df_copy['x.hispanc'].value_counts(dropna=False)

x.hispanc
0       360696
1        36322
<NA>      4940
Name: count, dtype: int64

### x.mrace1
**Question:** What is the respondent's status for race multi select?
- `1` = White only
- `2` = Black only
- `3` = American Indian or Alaska Native only
- `4` = Asian only
- `5` = Native Hawaiian or other Pacific Islander only
- `6` = Other race only
- `7` = Multiracial
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1182]:
df_copy['x.mrace1'] = df_copy['x.mrace1'].replace([77, 99], pd.NA)
df_copy['x.mrace1'].value_counts(dropna=False)

x.mrace1
1.0     316258
2.0      32029
6.0      11911
<NA>     11419
4.0      10442
7.0       9465
3.0       8104
5.0       2321
NaN          9
Name: count, dtype: int64

### x.prace1
**Question:** What is the respondent's status for race best represents?
- `1` = White
- `2` = Black or African American
- `3` = American Indian or Alaska Native
- `4` = Asian
- `5` = Native Hawaiian or other Pacific Islander
- `6` = Other race
- `7` = Multiracial / best represented by another race code
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1183]:
df_copy['x.prace1'] = df_copy['x.prace1'].replace([77, 99], pd.NA)
df_copy['x.prace1'].value_counts(dropna=False)

x.prace1
1.0     320045
2.0      33271
6.0      12511
<NA>     11419
4.0      11248
3.0       8972
5.0       3239
7.0       1242
NaN          9
8.0          2
Name: count, dtype: int64

### marital
**Question:** What is the respondent's marital status?
- `1` = Married
- `2` = Divorced
- `3` = Widowed
- `4` = Separated
- `5` = Never married
- `6` = A member of an unmarried couple
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [1184]:
df_copy['marital'] = df_copy['marital'].replace([9], pd.NA)
df_copy['marital'].value_counts(dropna=False)

marital
1.0     207302
5.0      72051
2.0      51939
3.0      43646
6.0      15261
4.0       7975
<NA>      3772
NaN         12
Name: count, dtype: int64

### educa
**Question:** What is the respondent's status for education?
- `1` = Never attended school or only kindergarten
- `2` = Grades 1 through 8
- `3` = Grades 9 through 11
- `4` = Grade 12 or GED
- `5` = College 1 year to 3 years
- `6` = College 4 years or more
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [1185]:
df_copy['educa'] = df_copy['educa'].replace([9], pd.NA)
df_copy['educa'].value_counts(dropna=False)

educa
6.0     155340
5.0     111387
4.0     107096
3.0      17596
2.0       8092
<NA>      1875
1.0        560
NaN         12
Name: count, dtype: int64

### renthom1
**Question:** What is the respondent's status for own or rent?
- `1` = Own
- `2` = Rent
- `3` = Other arrangement
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1186]:
df_copy['renthom1'] = df_copy['renthom1'].replace([7, 9], pd.NA)
df_copy['renthom1'].value_counts(dropna=False)

renthom1
1.0     280664
2.0      97305
3.0      20507
<NA>      3467
NaN         15
Name: count, dtype: int64

### x.urbstat
**Question:** Does the respondent live in an urban county or a rural county?
- `1` = Urban county
- `2` = Rural county
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1187]:
df_copy['x.urbstat'] = df_copy['x.urbstat'].replace([7, 9, 77, 99], pd.NA)
df_copy['x.urbstat'].value_counts(dropna=False)

x.urbstat
1.0    335728
2.0     59103
NaN      7127
Name: count, dtype: int64

### numhhol3
**Question:** What is the respondent's status for multiple phones in household?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1188]:
df_copy['numhhol3'] = df_copy['numhhol3'].replace({2: 0})
df_copy['numhhol3'] = df_copy['numhhol3'].replace([7, 9], pd.NA)
df_copy['numhhol3'].value_counts(dropna=False)

numhhol3
NaN     277212
0.0      93529
1.0      30250
<NA>       967
Name: count, dtype: int64

### numphon3
**Question:** What is the respondent's status for residential phones?
- `1-5` = Enter number of residential phones
- `6` = 6 or more
- `7` = Don't know / Not sure
- `8` = None
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1189]:
df_copy['numphon3'] = df_copy['numphon3'].replace([7, 9], pd.NA)
df_copy['numphon3'].value_counts(dropna=False)

numphon3
NaN     371708
1.0      20334
2.0       6505
3.0       1784
<NA>       805
8.0        359
4.0        284
6.0         93
5.0         86
Name: count, dtype: int64

### cpdemo1b
**Question:** What is the respondent's status for personal cell phones?
- `1-5` = Enter number of personal cell phones
- `6` = 6 or more
- `7` = Don't know / Not sure
- `8` = None
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1190]:
df_copy['cpdemo1b'] = df_copy['cpdemo1b'].replace([7, 9], pd.NA)
df_copy['cpdemo1b'].value_counts(dropna=False)

cpdemo1b
1.0     338710
2.0      34055
8.0      16498
<NA>      4713
3.0       4671
4.0       2119
5.0        686
6.0        390
NaN        116
Name: count, dtype: int64

### veteran3
**Question:** What is the respondent's veteran status?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1191]:
df_copy['veteran3'] = df_copy['veteran3'].replace({2: 0})
df_copy['veteran3'] = df_copy['veteran3'].replace([7, 9], pd.NA)
df_copy['veteran3'].value_counts(dropna=False)

veteran3
0.0     351210
1.0      48221
NaN       1307
<NA>      1220
Name: count, dtype: int64

### employ1
**Question:** What is the respondent's employment status?
- `1` = Employed for wages
- `2` = Self-employed
- `3` = Out of work for 1 year or more
- `4` = Out of work for less than 1 year
- `5` = A homemaker
- `6` = A student
- `7` = Retired
- `8` = Unable to work
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [1192]:
df_copy['employ1'] = df_copy['employ1'].replace([9], pd.NA)
df_copy['employ1'].value_counts(dropna=False)

employ1
1.0     165872
7.0     117209
2.0      34921
8.0      25429
5.0      17080
4.0      16409
6.0      10730
3.0       7232
<NA>      4151
NaN       2925
Name: count, dtype: int64

### children
**Question:** What is the respondent's status for children in household?
- `0-87` = number of children younger than 18 in the household
- `88` = None
- `99` = Refused
- cleaning: recode `88 -> 0`; set `99` to `pd.NA`

In [1193]:
df_copy['children'] = df_copy['children'].replace({88: 0})
df_copy['children'] = df_copy['children'].replace([99], pd.NA)
df_copy['children'].value_counts(dropna=False)

children
0.0     289105
1.0      43345
2.0      36227
3.0      15832
4.0       5874
NaN       4767
<NA>      3651
5.0       1885
6.0        739
7.0        268
8.0        124
9.0         49
10.0        35
11.0        10
12.0        10
15.0         9
81.0         6
13.0         4
14.0         4
16.0         3
24.0         2
19.0         2
77.0         2
20.0         1
23.0         1
82.0         1
22.0         1
21.0         1
Name: count, dtype: int64

### income2
**Question:** What is the respondent's status for income?
- `1` = Less than $10,000
- `2` = $10,000 to less than $15,000
- `3` = $15,000 to less than $20,000
- `4` = $20,000 to less than $25,000
- `5` = $25,000 to less than $35,000
- `6` = $35,000 to less than $50,000
- `7` = $50,000 to less than $75,000
- `8` = $75,000 or more
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1194]:
df_copy['income2'] = df_copy['income2'].replace([77, 99], pd.NA)
df_copy['income2'].value_counts(dropna=False)

income2
8.0     118779
<NA>     72699
7.0      52486
6.0      43851
5.0      31410
4.0      27719
3.0      21048
2.0      13705
1.0      12903
NaN       7358
Name: count, dtype: int64

### pregnant
**Question:** What is the respondent's status for pregnant?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1195]:
df_copy['pregnant'] = df_copy['pregnant'].replace({2: 0})
df_copy['pregnant'] = df_copy['pregnant'].replace([7, 9], pd.NA)
df_copy['pregnant'].value_counts(dropna=False)

pregnant
NaN     326368
0.0      72968
1.0       2153
<NA>       469
Name: count, dtype: int64

### weight2
**Question:** What is the respondent's status for weight?
- recorded weight code from BRFSS
- `7777` = Don't know / Not sure
- `9999` = Refused
- cleaning: set `7777` and `9999` to `pd.NA`

In [1196]:
df_copy['weight2'] = df_copy['weight2'].replace([7777, 9999], pd.NA)
df_copy['weight2'].value_counts(dropna=False)

weight2
<NA>      25063
200.0     19745
180.0     18493
150.0     16636
160.0     16606
          ...
9131.0        1
9031.0        1
9168.0        1
9225.0        1
9240.0        1
Name: count, Length: 574, dtype: int64

### height3
**Question:** What is the respondent's status for height?
- recorded height code from BRFSS
- `7777` = Don't know / Not sure
- `9999` = Refused
- cleaning: set `7777` and `9999` to `pd.NA`

In [1197]:
df_copy['height3'] = df_copy['height3'].replace([7777, 9999], pd.NA)
df_copy['height3'].value_counts(dropna=False)

height3
506.0     33784
504.0     33015
507.0     30496
505.0     29791
510.0     28639
          ...
308.0         1
710.0         1
9209.0        1
9115.0        1
9139.0        1
Name: count, Length: 147, dtype: int64

## Core Section 9: Disability

### deaf
**Question:** What is the respondent's status for deaf or serious hearing difficulty?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1198]:
df_copy['deaf'] = df_copy['deaf'].replace({2: 0})
df_copy['deaf'] = df_copy['deaf'].replace([7, 9], pd.NA)
df_copy['deaf'].value_counts(dropna=False)

deaf
0.0     354411
1.0      33631
NaN      12415
<NA>      1501
Name: count, dtype: int64

### blind
**Question:** What is the respondent's status for blind or serious vision difficulty?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1199]:
df_copy['blind'] = df_copy['blind'].replace({2: 0})
df_copy['blind'] = df_copy['blind'].replace([7, 9], pd.NA)
df_copy['blind'].value_counts(dropna=False)

blind
0.0     367276
1.0      20009
NaN      13324
<NA>      1349
Name: count, dtype: int64

### decide
**Question:** What is the respondent's status for serious difficulty decisions?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1200]:
df_copy['decide'] = df_copy['decide'].replace({2: 0})
df_copy['decide'] = df_copy['decide'].replace([7, 9], pd.NA)
df_copy['decide'].value_counts(dropna=False)

decide
0.0     346929
1.0      38175
NaN      14351
<NA>      2503
Name: count, dtype: int64

### diffwalk
**Question:** What is the respondent's status for serious difficulty walking?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1201]:
df_copy['diffwalk'] = df_copy['diffwalk'].replace({2: 0})
df_copy['diffwalk'] = df_copy['diffwalk'].replace([7, 9], pd.NA)
df_copy['diffwalk'].value_counts(dropna=False)

diffwalk
0.0     327864
1.0      57335
NaN      15280
<NA>      1479
Name: count, dtype: int64

### diffdres
**Question:** What is the respondent's status for serious difficulty dressing?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1202]:
df_copy['diffdres'] = df_copy['diffdres'].replace({2: 0})
df_copy['diffdres'] = df_copy['diffdres'].replace([7, 9], pd.NA)
df_copy['diffdres'].value_counts(dropna=False)

diffdres
0.0     371628
NaN      15892
1.0      13736
<NA>       702
Name: count, dtype: int64

### diffalon
**Question:** What is the respondent's status for serious difficulty doing errands?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1203]:
df_copy['diffalon'] = df_copy['diffalon'].replace({2: 0})
df_copy['diffalon'] = df_copy['diffalon'].replace([7, 9], pd.NA)
df_copy['diffalon'].value_counts(dropna=False)

diffalon
0.0     357364
1.0      26485
NaN      16769
<NA>      1340
Name: count, dtype: int64

## Core Section 10: Tobacco Use

### smoke100
**Question:** What is the respondent's status for smoked 100 cigarettes?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1204]:
df_copy['smoke100'] = df_copy['smoke100'].replace({2: 0})
df_copy['smoke100'] = df_copy['smoke100'].replace([7, 9], pd.NA)
df_copy['smoke100'].value_counts(dropna=False)

smoke100
0.0     224535
1.0     156750
NaN      17860
<NA>      2813
Name: count, dtype: int64

### smokday2
**Question:** What is the respondent's smoke frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1205]:
df_copy['smokday2'] = df_copy['smokday2'].replace([7, 9], pd.NA)
df_copy['smokday2'].value_counts(dropna=False)

smokday2
NaN     245324
3.0     103835
1.0      38152
2.0      14336
<NA>       311
Name: count, dtype: int64

### stopsmk2
**Question:** What is the respondent's status for stopped smoking one day?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1206]:
df_copy['stopsmk2'] = df_copy['stopsmk2'].replace({2: 0})
df_copy['stopsmk2'] = df_copy['stopsmk2'].replace([7, 9], pd.NA)
df_copy['stopsmk2'].value_counts(dropna=False)

stopsmk2
NaN     349535
1.0      27560
0.0      24656
<NA>       207
Name: count, dtype: int64

### lastsmk2
**Question:** What is the respondent's last smoked recency?
- `1` = Within the past month
- `2` = Within the past 3 months
- `3` = Within the past 6 months
- `4` = Within the past year
- `5` = Within the past 5 years
- `6` = Within the past 10 years
- `7` = 10 years or more
- `8` = Never smoked regularly
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1207]:
df_copy['lastsmk2'] = df_copy['lastsmk2'].replace([77, 99], pd.NA)
df_copy['lastsmk2'].value_counts(dropna=False)

lastsmk2
NaN     298233
7.0      68085
5.0      14040
6.0      10406
4.0       3472
1.0       2314
3.0       2120
2.0       2086
<NA>       873
8.0        329
Name: count, dtype: int64

### usenow3
**Question:** What is the respondent's smokeless tobacco frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1208]:
df_copy['usenow3'] = df_copy['usenow3'].replace([7, 9], pd.NA)
df_copy['usenow3'].value_counts(dropna=False)

usenow3
3.0     369261
NaN      18493
1.0       7572
2.0       5400
<NA>      1232
Name: count, dtype: int64

## Core Section 11: Alcohol Consumption

### alcday5
**Question:** What is the respondent's alcohol frequency?
- first digit is the time unit:
- `1xx` = days per week
- `2xx` = days in past 30 days
- `777` = Don't know / Not sure
- `888` = No drinks in past 30 days
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1209]:
df_copy['alcday5'] = df_copy['alcday5'].replace([777, 999], pd.NA)
df_copy['alcday5'].value_counts(dropna=False)

alcday5
888.0    183618
201.0     27715
202.0     21224
NaN       20927
101.0     16147
230.0     15744
102.0     13039
203.0     11984
205.0     10038
204.0     10021
103.0      9100
210.0      8041
220.0      6911
107.0      6859
215.0      6665
<NA>       5848
104.0      4456
105.0      4267
206.0      3679
225.0      3004
208.0      2930
207.0      2622
212.0      1744
106.0      1473
228.0       932
214.0       600
229.0       331
216.0       258
227.0       253
209.0       238
218.0       232
221.0       187
224.0       181
222.0       170
226.0       167
217.0       102
213.0        97
223.0        85
211.0        58
219.0        11
Name: count, dtype: int64

### avedrnk3
**Question:** What is the respondent's average drinks?
- `1-76` = average number of drinks
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1210]:
df_copy['avedrnk3'] = df_copy['avedrnk3'].replace([77, 99], pd.NA)
df_copy['avedrnk3'].value_counts(dropna=False)

avedrnk3
NaN     211099
1.0      83821
2.0      55796
3.0      21862
4.0       9486
5.0       5062
6.0       4812
<NA>      3210
10.0      1393
8.0       1293
88.0      1063
12.0       901
7.0        848
15.0       297
9.0        203
20.0       197
30.0       132
24.0        75
18.0        56
14.0        50
16.0        49
25.0        37
11.0        33
13.0        32
60.0        23
40.0        21
17.0        14
76.0        13
50.0        11
32.0         8
45.0         7
35.0         6
21.0         5
22.0         5
36.0         4
70.0         3
27.0         3
23.0         3
26.0         3
75.0         3
48.0         2
56.0         2
34.0         2
64.0         1
47.0         1
51.0         1
63.0         1
33.0         1
54.0         1
57.0         1
66.0         1
53.0         1
28.0         1
37.0         1
38.0         1
41.0         1
Name: count, dtype: int64

### drnk3ge5
**Question:** What is the respondent's binge drinking frequency?
- `1-76` = number of times
- `77` = Don't know / Not sure
- `88` = None
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1211]:
df_copy['drnk3ge5'] = df_copy['drnk3ge5'].replace([77, 99], pd.NA)
df_copy['drnk3ge5'].value_counts(dropna=False)

drnk3ge5
NaN     211626
88.0    137758
1.0      16473
2.0      10083
3.0       4720
4.0       4461
5.0       3543
<NA>      3291
30.0      2047
10.0      1781
6.0       1348
8.0       1095
15.0       967
20.0       736
7.0        726
12.0       410
25.0       261
14.0        95
9.0         91
28.0        76
16.0        66
29.0        42
18.0        30
22.0        29
24.0        29
26.0        28
13.0        27
27.0        25
21.0        22
11.0        20
17.0        14
23.0        13
76.0         8
50.0         3
32.0         3
60.0         2
19.0         2
40.0         1
44.0         1
66.0         1
31.0         1
55.0         1
35.0         1
70.0         1
Name: count, dtype: int64

### maxdrnks
**Question:** What is the respondent's status for max drinks?
- `1-76` = maximum number of drinks
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1212]:
df_copy['maxdrnks'] = df_copy['maxdrnks'].replace([77, 99], pd.NA)
df_copy['maxdrnks'].value_counts(dropna=False)

maxdrnks
NaN     212112
1.0      51397
2.0      48666
3.0      28825
4.0      15472
         ...
31.0         1
49.0         1
74.0         1
56.0         1
61.0         1
Name: count, Length: 63, dtype: int64

## Core Section 12: Immunization

### flushot7
**Question:** What is the respondent's status for flu shot?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1213]:
df_copy['flushot7'] = df_copy['flushot7'].replace({2: 0})
df_copy['flushot7'] = df_copy['flushot7'].replace([7, 9], pd.NA)
df_copy['flushot7'].value_counts(dropna=False)

flushot7
1.0     197197
0.0     179019
NaN      23525
<NA>      2217
Name: count, dtype: int64

### shingle2
**Question:** What is the respondent's status for shingles vaccine?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1214]:
df_copy['shingle2'] = df_copy['shingle2'].replace({2: 0})
df_copy['shingle2'] = df_copy['shingle2'].replace([7, 9], pd.NA)
df_copy['shingle2'].value_counts(dropna=False)

shingle2
NaN     165874
0.0     146462
1.0      85049
<NA>      4573
Name: count, dtype: int64

### pneuvac4
**Question:** What is the respondent's status for pneumonia vaccine?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1215]:
df_copy['pneuvac4'] = df_copy['pneuvac4'].replace({2: 0})
df_copy['pneuvac4'] = df_copy['pneuvac4'].replace([7, 9], pd.NA)
df_copy['pneuvac4'].value_counts(dropna=False)

pneuvac4
0.0     205331
1.0     140195
<NA>     31995
NaN      24437
Name: count, dtype: int64

## Core Section 13: Falls

### fall12mn
**Question:** What is the respondent's status for falls past 12 months?
- `1-76` = number of falls
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1216]:
df_copy['fall12mn'] = df_copy['fall12mn'].replace([77, 99], pd.NA)
df_copy['fall12mn'].value_counts(dropna=False)

fall12mn
88.0    191978
NaN     137808
1.0      32548
2.0      17136
3.0       7286
<NA>      3472
4.0       3266
5.0       2335
6.0       1737
10.0      1065
12.0       723
8.0        475
20.0       386
7.0        383
15.0       302
76.0       219
30.0       172
50.0       118
25.0        94
24.0        87
9.0         73
40.0        42
13.0        28
11.0        22
52.0        22
60.0        22
14.0        15
18.0        15
35.0        15
16.0        14
48.0        12
36.0        12
22.0         7
45.0         6
23.0         6
70.0         5
17.0         5
27.0         4
75.0         4
72.0         4
26.0         3
19.0         3
21.0         3
31.0         3
55.0         3
28.0         3
69.0         2
34.0         2
42.0         2
65.0         2
66.0         2
47.0         1
43.0         1
67.0         1
44.0         1
58.0         1
32.0         1
46.0         1
Name: count, dtype: int64

### fallinj4
**Question:** What is the respondent's status for fall injuries past 12 months?
- `1-76` = number of fall injuries
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1217]:
df_copy['fallinj4'] = df_copy['fallinj4'].replace([77, 99], pd.NA)
df_copy['fallinj4'].value_counts(dropna=False)

fallinj4
NaN     333322
88.0     43133
1.0      17538
2.0       3934
3.0       1469
4.0        579
<NA>       538
5.0        437
6.0        252
10.0       169
7.0         98
8.0         91
12.0        85
15.0        66
20.0        62
76.0        44
30.0        28
9.0         16
25.0        16
50.0        14
11.0        10
14.0         9
40.0         8
13.0         7
24.0         7
18.0         4
31.0         3
27.0         2
38.0         2
70.0         2
32.0         1
22.0         1
19.0         1
58.0         1
75.0         1
36.0         1
52.0         1
17.0         1
21.0         1
68.0         1
48.0         1
60.0         1
16.0         1
Name: count, dtype: int64

## Core Section 14: Seat Belt Use and Drinking and Driving

### seatbelt
**Question:** What is the respondent's status for seatbelt use?
- `1` = Always
- `2` = Nearly always
- `3` = Sometimes
- `4` = Seldom
- `5` = Never
- `7` = Don't know / Not sure
- `8` = Never drive or ride in a car
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1218]:
df_copy['seatbelt'] = df_copy['seatbelt'].replace([7, 9], pd.NA)
df_copy['seatbelt'].value_counts(dropna=False)

seatbelt
1.0     327249
2.0      26763
NaN      25511
3.0      10195
5.0       6632
4.0       3942
8.0        976
<NA>       690
Name: count, dtype: int64

### drnkdri2
**Question:** What is the respondent's drinking and driving frequency?
- `1-76` = number of times
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1219]:
df_copy['drnkdri2'] = df_copy['drnkdri2'].replace([77, 99], pd.NA)
df_copy['drnkdri2'].value_counts(dropna=False)

drnkdri2
NaN     208430
88.0    187473
1.0       2327
<NA>      1525
2.0       1124
3.0        296
5.0        155
4.0        152
8.0        103
30.0       103
10.0        65
15.0        41
6.0         35
7.0         27
20.0        20
12.0        16
55.0        12
9.0         10
25.0         7
14.0         4
58.0         4
28.0         4
60.0         3
16.0         3
21.0         3
18.0         2
17.0         2
22.0         2
11.0         2
38.0         1
29.0         1
33.0         1
66.0         1
50.0         1
40.0         1
76.0         1
26.0         1
Name: count, dtype: int64

## Core Section 15: Breast and Cervical Cancer Screening

### hadmam
**Question:** What is the respondent's status for ever had mammogram?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1220]:
df_copy['hadmam'] = df_copy['hadmam'].replace({2: 0})
df_copy['hadmam'] = df_copy['hadmam'].replace([7, 9], pd.NA)
df_copy['hadmam'].value_counts(dropna=False)

hadmam
NaN     198438
1.0     156765
0.0      45883
<NA>       872
Name: count, dtype: int64

### howlong
**Question:** What is the respondent's mammogram recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1221]:
df_copy['howlong'] = df_copy['howlong'].replace([7, 9], pd.NA)
df_copy['howlong'].value_counts(dropna=False)

howlong
NaN     245446
1.0      86916
2.0      30723
5.0      15842
3.0      11873
4.0       8718
<NA>      2440
Name: count, dtype: int64

### hadpap2
**Question:** What is the respondent's status for ever had pap test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1222]:
df_copy['hadpap2'] = df_copy['hadpap2'].replace({2: 0})
df_copy['hadpap2'] = df_copy['hadpap2'].replace([7, 9], pd.NA)
df_copy['hadpap2'].value_counts(dropna=False)

hadpap2
NaN     198942
1.0     186665
0.0      14626
<NA>      1725
Name: count, dtype: int64

### lastpap2
**Question:** What is the respondent's pap test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1223]:
df_copy['lastpap2'] = df_copy['lastpap2'].replace([7, 9], pd.NA)
df_copy['lastpap2'].value_counts(dropna=False)

lastpap2
NaN     215438
1.0      58089
5.0      49910
2.0      34778
3.0      20538
4.0      17034
<NA>      6171
Name: count, dtype: int64

### hpvtest
**Question:** What is the respondent's status for ever had hpv test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1224]:
df_copy['hpvtest'] = df_copy['hpvtest'].replace({2: 0})
df_copy['hpvtest'] = df_copy['hpvtest'].replace([7, 9], pd.NA)
df_copy['hpvtest'].value_counts(dropna=False)

hpvtest
NaN     199388
0.0      85736
1.0      65524
<NA>     51310
Name: count, dtype: int64

### hplsttst
**Question:** What is the respondent's hpv test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1225]:
df_copy['hplsttst'] = df_copy['hplsttst'].replace([7, 9], pd.NA)
df_copy['hplsttst'].value_counts(dropna=False)

hplsttst
NaN     336493
1.0      22004
5.0      13333
2.0      12217
3.0       6937
4.0       5928
<NA>      5046
Name: count, dtype: int64

### hadhyst2
**Question:** What is the respondent's status for had hysterectomy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1226]:
df_copy['hadhyst2'] = df_copy['hadhyst2'].replace({2: 0})
df_copy['hadhyst2'] = df_copy['hadhyst2'].replace([7, 9], pd.NA)
df_copy['hadhyst2'].value_counts(dropna=False)

hadhyst2
NaN     201690
0.0     145397
1.0      53754
<NA>      1117
Name: count, dtype: int64

## Core Section 16: Prostate Cancer Screening

### pcpsaad3
**Question:** What is the respondent's discussed psa advantages?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1227]:
df_copy['pcpsaad3'] = df_copy['pcpsaad3'].replace({2: 0})
df_copy['pcpsaad3'] = df_copy['pcpsaad3'].replace([7, 9], pd.NA)
df_copy['pcpsaad3'].value_counts(dropna=False)

pcpsaad3
NaN     275393
0.0      64276
1.0      57376
<NA>      4913
Name: count, dtype: int64

### pcpsadi1
**Question:** What is the respondent's discussed psa disadvantages?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1228]:
df_copy['pcpsadi1'] = df_copy['pcpsadi1'].replace({2: 0})
df_copy['pcpsadi1'] = df_copy['pcpsadi1'].replace([7, 9], pd.NA)
df_copy['pcpsadi1'].value_counts(dropna=False)

pcpsadi1
NaN     275622
0.0      94663
1.0      26277
<NA>      5396
Name: count, dtype: int64

### pcpsare1
**Question:** What is the respondent's status for recommended psa test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1229]:
df_copy['pcpsare1'] = df_copy['pcpsare1'].replace({2: 0})
df_copy['pcpsare1'] = df_copy['pcpsare1'].replace([7, 9], pd.NA)
df_copy['pcpsare1'].value_counts(dropna=False)

pcpsare1
NaN     275882
0.0      67225
1.0      52932
<NA>      5919
Name: count, dtype: int64

### psatest1
**Question:** What is the respondent's status for ever had psa test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1230]:
df_copy['psatest1'] = df_copy['psatest1'].replace({2: 0})
df_copy['psatest1'] = df_copy['psatest1'].replace([7, 9], pd.NA)
df_copy['psatest1'].value_counts(dropna=False)

psatest1
NaN     276043
0.0      60438
1.0      58425
<NA>      7052
Name: count, dtype: int64

### psatime
**Question:** What is the respondent's psa test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1231]:
df_copy['psatime'] = df_copy['psatime'].replace([7, 9], pd.NA)
df_copy['psatime'].value_counts(dropna=False)

psatime
NaN     343595
1.0      33032
2.0       8859
5.0       6412
3.0       4289
4.0       3926
<NA>      1845
Name: count, dtype: int64

### pcpsars1
**Question:** What is the respondent's reason for psa test?
- `1` = Part of a routine exam
- `2` = Because of a prostate problem
- `3` = Because of a family history of prostate cancer
- `4` = Because you were told you had prostate cancer
- `5` = Some other reason
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1232]:
df_copy['pcpsars1'] = df_copy['pcpsars1'].replace([7, 9], pd.NA)
df_copy['pcpsars1'].value_counts(dropna=False)

pcpsars1
NaN     343707
1.0      40740
5.0       5380
2.0       4468
4.0       3435
3.0       3435
<NA>       793
Name: count, dtype: int64

## Core Section 17: Colorectal Cancer Screening

### colnscpy
**Question:** What is the respondent's status for ever had colonoscopy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1233]:
df_copy['colnscpy'] = df_copy['colnscpy'].replace({2: 0})
df_copy['colnscpy'] = df_copy['colnscpy'].replace([7, 9], pd.NA)
df_copy['colnscpy'].value_counts(dropna=False)

colnscpy
1.0     181481
NaN     143403
0.0      75229
<NA>      1845
Name: count, dtype: int64

### colntest
**Question:** What is the respondent's colonoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 5 years
- `4` = Within the past 10 years
- `5` = 10 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1234]:
df_copy['colntest'] = df_copy['colntest'].replace([7, 9], pd.NA)
df_copy['colntest'].value_counts(dropna=False)

colntest
NaN     220603
3.0      62505
4.0      35413
1.0      32765
2.0      29096
5.0      18775
<NA>      2801
Name: count, dtype: int64

### sigmscpy
**Question:** What is the respondent's status for ever had sigmoidoscopy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1235]:
df_copy['sigmscpy'] = df_copy['sigmscpy'].replace({2: 0})
df_copy['sigmscpy'] = df_copy['sigmscpy'].replace([7, 9], pd.NA)
df_copy['sigmscpy'].value_counts(dropna=False)

sigmscpy
0.0     212874
NaN     143927
1.0      31908
<NA>     13249
Name: count, dtype: int64

### sigmtest
**Question:** What is the respondent's sigmoidoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 5 years
- `4` = Within the past 10 years
- `5` = 10 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1236]:
df_copy['sigmtest'] = df_copy['sigmtest'].replace([7, 9], pd.NA)
df_copy['sigmtest'].value_counts(dropna=False)

sigmtest
NaN     370070
5.0      17250
3.0       4335
4.0       4164
1.0       2493
2.0       2096
<NA>      1550
Name: count, dtype: int64

### bldstol1
**Question:** What is the respondent's status for ever had blood stool test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1237]:
df_copy['bldstol1'] = df_copy['bldstol1'].replace({2: 0})
df_copy['bldstol1'] = df_copy['bldstol1'].replace([7, 9], pd.NA)
df_copy['bldstol1'].value_counts(dropna=False)

bldstol1
0.0     170963
NaN     144393
1.0      83140
<NA>      3462
Name: count, dtype: int64

### lstblds4
**Question:** What is the respondent's blood stool test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1238]:
df_copy['lstblds4'] = df_copy['lstblds4'].replace([7, 9], pd.NA)
df_copy['lstblds4'].value_counts(dropna=False)

lstblds4
NaN     318862
5.0      27435
1.0      23544
2.0      12127
4.0       8490
3.0       8114
<NA>      3386
Name: count, dtype: int64

### stooldna
**Question:** What is the respondent's status for ever had stool DNA test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1239]:
df_copy['stooldna'] = df_copy['stooldna'].replace({2: 0})
df_copy['stooldna'] = df_copy['stooldna'].replace([7, 9], pd.NA)
df_copy['stooldna'].value_counts(dropna=False)

stooldna
0.0     234118
NaN     144914
1.0      18406
<NA>      4520
Name: count, dtype: int64

### sdnatest
**Question:** What is the respondent's stool DNA test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1240]:
df_copy['sdnatest'] = df_copy['sdnatest'].replace([7, 9], pd.NA)
df_copy['sdnatest'].value_counts(dropna=False)

sdnatest
NaN     383572
1.0       6686
5.0       4187
2.0       3156
3.0       1845
4.0       1698
<NA>       814
Name: count, dtype: int64

### vircolon
**Question:** What is the respondent's status for ever had virtual colonoscopy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1241]:
df_copy['vircolon'] = df_copy['vircolon'].replace({2: 0})
df_copy['vircolon'] = df_copy['vircolon'].replace([7, 9], pd.NA)
df_copy['vircolon'].value_counts(dropna=False)

vircolon
0.0     237160
NaN     145453
1.0      11238
<NA>      8107
Name: count, dtype: int64

### vclntest
**Question:** What is the respondent's virtual colonoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1242]:
df_copy['vclntest'] = df_copy['vclntest'].replace([7, 9], pd.NA)
df_copy['vclntest'].value_counts(dropna=False)

vclntest
NaN     390737
5.0       4170
1.0       1891
4.0       1719
2.0       1485
3.0       1329
<NA>       627
Name: count, dtype: int64

## Core Section 18: H.I.V./AIDS

### hivtst7
**Question:** What is the respondent's status for ever had hiv test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1243]:
df_copy['hivtst7'] = df_copy['hivtst7'].replace({2: 0})
df_copy['hivtst7'] = df_copy['hivtst7'].replace([7, 9], pd.NA)
df_copy['hivtst7'].value_counts(dropna=False)

hivtst7
0.0     232101
1.0     116990
NaN      34037
<NA>     18830
Name: count, dtype: int64

### hivtstd3
**Question:** What is the respondent's hiv test time?
- BRFSS combined month/year code for most recent HIV test
- `777777` = Don't know / Not sure
- `999999` = Refused
- cleaning: set `777777` and `999999` to `pd.NA`

In [1244]:
df_copy['hivtstd3'] = df_copy['hivtstd3'].replace([777777, 999999], pd.NA)
df_copy['hivtstd3'].value_counts(dropna=False)

hivtstd3
NaN         285136
<NA>         32120
772019.0      3112
772018.0      2558
772010.0      2098
             ...
121987.0         5
31986.0          5
21987.0          4
41983.0          1
772021.0         1
Name: count, Length: 474, dtype: int64

### hivrisk5
**Question:** What is the respondent's status for any hiv risk situation?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1245]:
df_copy['hivrisk5'] = df_copy['hivrisk5'].replace({2: 0})
df_copy['hivrisk5'] = df_copy['hivrisk5'].replace([7, 9], pd.NA)
df_copy['hivrisk5'].value_counts(dropna=False)

hivrisk5
0.0     349518
NaN      35932
1.0      14527
<NA>      1981
Name: count, dtype: int64

## Module 1: Prediabetes

### pdiabtst
**Question:** What is the respondent's status for prediabetes test past 3 years?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1246]:
df_copy['pdiabtst'] = df_copy['pdiabtst'].replace({2: 0})
df_copy['pdiabtst'] = df_copy['pdiabtst'].replace([7, 9], pd.NA)
df_copy['pdiabtst'].value_counts(dropna=False)

pdiabtst
NaN     183016
1.0     117749
0.0      93039
<NA>      8154
Name: count, dtype: int64

### prediab1
**Question:** What is the respondent's status for told has prediabetes?
- `1` = Yes
- `2` = Yes, during pregnancy
- `3` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1247]:
df_copy['prediab1'] = df_copy['prediab1'].replace([7, 9], pd.NA)
df_copy['prediab1'].value_counts(dropna=False)

prediab1
3.0     187174
NaN     182965
1.0      28314
2.0       2462
<NA>      1043
Name: count, dtype: int64

## Module 2: Diabetes

### insulin1
**Question:** What is the respondent's status for taking insulin1?
- `1` = Yes
- `2` = No
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1248]:
df_copy['insulin1'] = df_copy['insulin1'].replace({2: 0})
df_copy['insulin1'] = df_copy['insulin1'].replace([7, 9], pd.NA)
df_copy['insulin1'].value_counts(dropna=False)

insulin1
NaN     388849
0.0       8778
1.0       4294
<NA>        37
Name: count, dtype: int64

### bldsugar
**Question:** What is the respondent's status for blood sugar check freq?
- first digit is the time unit:
- `1xx` = times per day
- `2xx` = times per week
- `3xx` = times per month
- `4xx` = times per year
- `777` = Don't know / Not sure
- `888` = Never
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1249]:
df_copy['bldsugar'] = df_copy['bldsugar'].replace([777, 999], pd.NA)
df_copy['bldsugar'].value_counts(dropna=False)

bldsugar
NaN      388850
101.0      3972
102.0      1857
888.0      1495
103.0       976
          ...
430.0         1
117.0         1
209.0         1
175.0         1
314.0         1
Name: count, Length: 72, dtype: int64

### feetchk3
**Question:** What is the respondent's status for foot self check freq?
- first digit is the time unit:
- `1xx` = times per day
- `2xx` = times per week
- `3xx` = times per month
- `4xx` = times per year
- `555` = No feet
- `777` = Don't know / Not sure
- `888` = Never
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1250]:
df_copy['feetchk3'] = df_copy['feetchk3'].replace([777, 999], pd.NA)
df_copy['feetchk3'].value_counts(dropna=False)

feetchk3
NaN      388850
101.0      6816
888.0      1799
201.0       945
102.0       576
          ...
109.0         1
123.0         1
220.0         1
356.0         1
345.0         1
Name: count, Length: 67, dtype: int64

### doctdiab
**Question:** What is the respondent's status for doctor visit diabetes freq?
- `1-76` = number of visits in past 12 months (`76` means 76 or more)
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1251]:
df_copy['doctdiab'] = df_copy['doctdiab'].replace([77, 99], pd.NA)
df_copy['doctdiab'].value_counts(dropna=False)

doctdiab
NaN     388850
4.0       3159
2.0       2977
1.0       2082
3.0       1634
88.0      1454
<NA>       447
12.0       393
6.0        347
5.0        237
8.0         70
10.0        65
76.0        39
7.0         36
24.0        30
9.0         27
20.0        21
30.0        11
14.0         8
15.0         8
48.0         7
11.0         7
40.0         6
36.0         5
13.0         4
60.0         4
25.0         4
52.0         3
54.0         3
26.0         3
16.0         3
22.0         3
43.0         2
45.0         2
50.0         2
28.0         1
58.0         1
18.0         1
21.0         1
23.0         1
Name: count, dtype: int64

### chkhemo3
**Question:** What is the respondent's status for a1c check freq?
- `1-76` = number of A1C checks in past 12 months (`76` means 76 or more)
- `88` = None
- `98` = Never heard of A1C test
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1252]:
df_copy['chkhemo3'] = df_copy['chkhemo3'].replace([77, 99], pd.NA)
df_copy['chkhemo3'].value_counts(dropna=False)

chkhemo3
NaN     388850
2.0       3616
4.0       3157
1.0       2487
3.0       1551
88.0       859
<NA>       654
6.0        186
12.0       162
5.0        147
98.0       117
10.0        33
76.0        25
7.0         16
8.0         16
24.0        15
9.0         15
20.0         8
15.0         6
50.0         5
14.0         5
22.0         4
30.0         3
48.0         3
40.0         3
11.0         2
60.0         2
52.0         2
34.0         1
16.0         1
32.0         1
36.0         1
17.0         1
72.0         1
44.0         1
21.0         1
54.0         1
Name: count, dtype: int64

### feetchk
**Question:** What is the respondent's status for professional foot check freq?
- `1-76` = number of professional foot checks in past 12 months (`76` means 76 or more)
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1253]:
df_copy['feetchk'] = df_copy['feetchk'].replace([77, 99], pd.NA)
df_copy['feetchk'].value_counts(dropna=False)

feetchk
NaN     388925
88.0      3310
1.0       3027
2.0       2514
4.0       1847
3.0        975
<NA>       418
6.0        262
12.0       249
5.0        134
8.0         56
76.0        42
10.0        31
7.0         30
24.0        22
9.0         19
52.0        15
15.0        10
20.0         9
48.0         7
25.0         6
40.0         6
11.0         5
26.0         4
70.0         4
36.0         4
30.0         4
14.0         3
60.0         3
16.0         2
21.0         2
18.0         1
74.0         1
42.0         1
58.0         1
38.0         1
73.0         1
28.0         1
50.0         1
64.0         1
22.0         1
54.0         1
35.0         1
63.0         1
Name: count, dtype: int64

### eyeexam1
**Question:** What is the respondent's eye exam recency?
- `1` = Within the past month
- `2` = Within the past year
- `3` = Within the past 2 years
- `4` = 2 or more years ago
- `7` = Don't know / Not sure
- `8` = Never
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1254]:
df_copy['eyeexam1'] = df_copy['eyeexam1'].replace([7, 9], pd.NA)
df_copy['eyeexam1'].value_counts(dropna=False)

eyeexam1
NaN     388850
2.0       6149
1.0       2893
3.0       1819
4.0       1519
8.0        476
<NA>       252
Name: count, dtype: int64

### diabeye
**Question:** What is the respondent's status for diabetes affected eyes?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1255]:
df_copy['diabeye'] = df_copy['diabeye'].replace({2: 0})
df_copy['diabeye'] = df_copy['diabeye'].replace([7, 9], pd.NA)
df_copy['diabeye'].value_counts(dropna=False)

diabeye
NaN     388850
0.0      10532
1.0       2374
<NA>       202
Name: count, dtype: int64

### diabedu
**Question:** What is the respondent's status for diabetes education?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1256]:
df_copy['diabedu'] = df_copy['diabedu'].replace({2: 0})
df_copy['diabedu'] = df_copy['diabedu'].replace([7, 9], pd.NA)
df_copy['diabedu'].value_counts(dropna=False)

diabedu
NaN     388850
1.0       6690
0.0       6357
<NA>        61
Name: count, dtype: int64

## Module 3: ME/CFS

### toldcfs
**Question:** What is the respondent's status for told has ME/CFS?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1257]:
df_copy['toldcfs'] = df_copy['toldcfs'].replace({2: 0})
df_copy['toldcfs'] = df_copy['toldcfs'].replace([7, 9], pd.NA)
df_copy['toldcfs'].value_counts(dropna=False)

toldcfs
NaN    401958
Name: count, dtype: int64

### havecfs
**Question:** What is the respondent's status for still has ME/CFS?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1258]:
df_copy['havecfs'] = df_copy['havecfs'].replace({2: 0})
df_copy['havecfs'] = df_copy['havecfs'].replace([7, 9], pd.NA)
df_copy['havecfs'].value_counts(dropna=False)

havecfs
NaN    401958
Name: count, dtype: int64

### workcfs
**Question:** What is the respondent's work hours per week during the past 6 months with ME/CFS?
- `1` = 0 or no hours, cannot work at all because of CFS or ME
- `2` = 1-10 hours a week
- `3` = 11-20 hours a week
- `4` = 21-30 hours a week
- `5` = 31-40 hours a week
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1259]:
df_copy['workcfs'] = df_copy['workcfs'].replace([7, 9], pd.NA)
df_copy['workcfs'].value_counts(dropna=False)

workcfs
NaN    401958
Name: count, dtype: int64

## Module 4: Hepatitis Treatment

### toldhepc
**Question:** What is the respondent's status for told has hepatitis C?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1260]:
df_copy['toldhepc'] = df_copy['toldhepc'].replace({2: 0})
df_copy['toldhepc'] = df_copy['toldhepc'].replace([7, 9], pd.NA)
df_copy['toldhepc'].value_counts(dropna=False)

toldhepc
NaN     383151
0.0      18454
1.0        272
<NA>        81
Name: count, dtype: int64

### trethepc
**Question:** What is the respondent's status for treated hepatitis C in 2015 or after?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1261]:
df_copy['trethepc'] = df_copy['trethepc'].replace({2: 0})
df_copy['trethepc'] = df_copy['trethepc'].replace([7, 9], pd.NA)
df_copy['trethepc'].value_counts(dropna=False)

trethepc
NaN     401687
0.0        138
1.0        130
<NA>         3
Name: count, dtype: int64

### prirhepc
**Question:** What is the respondent's status for treated hepatitis C before 2015?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1262]:
df_copy['prirhepc'] = df_copy['prirhepc'].replace({2: 0})
df_copy['prirhepc'] = df_copy['prirhepc'].replace([7, 9], pd.NA)
df_copy['prirhepc'].value_counts(dropna=False)

prirhepc
NaN     401687
0.0        153
1.0        113
<NA>         5
Name: count, dtype: int64

### havehepc
**Question:** What is the respondent's status for still has hepatitis C?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1263]:
df_copy['havehepc'] = df_copy['havehepc'].replace({2: 0})
df_copy['havehepc'] = df_copy['havehepc'].replace([7, 9], pd.NA)
df_copy['havehepc'].value_counts(dropna=False)

havehepc
NaN     401687
0.0        197
1.0         53
<NA>        21
Name: count, dtype: int64

### havehepb
**Question:** What is the respondent's status for told has hepatitis B?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1264]:
df_copy['havehepb'] = df_copy['havehepb'].replace({2: 0})
df_copy['havehepb'] = df_copy['havehepb'].replace([7, 9], pd.NA)
df_copy['havehepb'].value_counts(dropna=False)

havehepb
NaN     383186
0.0      18509
1.0        151
<NA>       112
Name: count, dtype: int64

### medshepb
**Question:** What is the respondent's status for taking medicine to treat hepatitis B?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1265]:
df_copy['medshepb'] = df_copy['medshepb'].replace({2: 0})
df_copy['medshepb'] = df_copy['medshepb'].replace([7, 9], pd.NA)
df_copy['medshepb'].value_counts(dropna=False)

medshepb
NaN     401807
0.0        137
1.0         12
<NA>         2
Name: count, dtype: int64

## Module 5: Health Care Access

### hlthcvr1
**Question:** What is the respondent's primary health coverage source?
- `1-8` = primary source of health care coverage
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1266]:
df_copy['hlthcvr1'] = df_copy['hlthcvr1'].replace([77, 99], pd.NA)
df_copy['hlthcvr1'].value_counts(dropna=False)

hlthcvr1
NaN     362563
1.0      16305
3.0      13128
4.0       3399
2.0       2697
5.0       1618
7.0       1143
<NA>       965
8.0        117
6.0         23
Name: count, dtype: int64

### cimemlos
**Question:** What is the respondent's status for worsening confusion or memory loss?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1267]:
df_copy['cimemlos'] = df_copy['cimemlos'].replace({2: 0})
df_copy['cimemlos'] = df_copy['cimemlos'].replace([7, 9], pd.NA)
df_copy['cimemlos'].value_counts(dropna=False)

/Users/rj/Repos/615-ML-Project/ML-Project/lib/python3.14/site-packages/IPython/core/displayhook.py:292: UserWarning: Output cache limit (currently 1000 entries) hit.
Flushing oldest 200 entries.
  warn('Output cache limit (currently {sz} entries) hit.\n'

cimemlos
NaN     334120
0.0      61537
1.0       5729
<NA>       572
Name: count, dtype: int64

### cdhouse
**Question:** What is the respondent's status for confusion interfered household activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1268]:
df_copy['cdhouse'] = df_copy['cdhouse'].replace([7, 9], pd.NA)
df_copy['cdhouse'].value_counts(dropna=False)

cdhouse
NaN     395834
5.0       3128
3.0       1264
4.0        935
1.0        363
2.0        307
<NA>       127
Name: count, dtype: int64

### cdassist
**Question:** What is the respondent's status for need assistance day to day activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1269]:
df_copy['cdassist'] = df_copy['cdassist'].replace([7, 9], pd.NA)
df_copy['cdassist'].value_counts(dropna=False)

cdassist
NaN     395847
5.0       3390
3.0       1099
4.0        978
1.0        305
2.0        263
<NA>        76
Name: count, dtype: int64

### cdhelp
**Question:** What is the respondent's status for gets needed help for activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- cleaning: set `7` and `9` to `pd.NA`

In [1270]:
df_copy['cdhelp'] = df_copy['cdhelp'].replace([7, 9], pd.NA)
df_copy['cdhelp'].value_counts(dropna=False)

cdhelp
NaN     400293
1.0        673
3.0        375
2.0        356
4.0        142
5.0        110
<NA>         9
Name: count, dtype: int64

### cdsocial
**Question:** What is the respondent's status for confusion interfered social activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1271]:
df_copy['cdsocial'] = df_copy['cdsocial'].replace([7, 9], pd.NA)
df_copy['cdsocial'].value_counts(dropna=False)

cdsocial
NaN     395855
5.0       3313
3.0        988
4.0        950
1.0        452
2.0        284
<NA>       116
Name: count, dtype: int64

### cddiscus
**Question:** What is the respondent's status for discussed confusion with health professional?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1272]:
df_copy['cddiscus'] = df_copy['cddiscus'].replace({2: 0})
df_copy['cddiscus'] = df_copy['cddiscus'].replace([7, 9], pd.NA)
df_copy['cddiscus'].value_counts(dropna=False)

cddiscus
NaN     395865
0.0       3302
1.0       2722
<NA>        69
Name: count, dtype: int64

## Module 7: Caregiver

### caregiv1
**Question:** What is the respondent's provided care past 30 days?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `8` = Caregiving recipient died in past 30 days
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1273]:
df_copy['caregiv1'] = df_copy['caregiv1'].replace([7, 9], pd.NA)
df_copy['caregiv1'].value_counts(dropna=False)

caregiv1
NaN     371480
2.0      24372
1.0       5863
<NA>       178
8.0         65
Name: count, dtype: int64

### crgvrel4
**Question:** What is the respondent's status for care recipient relationship?
- `1-16` = relationship to person cared for
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1274]:
df_copy['crgvrel4'] = df_copy['crgvrel4'].replace([77, 99], pd.NA)
df_copy['crgvrel4'].value_counts(dropna=False)

crgvrel4
NaN     396104
1.0       1234
15.0       920
6.0        652
7.0        540
5.0        478
14.0       402
2.0        391
10.0       241
11.0       236
3.0        211
9.0        192
4.0         90
<NA>        76
12.0        75
8.0         72
13.0        44
Name: count, dtype: int64

### crgvlng1
**Question:** What is the respondent's caregiving duration?
- `1` = Less than 30 days
- `2` = 1 month to less than 6 months
- `3` = 6 months to less than 2 years
- `4` = 2 years to less than 5 years
- `5` = More than 5 years
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1275]:
df_copy['crgvlng1'] = df_copy['crgvlng1'].replace([7, 9], pd.NA)
df_copy['crgvlng1'].value_counts(dropna=False)

crgvlng1
NaN     396112
5.0       1863
4.0       1161
3.0       1115
1.0        904
2.0        697
<NA>       106
Name: count, dtype: int64

### crgvhrs1
**Question:** What is the respondent's caregiving hours per week?
- `1` = Up to 8 hours per week
- `2` = 9 to 19 hours per week
- `3` = 20 to 39 hours per week
- `4` = 40 hours or more
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1276]:
df_copy['crgvhrs1'] = df_copy['crgvhrs1'].replace([7, 9], pd.NA)
df_copy['crgvhrs1'].value_counts(dropna=False)

crgvhrs1
NaN     396130
1.0       2658
4.0       1331
2.0        776
3.0        626
<NA>       437
Name: count, dtype: int64

### crgvprb3
**Question:** What is the respondent's status for care recipient main problem?
- `1-15` = main health problem, long-term illness, or disability
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1277]:
df_copy['crgvprb3'] = df_copy['crgvprb3'].replace([77, 99], pd.NA)
df_copy['crgvprb3'].value_counts(dropna=False)

crgvprb3
NaN     396148
15.0      1446
14.0       771
5.0        607
8.0        502
3.0        476
13.0       310
<NA>       297
7.0        280
4.0        256
10.0       246
1.0        217
6.0        199
11.0       148
2.0         25
12.0        18
9.0         12
Name: count, dtype: int64

### crgvper1
**Question:** What is the respondent's status for provided personal care?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1278]:
df_copy['crgvper1'] = df_copy['crgvper1'].replace({2: 0})
df_copy['crgvper1'] = df_copy['crgvper1'].replace([7, 9], pd.NA)
df_copy['crgvper1'].value_counts(dropna=False)

crgvper1
NaN     396163
1.0       2926
0.0       2820
<NA>        49
Name: count, dtype: int64

### crgvhou1
**Question:** What is the respondent's status for provided household tasks?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1279]:
df_copy['crgvhou1'] = df_copy['crgvhou1'].replace({2: 0})
df_copy['crgvhou1'] = df_copy['crgvhou1'].replace([7, 9], pd.NA)
df_copy['crgvhou1'].value_counts(dropna=False)

crgvhou1
NaN     396172
1.0       4497
0.0       1124
<NA>       165
Name: count, dtype: int64

### crgvexpt
**Question:** What is the respondent's status for expect to provide care next 2 years?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1280]:
df_copy['crgvexpt'] = df_copy['crgvexpt'].replace({2: 0})
df_copy['crgvexpt'] = df_copy['crgvexpt'].replace([7, 9], pd.NA)
df_copy['crgvexpt'].value_counts(dropna=False)

crgvexpt
NaN     372320
0.0      20616
1.0       6828
<NA>      2194
Name: count, dtype: int64

## Module 8: E-Cigarettes

### ecigaret
**Question:** What is the respondent's status for ever used e cigarette?
- `1` = Yes
- `2` = No
- `7` / `77` = Don't know / Not sure
- `9` / `99` = Refused
- cleaning: recode `2 -> 0`; set `7`, `9`, `77`, and `99` to `pd.NA`

In [1281]:
df_copy['ecigaret'] = df_copy['ecigaret'].replace({2: 0})
df_copy['ecigaret'] = df_copy['ecigaret'].replace([7, 9, 77, 99], pd.NA)
df_copy['ecigaret'].value_counts(dropna=False)

ecigaret
0.0     213059
NaN     137397
1.0      50820
<NA>       682
Name: count, dtype: int64

### ecignow
**Question:** What is the respondent's e cigarette frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1282]:
df_copy['ecignow'] = df_copy['ecignow'].replace([7, 9], pd.NA)
df_copy['ecignow'].value_counts(dropna=False)

ecignow
NaN     351208
3.0      40787
2.0       5539
1.0       4340
<NA>        84
Name: count, dtype: int64

## Module 9: Marijuana Use

### marijan1
**Question:** What is the respondent's marijuana use days past 30?
- `1-30` = number of days used marijuana in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [1283]:
df_copy['marijan1'] = df_copy['marijan1'].replace({88: 0})
df_copy['marijan1'] = df_copy['marijan1'].replace([77, 99], pd.NA)
df_copy['marijan1'].value_counts(dropna=False)

marijan1
NaN     271339
0.0     117764
30.0      4363
<NA>      1396
1.0       1242
2.0       1142
10.0       634
20.0       622
5.0        609
3.0        609
15.0       607
4.0        437
25.0       230
7.0        205
6.0        169
8.0         98
12.0        91
28.0        81
14.0        76
29.0        52
27.0        26
9.0         25
18.0        20
16.0        18
22.0        16
21.0        15
24.0        14
26.0        13
17.0        13
23.0        12
13.0         9
11.0         7
19.0         4
Name: count, dtype: int64

### usemrjn2
**Question:** What is the respondent's most frequent marijuana use method?
- `1-6` = most frequent way marijuana was used
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1284]:
df_copy['usemrjn2'] = df_copy['usemrjn2'].replace([7, 9], pd.NA)
df_copy['usemrjn2'].value_counts(dropna=False)

usemrjn2
NaN     390513
1.0       8142
2.0       1536
4.0        810
6.0        450
5.0        270
<NA>       120
3.0        117
Name: count, dtype: int64

### rsnmrjn1
**Question:** What is the respondent's reason for marijuana use?
- `1` = For medical reasons
- `2` = For non-medical reasons
- `3` = For both medical and non-medical reasons
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1285]:
df_copy['rsnmrjn1'] = df_copy['rsnmrjn1'].replace([7, 9], pd.NA)
df_copy['rsnmrjn1'].value_counts(dropna=False)

rsnmrjn1
NaN     390525
3.0       3856
2.0       3742
1.0       3713
<NA>       122
Name: count, dtype: int64

## Module 10: Lung Cancer Screening

### lcsfirst
**Question:** What is the respondent's age started smoking regularly?
- age in years when respondent first started smoking cigarettes regularly
- `777` = Don't know / Not sure
- `888` = Never smoked cigarettes regularly
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1286]:
df_copy['lcsfirst'] = df_copy['lcsfirst'].replace([777, 999], pd.NA)
df_copy['lcsfirst'].value_counts(dropna=False)

lcsfirst
NaN     387914
18.0      2311
16.0      1875
15.0      1454
17.0      1264
         ...
58.0         1
77.0         1
41.0         1
75.0         1
74.0         1
Name: count, Length: 65, dtype: int64

### lcslast
**Question:** What is the respondent's age last smoked regularly?
- age in years when respondent last smoked cigarettes regularly
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1287]:
df_copy['lcslast'] = df_copy['lcslast'].replace([777, 999], pd.NA)
df_copy['lcslast'].value_counts(dropna=False)

lcslast
NaN      388332
<NA>        798
30.0        683
40.0        581
35.0        534
          ...
100.0         1
8.0           1
5.0           1
94.0          1
2.0           1
Name: count, Length: 92, dtype: int64

### lcsnumcg
**Question:** What is the respondent's status for cigarettes per day when smoking?
- number of cigarettes smoked each day on average when respondent smoked regularly
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [1288]:
df_copy['lcsnumcg'] = df_copy['lcsnumcg'].replace([777, 999], pd.NA)
df_copy['lcsnumcg'].value_counts(dropna=False)

lcsnumcg
NaN      388351
20.0       3790
10.0       2722
5.0         982
15.0        845
40.0        666
<NA>        592
30.0        542
3.0         472
4.0         446
2.0         406
6.0         364
1.0         335
8.0         278
7.0         208
12.0        196
25.0        169
60.0        156
50.0         74
35.0         58
18.0         51
9.0          33
80.0         29
13.0         24
14.0         19
11.0         18
17.0         17
75.0         14
16.0         13
45.0         12
24.0         10
100.0         8
19.0          8
77.0          7
21.0          5
70.0          5
23.0          3
99.0          3
36.0          3
88.0          2
28.0          2
26.0          2
55.0          2
56.0          2
125.0         2
110.0         2
90.0          1
120.0         1
33.0          1
38.0          1
41.0          1
220.0         1
109.0         1
190.0         1
29.0          1
67.0          1
Name: count, dtype: int64

### lcsctscn
**Question:** What is the respondent's status for had lung cancer ct scan?
- `1` = Yes, to check for lung cancer
- `2` = No, did not have a CT scan
- `3` = Had a CT scan, but for some other reason
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1289]:
df_copy['lcsctscn'] = df_copy['lcsctscn'].replace([7, 9], pd.NA)
df_copy['lcsctscn'].value_counts(dropna=False)

lcsctscn
NaN     370711
2.0      24298
3.0       4663
1.0       1722
<NA>       564
Name: count, dtype: int64

## Module 11: Cancer Survivorship: Type of Cancer

### cncrdiff
**Question:** What is the respondent's number of cancer types?
- `1` = Only one
- `2` = Two
- `3` = Three or more
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1290]:
df_copy['cncrdiff'] = df_copy['cncrdiff'].replace([7, 9], pd.NA)
df_copy['cncrdiff'].value_counts(dropna=False)

cncrdiff
NaN     378792
1.0      17563
2.0       4177
3.0        973
<NA>       453
Name: count, dtype: int64

### cncrage
**Question:** What is the respondent's age first diagnosed cancer?
- `1-97` = age in years (`97` means 97 and older)
- `98` = Don't know / Not sure
- `99` = Refused
- cleaning: set `98` and `99` to `pd.NA`

In [1291]:
df_copy['cncrage'] = df_copy['cncrage'].replace([98, 99], pd.NA)
df_copy['cncrage'].value_counts(dropna=False)

cncrage
NaN     379265
60.0      1263
<NA>      1262
50.0      1254
65.0      1076
         ...
94.0         4
93.0         4
95.0         2
97.0         1
92.0         1
Name: count, Length: 99, dtype: int64

### cncrtyp1
**Question:** What is the respondent's most recent cancer type?
- `1-30` = type of cancer
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1292]:
df_copy['cncrtyp1'] = df_copy['cncrtyp1'].replace([77, 99], pd.NA)
df_copy['cncrtyp1'].value_counts(dropna=False)

cncrtyp1
NaN     379282
22.0      7036
21.0      3275
1.0       3063
19.0      1928
<NA>      1014
30.0      1008
10.0       772
2.0        690
8.0        471
24.0       440
25.0       434
3.0        432
4.0        292
17.0       278
26.0       268
18.0       264
16.0       155
27.0        92
7.0         88
20.0        88
12.0        82
15.0        81
14.0        79
5.0         79
28.0        62
13.0        58
6.0         58
11.0        56
9.0         22
29.0         8
23.0         3
Name: count, dtype: int64

## Module 12: Cancer Survivorship: Course of Treatment

### csrvtrt3
**Question:** What is the respondent's status for currently receiving cancer treatment?
- `1` = Yes
- `2` = No, I've completed treatment
- `3` = No, I've refused treatment
- `4` = No, I haven't started treatment
- `5` = Treatment not needed
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1293]:
df_copy['csrvtrt3'] = df_copy['csrvtrt3'].replace([7, 9], pd.NA)
df_copy['csrvtrt3'].value_counts(dropna=False)

csrvtrt3
NaN     377950
2.0      13589
5.0       5962
1.0       2824
4.0        837
<NA>       620
3.0        176
Name: count, dtype: int64

### csrvdoc1
**Question:** What is the respondent's cancer care doctor type?
- `1-10` = type of doctor providing most of health care
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1294]:
df_copy['csrvdoc1'] = df_copy['csrvdoc1'].replace([77, 99], pd.NA)
df_copy['csrvdoc1'].value_counts(dropna=False)

csrvdoc1
NaN     388388
2.0       5736
5.0       3726
10.0      1609
7.0        555
1.0        456
<NA>       440
4.0        311
9.0        277
3.0        254
8.0        123
6.0         83
Name: count, dtype: int64

### csrvsum
**Question:** What is the respondent's status for received cancer treatment summary?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1295]:
df_copy['csrvsum'] = df_copy['csrvsum'].replace({2: 0})
df_copy['csrvsum'] = df_copy['csrvsum'].replace([7, 9], pd.NA)
df_copy['csrvsum'].value_counts(dropna=False)

csrvsum
NaN     388401
0.0       6679
1.0       5858
<NA>      1020
Name: count, dtype: int64

### csrvrtrn
**Question:** What is the respondent's status for received follow up instructions?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1296]:
df_copy['csrvrtrn'] = df_copy['csrvrtrn'].replace({2: 0})
df_copy['csrvrtrn'] = df_copy['csrvrtrn'].replace([7, 9], pd.NA)
df_copy['csrvrtrn'].value_counts(dropna=False)

csrvrtrn
NaN     388422
1.0       9985
0.0       3228
<NA>       323
Name: count, dtype: int64

### csrvinst
**Question:** What is the respondent's status for follow up instructions written?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1297]:
df_copy['csrvinst'] = df_copy['csrvinst'].replace({2: 0})
df_copy['csrvinst'] = df_copy['csrvinst'].replace([7, 9], pd.NA)
df_copy['csrvinst'].value_counts(dropna=False)

csrvinst
NaN     391979
1.0       7453
0.0       1804
<NA>       722
Name: count, dtype: int64

### csrvinsr
**Question:** What is the respondent's status for insurance paid for cancer treatment?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1298]:
df_copy['csrvinsr'] = df_copy['csrvinsr'].replace({2: 0})
df_copy['csrvinsr'] = df_copy['csrvinsr'].replace([7, 9], pd.NA)
df_copy['csrvinsr'].value_counts(dropna=False)

csrvinsr
NaN     388442
1.0      12758
0.0        565
<NA>       193
Name: count, dtype: int64

### csrvdein
**Question:** What is the respondent's status for denied insurance because of cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1299]:
df_copy['csrvdein'] = df_copy['csrvdein'].replace({2: 0})
df_copy['csrvdein'] = df_copy['csrvdein'].replace([7, 9], pd.NA)
df_copy['csrvdein'].value_counts(dropna=False)

csrvdein
NaN     388451
0.0      12659
1.0        754
<NA>        94
Name: count, dtype: int64

### csrvclin
**Question:** What is the respondent's status for participated in cancer clinical trial?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1300]:
df_copy['csrvclin'] = df_copy['csrvclin'].replace({2: 0})
df_copy['csrvclin'] = df_copy['csrvclin'].replace([7, 9], pd.NA)
df_copy['csrvclin'].value_counts(dropna=False)

csrvclin
NaN     388459
0.0      12603
1.0        684
<NA>       212
Name: count, dtype: int64

## Module 13: Cancer Survivorship: Pain Management

### csrvpain
**Question:** What is the respondent's status for current physical pain from cancer treatment?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1301]:
df_copy['csrvpain'] = df_copy['csrvpain'].replace({2: 0})
df_copy['csrvpain'] = df_copy['csrvpain'].replace([7, 9], pd.NA)
df_copy['csrvpain'].value_counts(dropna=False)

csrvpain
NaN     379939
0.0      19747
1.0       1859
<NA>       413
Name: count, dtype: int64

### csrvctl2
**Question:** What is the respondent's cancer pain control status?
- `1` = With medication (or treatment)
- `2` = Without medication (or treatment)
- `3` = Not under control, with medication (or treatment)
- `4` = Not under control, without medication (or treatment)
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1302]:
df_copy['csrvctl2'] = df_copy['csrvctl2'].replace([7, 9], pd.NA)
df_copy['csrvctl2'].value_counts(dropna=False)

csrvctl2
NaN     400105
1.0        742
2.0        621
4.0        254
3.0        161
<NA>        75
Name: count, dtype: int64

## Module 14: Prostate Cancer Screening Decision Making

### pcpsade1
**Question:** What is the respondent's psa decision making role?
- `1` = You made the decision alone
- `2` = Your doctor, nurse, or health care provider made the decision alone
- `3` = You and one or more other persons made the decision together
- `4` = You don't know how the decision was made
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1303]:
df_copy['pcpsade1'] = df_copy['pcpsade1'].replace([7, 9], pd.NA)
df_copy['pcpsade1'].value_counts(dropna=False)

pcpsade1
NaN     400117
2.0        782
1.0        507
3.0        418
4.0        114
<NA>        20
Name: count, dtype: int64

### pcdmdec1
**Question:** What is the respondent's status for who helped make psa decision?
- `1` = Doctor/nurse/health care provider
- `2` = Spouse/significant other
- `3` = Other family member
- `4` = Friend/non-relative
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1304]:
df_copy['pcdmdec1'] = df_copy['pcdmdec1'].replace([7, 9], pd.NA)
df_copy['pcdmdec1'].value_counts(dropna=False)

pcdmdec1
NaN     401540
1.0        367
2.0         41
3.0          6
4.0          2
<NA>         2
Name: count, dtype: int64

## Module 15: Adult Human Papillomavirus (HPV) - Vaccination

### hpvadvc4
**Question:** What is the respondent's hpv vaccine status?
- `1` = Yes
- `2` = No
- `3` = Doctor refused when asked
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1305]:
df_copy['hpvadvc4'] = df_copy['hpvadvc4'].replace([7, 9], pd.NA)
df_copy['hpvadvc4'].value_counts(dropna=False)

hpvadvc4
NaN     386846
2.0      10469
1.0       2784
<NA>      1859
Name: count, dtype: int64

### hpvadsht
**Question:** What is the respondent's hpv vaccine shot count?
- number of H.P.V. shots received
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [1306]:
df_copy['hpvadsht'] = df_copy['hpvadsht'].replace([77, 99], pd.NA)
df_copy['hpvadsht'].value_counts(dropna=False)

hpvadsht
NaN     399179
3.0       1340
<NA>       690
2.0        398
1.0        351
Name: count, dtype: int64

## Module 16: Tetanus Diphtheria (Tdap) (Adults)

### tetanus1
**Question:** What is the respondent's tetanus tdap status?
- `1` = Yes, received Tdap
- `2` = Yes, received tetanus shot, but not Tdap
- `3` = Yes, received tetanus shot but not sure what type
- `4` = No, did not receive any tetanus shot in the past 10 years
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [1307]:
df_copy['tetanus1'] = df_copy['tetanus1'].replace([7, 9], pd.NA)
df_copy['tetanus1'].value_counts(dropna=False)

tetanus1
NaN     394003
3.0       2450
1.0       2115
4.0       2063
<NA>       701
2.0        626
Name: count, dtype: int64

## Module 17: Place of Flu Vaccination

- no executable cleaning cells added because no Module 17 variables are included in `features`

## Module 18: Industry and Occupation

- no executable cleaning cells added because no Module 18 variables are included in `features`

## Module 19: Sex at Birth

### birthsex
**Question:** What is the respondent's status for male?
- `1` = Male
- `2` = Female
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [1308]:
df_copy['birthsex'] = df_copy['birthsex'].replace({2: 0})
df_copy['birthsex'] = df_copy['birthsex'].replace([7, 9], pd.NA)
df_copy['birthsex'].value_counts(dropna=False)

birthsex
NaN     300719
0.0      54541
1.0      46371
<NA>       327
Name: count, dtype: int64

## Module 20: Sexual Orientation and Gender Identity (SOGI)

### somale
**Question:** Which response best describes the respondent's sexual attraction to males?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1309]:
df_copy['somale'] = df_copy['somale'].replace([7, 9, 77, 99], pd.NA)
df_copy['somale'].value_counts(dropna=False)

somale
NaN     291919
2.0     101417
<NA>      3067
1.0       2320
3.0       1775
4.0       1460
Name: count, dtype: int64

### sofemale
**Question:** Which response best describes the respondent's sexual attraction to females?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1310]:
df_copy['sofemale'] = df_copy['sofemale'].replace([7, 9, 77, 99], pd.NA)
df_copy['sofemale'].value_counts(dropna=False)

sofemale
NaN     271880
2.0     117865
<NA>      4762
3.0       3889
4.0       1885
1.0       1677
Name: count, dtype: int64

### trnsgndr
**Question:** Which response best describes the respondent's transgender status?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1311]:
df_copy['trnsgndr'] = df_copy['trnsgndr'].replace([7, 9, 77, 99], pd.NA)
df_copy['trnsgndr'].value_counts(dropna=False)

trnsgndr
4.0     235887
NaN     161936
<NA>      3118
1.0        372
2.0        367
3.0        278
Name: count, dtype: int64

## Module 21: Adverse Childhood Experiences

- no executable cleaning cells added because no Module 21 variables are included in `features`

## Module 22: Random Child Selection

### rcsgendr
**Question:** What is the sex of the randomly selected child?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1312]:
df_copy['rcsgendr'] = df_copy['rcsgendr'].replace([7, 9, 77, 99], pd.NA)
df_copy['rcsgendr'].value_counts(dropna=False)

rcsgendr
NaN     346998
1.0      26889
2.0      24891
<NA>      3180
Name: count, dtype: int64

### rcsrltn2
**Question:** How is the randomly selected child related to the respondent?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1313]:
df_copy['rcsrltn2'] = df_copy['rcsrltn2'].replace([7, 9, 77, 99], pd.NA)
df_copy['rcsrltn2'].value_counts(dropna=False)

rcsrltn2
NaN     347440
1.0      42005
2.0       4697
4.0       2776
<NA>      1978
5.0       1409
6.0        952
3.0        701
Name: count, dtype: int64

## Module 23: Childhood Asthma Prevalence

### casthdx2
**Question:** Has a doctor, nurse, or other health professional ever said that the selected child has asthma?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1314]:
df_copy['casthdx2'] = df_copy['casthdx2'].replace([7, 9, 77, 99], pd.NA)
df_copy['casthdx2'].value_counts(dropna=False)

casthdx2
NaN     352527
2.0      41616
1.0       5495
<NA>      2320
Name: count, dtype: int64

### casthno2
**Question:** Does the selected child still have asthma?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [1315]:
df_copy['casthno2'] = df_copy['casthno2'].replace([7, 9, 77, 99], pd.NA)
df_copy['casthno2'].value_counts(dropna=False)

casthno2
NaN     396463
1.0       3591
2.0       1758
<NA>       146
Name: count, dtype: int64

### Rename Management Columns
Rename the cleaned diabetes-management variables to readable analysis names before EDA and export

In [1316]:
df_copy = df_copy.rename(columns={
    'diabedu': 'Diabetes_Education',
    'toldcfs': 'Told_Has_ME_CFS',
    'havecfs': 'Still_Has_ME_CFS',
    'workcfs': 'Work_Hours_Per_Week_With_ME_CFS',
    'toldhepc': 'Told_Has_Hepatitis_C',
    'trethepc': 'Treated_Hepatitis_C_2015_Or_After',
    'prirhepc': 'Treated_Hepatitis_C_Before_2015',
    'havehepc': 'Still_Has_Hepatitis_C',
    'havehepb': 'Told_Has_Hepatitis_B',
    'medshepb': 'Taking_Medicine_For_Hepatitis_B',
    'feetchk3': 'Foot_Self_Check_Freq',
    'bldsugar': 'Blood_Sugar_Check_Freq',
    'doctdiab': 'Doctor_Visit_Diabetes_Freq',
    'chkhemo3': 'A1C_Check_Freq',
    'feetchk': 'Professional_Foot_Check_Freq',
    'eyeexam1': 'Eye_Exam_Recency',
    'genhlth': 'General_Health',
    'physhlth': 'Bad_Physical_Health_Days',
    'poorhlth': 'Poor_Health_Impact_Days',
    'medcost': 'Skipped_Doctor_Due_To_Cost',
    'checkup1': 'Checkup_Recency',
    'exerany2': 'Any_Exercise',
    'sleptim1': 'Sleep_Hours',
    'cvdinfr4': 'Heart_Attack',
    'cvdcrhd4': 'Coronary_Heart_Disease',
    'cvdstrk3': 'Stroke',
    'asthma3': 'Ever_Asthma',
    'asthnow': 'Current_Asthma',
    'chcscncr': 'Skin_Cancer',
    'chcocncr': 'Other_Cancer',
    'chccopd2': 'COPD',
    'havarth4': 'Arthritis',
    'chckdny2': 'Kidney_Disease',
    'lastden4': 'Dental_Visit_Recency',
    'rmvteth4': 'Teeth_Removed',
    'x.hispanc': 'Hispanic',
    'x.mrace1': 'Race_Multi_Select',
    'x.prace1': 'Race_Best_Represents',
    'renthom1': 'Own_Or_Rent',
    'numhhol3': 'Multiple_Phones_In_Household',
    'numphon3': 'Residential_Phones',
    'cpdemo1b': 'Personal_Cell_Phones',
    'veteran3': 'Veteran_Status',
    'children': 'Children_In_Household',
    'weight2': 'Weight',
    'height3': 'Height',
    'pregnant': 'Pregnant',
    'deaf': 'Deaf_Or_Serious_Hearing_Difficulty',
    'blind': 'Blind_Or_Serious_Vision_Difficulty',
    'decide': 'Serious_Difficulty_Decisions',
    'diffwalk': 'Serious_Difficulty_Walking',
    'diffdres': 'Serious_Difficulty_Dressing',
    'diffalon': 'Serious_Difficulty_Doing_Errands',
    'menthlth': 'Bad_Mental_Health_Days',
    'educa': 'Education',
    'x.ageg5yr': 'Age_Group',
    'birthsex': 'Male',
    'marital': 'Marital_Status',
    'employ1': 'Employment_Status',
    'income2': 'Income',
    'x.urbstat': 'Urban_Rural_Status',
    'persdoc2': 'Personal_Doctor',
    'hlthpln1': 'Health_Coverage',
    'addepev3': 'Depressive_Disorder',
    'diabete4': 'Diabetes_Status',
    'diabage3': 'Diabetes_Age',
    'smoke100': 'Smoked_100_Cigarettes',
    'smokday2': 'Smoke_Frequency',
    'stopsmk2': 'Stopped_Smoking_One_Day',
    'lastsmk2': 'Last_Smoked_Recency',
    'usenow3': 'Smokeless_Tobacco_Frequency',
    'alcday5': 'Alcohol_Frequency',
    'avedrnk3': 'Average_Drinks',
    'drnk3ge5': 'Binge_Drinking_Frequency',
    'maxdrnks': 'Max_Drinks',
    'flushot7': 'Flu_Shot',
    'pneuvac4': 'Pneumonia_Vaccine',
    'fall12mn': 'Falls_Past_12_Months',
    'fallinj4': 'Fall_Injuries_Past_12_Months',
    'seatbelt': 'Seatbelt_Use',
    'drnkdri2': 'Drinking_And_Driving_Frequency',
    'hadmam': 'Ever_Had_Mammogram',
    'howlong': 'Mammogram_Recency',
    'hadpap2': 'Ever_Had_Pap_Test',
    'lastpap2': 'Pap_Test_Recency',
    'hpvtest': 'Ever_Had_HPV_Test',
    'hplsttst': 'HPV_Test_Recency',
    'hadhyst2': 'Had_Hysterectomy',
    'pcpsaad3': 'Discussed_PSA_Advantages',
    'pcpsadi1': 'Discussed_PSA_Disadvantages',
    'pcpsare1': 'Recommended_PSA_Test',
    'psatest1': 'Ever_Had_PSA_Test',
    'psatime': 'PSA_Test_Recency',
    'pcpsars1': 'Reason_For_PSA_Test',
    'colnscpy': 'Ever_Had_Colonoscopy',
    'colntest': 'Colonoscopy_Recency',
    'sigmscpy': 'Ever_Had_Sigmoidoscopy',
    'sigmtest': 'Sigmoidoscopy_Recency',
    'bldstol1': 'Ever_Had_Blood_Stool_Test',
    'lstblds4': 'Blood_Stool_Test_Recency',
    'stooldna': 'Ever_Had_Stool_DNA_Test',
    'sdnatest': 'Stool_DNA_Test_Recency',
    'vircolon': 'Ever_Had_Virtual_Colonoscopy',
    'vclntest': 'Virtual_Colonoscopy_Recency',
    'hivtst7': 'Ever_Had_HIV_Test',
    'hivtstd3': 'HIV_Test_Time',
    'hivrisk5': 'Any_HIV_Risk_Situation',
    'pdiabtst': 'Prediabetes_Test_Past_3_Years',
    'prediab1': 'Told_Has_Prediabetes',
    'insulin1': 'Taking_Insulin',
    'diabeye': 'Diabetes_Affected_Eyes',
    'hlthcvr1': 'Primary_Health_Coverage_Source',
    'cimemlos': 'Worsening_Confusion_Or_Memory_Loss',
    'cdhouse': 'Confusion_Interfered_Household_Activities',
    'cdassist': 'Need_Assistance_Day_To_Day_Activities',
    'cdhelp': 'Gets_Needed_Help_For_Activities',
    'cdsocial': 'Confusion_Interfered_Social_Activities',
    'cddiscus': 'Discussed_Confusion_With_Health_Professional',
    'caregiv1': 'Provided_Care_Past_30_Days',
    'crgvrel4': 'Care_Recipient_Relationship',
    'crgvlng1': 'Caregiving_Duration',
    'crgvhrs1': 'Caregiving_Hours_Per_Week',
    'crgvprb3': 'Care_Recipient_Main_Problem',
    'crgvper1': 'Provided_Personal_Care',
    'crgvhou1': 'Provided_Household_Tasks',
    'crgvexpt': 'Expect_To_Provide_Care_Next_2_Years',
    'ecigaret': 'Ever_Used_E_Cigarette',
    'ecignow': 'E_Cigarette_Frequency',
    'marijan1': 'Marijuana_Use_Days_Past_30',
    'usemrjn2': 'Most_Frequent_Marijuana_Use_Method',
    'rsnmrjn1': 'Reason_For_Marijuana_Use',
    'lcsfirst': 'Age_Started_Smoking_Regularly',
    'lcslast': 'Age_Last_Smoked_Regularly',
    'lcsnumcg': 'Cigarettes_Per_Day_When_Smoking',
    'lcsctscn': 'Had_Lung_Cancer_CT_Scan',
    'cncrdiff': 'Number_Of_Cancer_Types',
    'cncrage': 'Age_First_Diagnosed_Cancer',
    'cncrtyp1': 'Most_Recent_Cancer_Type',
    'csrvtrt3': 'Currently_Receiving_Cancer_Treatment',
    'csrvdoc1': 'Cancer_Care_Doctor_Type',
    'csrvsum': 'Received_Cancer_Treatment_Summary',
    'csrvrtrn': 'Received_Follow_Up_Instructions',
    'csrvinst': 'Follow_Up_Instructions_Written',
    'csrvinsr': 'Insurance_Paid_For_Cancer_Treatment',
    'csrvdein': 'Denied_Insurance_Because_Of_Cancer',
    'csrvclin': 'Participated_In_Cancer_Clinical_Trial',
    'csrvpain': 'Current_Physical_Pain_From_Cancer_Treatment',
    'csrvctl2': 'Cancer_Pain_Control_Status',
    'pcpsade1': 'PSA_Decision_Making_Role',
    'pcdmdec1': 'Who_Helped_Make_PSA_Decision',
    'hpvadvc4': 'HPV_Vaccine_Status',
    'hpvadsht': 'HPV_Vaccine_Shot_Count',
    'tetanus1': 'Tetanus_Tdap_Status',
    'shingle2': 'Shingles_Vaccine',
    'rmvteth4': 'Teeth_Removed',
    'somale': 'Sex_Attracted_To_Males',
    'sofemale': 'Sex_Attracted_To_Females',
    'trnsgndr': 'Transgender_Status',
    'rcsgendr': 'Random_Child_Gender',
    'rcsrltn2': 'Child_Relationship_To_Respondent',
    'casthdx2': 'Child_Ever_Diagnosed_With_Asthma',
    'casthno2': 'Child_Current_Asthma',
})

### Normalize Missing Values
Convert any remaining `NaN` values to `pd.NA` and switch columns to pandas nullable dtypes before reporting missingness and saving

In [1317]:
df_copy = df_copy.mask(df_copy.isna(), pd.NA).convert_dtypes()
df_copy.dtypes

General_Health                      Float64
Bad_Physical_Health_Days            Float64
Bad_Mental_Health_Days              Float64
Poor_Health_Impact_Days             Float64
Health_Coverage                     Float64
                                     ...
Transgender_Status                  Float64
Random_Child_Gender                 Float64
Child_Relationship_To_Respondent    Float64
Child_Ever_Diagnosed_With_Asthma    Float64
Child_Current_Asthma                Float64
Length: 161, dtype: object

In [1318]:
missing_pct = (
    df_copy.isna().mean().mul(100).round(2).sort_values(ascending=False).rename('missing_pct').to_frame()
)
missing_pct

                                 missing_pct
Told_Has_ME_CFS                       100.00
Work_Hours_Per_Week_With_ME_CFS       100.00
Still_Has_ME_CFS                      100.00
Taking_Medicine_For_Hepatitis_B        99.96
Still_Has_Hepatitis_C                  99.94
...                                      ...
Other_Cancer                            0.29
Skipped_Doctor_Due_To_Cost              0.28
General_Health                          0.24
Diabetes_Status                         0.20
Any_Exercise                            0.17

[161 rows x 1 columns]

In [1319]:
df_copy

,General_Health,Bad_Physical_Health_Days,Bad_Mental_Health_Days,Poor_Health_Impact_Days,Health_Coverage,Personal_Doctor,Skipped_Doctor_Due_To_Cost,Checkup_Recency,Any_Exercise,Sleep_Hours,Heart_Attack,Coronary_Heart_Disease,Stroke,Ever_Asthma,Current_Asthma,Skin_Cancer,Other_Cancer,COPD,Arthritis,Depressive_Disorder,Kidney_Disease,Diabetes_Status,Diabetes_Age,Dental_Visit_Recency,Teeth_Removed,Age_Group,Hispanic,Race_Multi_Select,Race_Best_Represents,Marital_Status,Education,Own_Or_Rent,Urban_Rural_Status,Multiple_Phones_In_Household,Residential_Phones,Personal_Cell_Phones,Veteran_Status,Employment_Status,Children_In_Household,Income,Pregnant,Weight,Height,Deaf_Or_Serious_Hearing_Difficulty,Blind_Or_Serious_Vision_Difficulty,Serious_Difficulty_Decisions,Serious_Difficulty_Walking,Serious_Difficulty_Dressing,Serious_Difficulty_Doing_Errands,Smoked_100_Cigarettes,Smoke_Frequency,Stopped_Smoking_One_Day,Last_Smoked_Recency,Smokeless_Tobacco_Frequency,Alcohol_Frequency,Average_Drinks,Binge_Drinking_Frequency,Max_Drinks,Flu_Shot,Shingles_Vaccine,Pneumonia_Vaccine,Falls_Past_12_Months,Fall_Injuries_Past_12_Months,Seatbelt_Use,Drinking_And_Driving_Frequency,Ever_Had_Mammogram,Mammogram_Recency,Ever_Had_Pap_Test,Pap_Test_Recency,Ever_Had_HPV_Test,HPV_Test_Recency,Had_Hysterectomy,Discussed_PSA_Advantages,Discussed_PSA_Disadvantages,Recommended_PSA_Test,Ever_Had_PSA_Test,PSA_Test_Recency,Reason_For_PSA_Test,Ever_Had_Colonoscopy,Colonoscopy_Recency,Ever_Had_Sigmoidoscopy,Sigmoidoscopy_Recency,Ever_Had_Blood_Stool_Test,Blood_Stool_Test_Recency,Ever_Had_Stool_DNA_Test,Stool_DNA_Test_Recency,Ever_Had_Virtual_Colonoscopy,Virtual_Colonoscopy_Recency,Ever_Had_HIV_Test,HIV_Test_Time,Any_HIV_Risk_Situation,Prediabetes_Test_Past_3_Years,Told_Has_Prediabetes,Taking_Insulin,Blood_Sugar_Check_Freq,Foot_Self_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Diabetes_Affected_Eyes,Diabetes_Education,Told_Has_ME_CFS,Still_Has_ME_CFS,Work_Hours_Per_Week_With_ME_CFS,Told_Has_Hepatitis_C,Treated_Hepatitis_C_2015_Or_After,Treated_Hepatitis_C_Before_2015,Still_Has_Hepatitis_C,Told_Has_Hepatitis_B,Taking_Medicine_For_Hepatitis_B,Primary_Health_Coverage_Source,Worsening_Confusion_Or_Memory_Loss,Confusion_Interfered_Household_Activities,Need_Assistance_Day_To_Day_Activities,Gets_Needed_Help_For_Activities,Confusion_Interfered_Social_Activities,Discussed_Confusion_With_Health_Professional,Provided_Care_Past_30_Days,Care_Recipient_Relationship,Caregiving_Duration,Caregiving_Hours_Per_Week,Care_Recipient_Main_Problem,Provided_Personal_Care,Provided_Household_Tasks,Expect_To_Provide_Care_Next_2_Years,Ever_Used_E_Cigarette,E_Cigarette_Frequency,Marijuana_Use_Days_Past_30,Most_Frequent_Marijuana_Use_Method,Reason_For_Marijuana_Use,Age_Started_Smoking_Regularly,Age_Last_Smoked_Regularly,Cigarettes_Per_Day_When_Smoking,Had_Lung_Cancer_CT_Scan,Number_Of_Cancer_Types,Age_First_Diagnosed_Cancer,Most_Recent_Cancer_Type,Currently_Receiving_Cancer_Treatment,Cancer_Care_Doctor_Type,Received_Cancer_Treatment_Summary,Received_Follow_Up_Instructions,Follow_Up_Instructions_Written,Insurance_Paid_For_Cancer_Treatment,Denied_Insurance_Because_Of_Cancer,Participated_In_Cancer_Clinical_Trial,Current_Physical_Pain_From_Cancer_Treatment,Cancer_Pain_Control_Status,PSA_Decision_Making_Role,Who_Helped_Make_PSA_Decision,HPV_Vaccine_Status,HPV_Vaccine_Shot_Count,Tetanus_Tdap_Status,Male,Sex_Attracted_To_Males,Sex_Attracted_To_Females,Transgender_Status,Random_Child_Gender,Child_Relationship_To_Respondent,Child_Ever_Diagnosed_With_Asthma,Child_Current_Asthma
0,2.0,3.0,30.0,3.0,0.0,3.0,1.0,4.0,1.0,5.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,35.0,1.0,2.0,8,0,1.0,1.0,2.0,6.0,1.0,1,0.0,<NA>,1.0,0.0,4.0,0.0,1.0,<NA>,106.0,507.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,<NA>,3.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,88.0,<NA>,1.0,<NA>,1.0,3.0,1.0,4.0,0.0,<NA>,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,4.0,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,1.0,21994.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,7.0,0.0,1.0,1.0,0.0,0.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,3.0,0.0,0.0,<NA>,1.0,1.0,1.0,1.0,1.0,7.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,<NA>,1.0,1.0,10,0,2.0,2.0,3.0,6.0,1.0,1,1.0,1.0,1.0,0.0,7.0,0.0,<NA>,<NA>,170.0,504.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,3.0,0.0,0.0,<NA>,1.0,1.0,0.0,1.0,1.0,7.0,0.0,0.0,0.0,0.0,<NA>,0.0,1.0,0.0,1.0,0.0,0.0,3.0,<NA>,1.0,<NA>,10,0,2.0,2.0,1.0,5.0,1.0,1,0.0,<NA>,1.0,0.0,7.0,0.0,7.0,<NA>,<NA>,508.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,1.0,0.0,0.0,88.0,<NA>,1.0,<NA>,1.0,1.0,1.0,1.0,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,4.0,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,2.0,0.0,1.0,1.0,1.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,1.0,0.0,0.0,<NA>,1.0,3.0,0.0,2.0,0.0,6.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,<NA>,1.0,13,0,1.0,1.0,3.0,4.0,1.0,1,<NA>,<NA>,<NA>,0.0,5.0,0.0,<NA>,<NA>,<NA>,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,88.0,<NA>,1.0,<NA>,0.0,<NA>,1.0,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,2.0,0.0,0.0,<NA>,1.0,1.0,0.0,1.0,1.0,7.0,0.0,0.0,1.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,<NA>,8.0,13,0,1.0,1.0,3.0,6.0,2.0,1,0.0,<NA>,8.0,0.0,7.0,0.0,<NA>,<NA>,126.0,506.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,1.0,1.0,1.0,88.0,<NA>,1.0,<NA>,1.0,1.0,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401953,3.0,0.0,0.0,<NA>,0.0,1.0,0.0,2.0,1.0,6.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,1.0,0.0,3.0,<NA>,2.0,1.0,6,1,1.0,1.0,2.0,5.0,1.0,<NA>,<NA>,<NA>,3.0,0.0,1.0,1.0,<NA>,0.0,120.0,411.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,0.0,<NA>,0.0,88.0,<NA>,1.0,<NA>,1.0,5.0,1.0,3.0,1.0,3.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,1.0,<NA>,0.0,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,1.0,2.0,<NA>
401954,3.0,0.0,0.0,<NA>,1.0,1.0,0.0,3.0,0.0,12.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,1.0,1.0,2,1,6.0,6.0,1.0,3.0,2.0,<NA>,<NA>,<NA>,1.0,0.0,5.0,4.0,4.0,0.0,168.0,500.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,<NA>,1.0,<NA>,0.0,<NA>,1.0,5.0,1.0,5.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,92019.0,0.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,1.0,2.0,<NA>
401955,3.0,0.0,0.0,<NA>,1.0,1.0,0.0,2.0,1.0,8.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,1.0,8.0,13,1,1.0,1.0,1.0,4.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,5.0,0.0,1.0,<NA>,159.0,401.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,1.0,0.0,1.0,88.0,<NA>,1.0,<NA>,1.0,2.0,1.0,5.0,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,3.0,0.0,<NA>,1.0,2.0,0.0,<NA>,0.0,<NA>,0.0,<NA>,0.0,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
401956,3.0,0.0,0.0,<NA>,1.0,1.0,0.0,1.0,1.0,6.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,1.0,1.0,8,1,1.0,1.0,1.0,6.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,1.0,0.0,<NA>,<NA>,175.0,508.0,0.0,1.0,0.0,0.0,0.0,0.0,<NA>,<NA>,<NA>,<NA>,3.0,101.0,2.0,88.0,4.0,1.0,0.0,0.0,88.0,<NA>,1.0,88.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,<NA>,1.0,1.0,0.0,<NA>,0.0,<NA>,1.0,<NA>,0.0,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
401957,3.0,2.0,7.0,2.0,1.0,1.0,0.0,1.0,0.0,6.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,<NA>,4.0,<NA>,1.0,2.0,9,1,2.0,2.0,1.0,6.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,8.0,0.0,5.0,<NA>,197.0,507.0,<NA>,1.0,1.0,0.0,0.0,1.0,0.0,<NA>,<NA>,<NA>,3.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,1.0,1.0,88.0,1.0,<NA>,1.0,1.0,1.0,1.0,1.0,1.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,4.0,0.0,<NA>,1.0,1.0,0.0,<NA>,0.0,<NA>,1.0,82020.0,0.0,1.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Data Path

In [1320]:
data_path = '../../data/clean'

### Save Dataset

In [1321]:
missing_pct.to_csv(f'{data_path}/missing/{year}_missing_pct.csv')
df_copy.to_csv(f'{data_path}/brfss/{year}_brfss_data.csv', index=False)