# Getting Data

### Imports
- import the libraries used for data loading, cleaning, and sampling

In [ ]:
import pandas as pd

### Survey Year
- set the BRFSS year used to build the file path

In [ ]:
year = '2020'

### Load CSV
- load the 2018 BRFSS CSV into a dataframe

In [ ]:
brfss_2020_df = pd.read_csv(f'brfss2020.csv')

### Dataset Shape
- inspect the number of rows and columns in the raw 2018 BRFSS file

In [ ]:
brfss_2020_df.shape

(401958, 280)

### Display Settings
- show more columns when previewing the dataframe
- display the first few rows of the raw dataset

In [ ]:
pd.set_option('display.max_columns', 500)
brfss_2020_df.head()

,Unnamed: 0,x.state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,x.psu,ctelenm1,pvtresd1,colghous,statere1,celphone,ladult1,colgsex,numadult,landsex,nummen,numwomen,respslct,safetime,ctelnum1,cellfon5,cadult1,cellsex,pvtresd3,cclghous,cstate1,landline,hhadult,sexvar,genhlth,physhlth,menthlth,poorhlth,hlthpln1,persdoc2,medcost,checkup1,exerany2,sleptim1,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd2,havarth4,addepev3,chckdny2,diabete4,diabage3,lastden4,rmvteth4,marital,educa,renthom1,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income2,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,stopsmk2,lastsmk2,usenow3,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,flshtmy3,shingle2,pneuvac4,fall12mn,fallinj4,seatbelt,drnkdri2,hadmam,howlong,hadpap2,lastpap2,hpvtest,hplsttst,hadhyst2,pcpsaad3,pcpsadi1,pcpsare1,psatest1,psatime,pcpsars1,colnscpy,colntest,sigmscpy,sigmtest,bldstol1,lstblds4,stooldna,sdnatest,vircolon,vclntest,hivtst7,hivtstd3,hivrisk5,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hlthcvr1,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvalzd,crgvper1,crgvhou1,crgvexpt,ecigaret,ecignow,marijan1,usemrjn2,rsnmrjn1,lcsfirst,lcslast,lcsnumcg,lcsctscn,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,pcpsade1,pcdmdec1,hpvadvc4,hpvadsht,tetanus1,imfvpla1,birthsex,somale,sofemale,trnsgndr,acedeprs,acedrink,acedrugs,aceprisn,acedivrc,acepunch,acehurt1,aceswear,acetouch,acetthem,acehvsex,rcsgendr,rcsrltn2,casthdx2,casthno2,qstver,qstlang,x.metstat,x.urbstat,mscode,x.ststr,x.strwt,x.rawrake,x.wt2rake,x.imprace,x.chispnc,x.crace1,x.cprace,x.cllcpwt,x.dualuse,x.dualcor,x.llcpwt2,x.llcpwt,x.rfhlth,x.phys14d,x.ment14d,x.hcvu651,x.totinda,x.michd,x.ltasth1,x.casthm1,x.asthms1,x.drdxar2,x.exteth3,x.alteth3,x.denvst3,x.prace1,x.mrace1,x.hispanc,x.race,x.raceg21,x.racegr3,x.raceprv,x.sex,x.ageg5yr,x.age65yr,x.age80,x.age.g,htin4,htm4,wtkg3,x.bmi5,x.bmi5cat,x.rfbmi5,x.chldcnt,x.educag,x.incomg,x.smoker3,x.rfsmok3,drnkany5,drocdy3.,x.rfbing5,x.drnkwk1,x.rfdrhv7,x.flshot7,x.pneumo3,x.rfseat2,x.rfseat3,x.drnkdrv,x.rfmam22,x.mam5023,x.rfpap35,x.rfpsa23,x.clnscpy,x.sgmscpy,x.sgms10y,x.rfblds4,x.stoldna,x.vircoln,x.sbontim,x.crcrec1,x.aidtst4
0,1,1,1,1042020,1,4,2020,1100,2020000001,2020000001,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,3.0,30.0,3.0,2.0,3.0,1.0,4.0,1.0,5.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,35.0,1.0,2.0,2.0,6.0,1.0,2.0,NaN,1.0,2.0,4.0,88.0,1.0,NaN,106.0,507.0,2.0,2.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,1.0,3.0,1.0,4.0,2.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,1.0,21994.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,7.0,2.0,1.0,1.0,2.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,2.0,1.0,1.0,1.0,3.0,3.0,3.0,2.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,1,0.465411,460.002849,284.335672,1,2,3,2,1,2.0,2,2,1,1.0,2,NaN,1,1.0,1.0,2,1.0,1.0,1.0,1.0,2,8,1,56,5,67.0,170.0,4808.0,1660.0,1.0,1,1,4,1,1,2,2,0,1,0,1,NaN,NaN,1,1,9,2.0,2.0,NaN,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,1.0
1,2,1,1,2072020,2,7,2020,1200,2020000002,2020000002,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,1.0,1.0,1.0,1.0,7.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,1.0,1.0,2.0,3.0,NaN,1.0,1.0,3.0,6.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,99.0,NaN,170.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,2,NaN,NaN,NaN,NaN,1,0.465411,460.002849,171.283329,1,1,1,9,1,2.0,2,1,2,1.0,2,1.0,1,2.0,2.0,2,2.0,2.0,2.0,2.0,2,10,2,65,6,64.0,163.0,7711.0,2918.0,3.0,2,1,4,9,9,9,9,900,9,99900,9,9.0,9.0,9,9,9,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN
2,3,1,1,1232020,1,23,2020,1100,2020000003,2020000003,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,2.0,2.0,NaN,2.0,1.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,7.0,1.0,5.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,7777.0,508.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,2.0,2.0,88.0,NaN,1.0,NaN,1.0,1.0,1.0,1.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,4.0,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11012,279.748901,1.0,279.748901,2,NaN,NaN,NaN,NaN,1,0.465411,1847.859106,1334.368863,1,1,1,9,1,2.0,1,1,3,1.0,9,9.0,1,2.0,2.0,2,2.0,2.0,2.0,2.0,2,10,2,65,6,68.0,173.0,NaN,NaN,NaN,9,1,3,5,4,1,2,0,1,0,1,1.0,2.0,1,1,9,1.0,1.0,1.0,NaN,1.0,3.0,3.0,3.0,3.0,3.0,3.0,1.0,2.0
3,4,1,1,1092020,1,9,2020,1100,2020000004,2020000004,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,1.0,88.0,88.0,NaN,1.0,3.0,2.0,2.0,2.0,6.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,1.0,3.0,4.0,1.0,9.0,NaN,9.0,2.0,5.0,88.0,99.0,NaN,9999.0,9999.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,2.0,NaN,2.0,2.0,88.0,NaN,1.0,NaN,2.0,NaN,1.0,7.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,9,NaN,1472.417322,1297.486618,1,1,1,9,2,2.0,1,1,3,2.0,2,1.0,9,1.0,1.0,2,1.0,1.0,1.0,1.0,2,13,2,80,6,NaN,NaN,NaN,NaN,NaN,9,1,2,9,4,1,2,0,1,0,1,2.0,2.0,1,1,9,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
4,5,1,1,1042020,1,4,2020,1100,2020000005,2020000005,1.0,1.0,NaN,1.0,2.0,1.0,NaN,1.0,2.0,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,88.0,NaN,1.0,1.0,2.0,1.0,1.0,7.0,2.0,2.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,2.0,3.0,NaN,7.0,8.0,3.0,6.0,2.0,2.0,NaN,8.0,2.0,7.0,88.0,77.0,NaN,126.0,506.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,3.0,888.0,NaN,NaN,NaN,1.0,102019.0,1.0,1.0,88.0,NaN,1.0,NaN,1.0,1.0,2.0,NaN,7.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,7.0,2.0,NaN,7.0,NaN,7.0,NaN,2.0,NaN,7.0,NaN,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,69.640207,1.0,69.640207,1,NaN,NaN,NaN,NaN,9,NaN,1472.417322,454.815127,1,1,1,9,1,2.0,1,1,3,2.0,1,1.0,9,1.0,1.0,2,1.0,1.0,1.0,1.0,2,13,2,80,6,66.0,168.0,5715.0,2034.0,2.0,1,1,4,9,4,1,2,0,1,0,1,1.0,1.0,1,1,9,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0

### Diabetes Status Subset
- create a full-population dataframe using only `diabete3`
- drop missing values for the diabetes-status variable

In [ ]:
diabetes_status_df = brfss_2020_df[['diabete4']].dropna()
diabetes_status_df.shape

(401952, 1)

### Clean Diabetes Status
- remove invalid `diabete3` codes for don't know and refused
- inspect the remaining diabetes-status counts

In [ ]:
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete4'] != 7]
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete4'] != 9]
diabetes_status_df['diabete4'].value_counts().sort_index()

diabete4
1.0     52094
2.0      3374
3.0    337064
4.0      8612
Name: count, dtype: int64

### Recode Diabetes Target
- convert BRFSS diabetes codes into the `0/1/2` target used in the reference notebook

In [ ]:
diabetes_status_df['Diabetes_012'] = diabetes_status_df['diabete4'].replace({
    2: 0,
    4: 0,
    3: 1,
    1: 2,
})

diabetes_status_df.groupby(['Diabetes_012']).size()

Diabetes_012
0.0     11986
1.0    337064
2.0     52094
dtype: int64

### Feature List
- define the diabetes-management variables and covariates used in the paper-style analysis dataframe

In [ ]:
columns = [
"diabedu",
"feetchk3",
"bldsugar",
"doctdiab",
"chkhemo3",
"feetchk",
"eyeexam1",
"menthlth",
"educa",
"x.ageg5yr",
"birthsex",
"marital",
"employ1",
"income2",
"x.urbstat",
"persdoc2",
"hlthpln1",
"addepev3",
"diabete4",
"diabage3"
]

### Select Analysis Columns
- build `features_df` from the selected diabetes-management variables

In [ ]:
features_df = brfss_2020_df[columns].copy()

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [ ]:
features_df.shape

(401958, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [ ]:
features_df.head()

,diabedu,feetchk3,bldsugar,doctdiab,chkhemo3,feetchk,eyeexam1,menthlth,educa,x.ageg5yr,birthsex,marital,employ1,income2,x.urbstat,persdoc2,hlthpln1,addepev3,diabete4,diabage3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,6.0,8,NaN,2.0,4.0,1.0,1.0,3.0,2.0,1.0,1.0,35.0
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,10,NaN,3.0,7.0,99.0,1.0,1.0,1.0,1.0,3.0,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,5.0,10,NaN,1.0,7.0,7.0,1.0,1.0,1.0,2.0,3.0,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,4.0,13,NaN,3.0,5.0,99.0,1.0,3.0,1.0,2.0,3.0,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,13,NaN,3.0,7.0,77.0,1.0,1.0,1.0,2.0,3.0,NaN

# Cleaning

### Drop Missing Values
- remove rows with missing values across the selected diabetes-management variables

In [ ]:
features_df = features_df.dropna()
features_df.shape

(1438, 20)

### diabedu
- whether respondent ever took a diabetes management class
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [ ]:
features_df = features_df[features_df['diabedu'] != 7]
features_df = features_df[features_df['diabedu'] != 9]
features_df['diabedu'] = features_df['diabedu'].replace({2: 0})
features_df['diabedu'].unique()

array([1., 0.])

### feetchk3
- how often respondent checks their feet for sores or irritation
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [ ]:
features_df = features_df[features_df['feetchk3'] != 777]
features_df = features_df[features_df['feetchk3'] != 999]
features_df['feetchk3'].unique()

array([101., 301., 107., 201., 360., 102., 888., 204., 401., 203., 202.,
       304., 416., 404., 130., 499., 103., 207., 330., 403., 104., 205.,
       402., 199., 302., 221., 303., 406., 299., 365., 209., 227., 325.,
       110., 315., 208., 105.])

### bldsugar
- how often respondent checks blood sugar
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [ ]:
features_df = features_df[features_df['bldsugar'] != 777]
features_df = features_df[features_df['bldsugar'] != 999]
features_df['bldsugar'].unique()

array([103., 330., 301., 303., 102., 201., 305., 104., 888., 202., 204.,
       402., 101., 205., 105., 203., 130., 198., 107., 403., 302., 404.,
       315., 405., 108., 401., 206., 208., 406., 110., 120., 210., 321.,
       109., 106., 410., 124., 304., 431.])

### doctdiab
- number of times respondent saw a health professional for diabetes in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining counts as numeric values

In [ ]:
features_df = features_df[features_df['doctdiab'] != 77]
features_df = features_df[features_df['doctdiab'] != 99]
features_df['doctdiab'].unique()

array([12.,  4., 88.,  5.,  1., 24.,  2.,  3.,  6.,  7.,  8., 20., 10.,
       15., 11., 76., 43., 14.,  9., 30., 58., 26., 25.])

### chkhemo3
- number of A1c checks in the past year
- remove `77` and `99` because they represent don't know / refused
- keep the remaining numeric counts so you can later convert this into at least twice per year vs less than twice

In [ ]:
features_df = features_df[features_df['chkhemo3'] != 77]
features_df = features_df[features_df['chkhemo3'] != 99]
features_df['chkhemo3'].unique()

array([ 2., 88.,  4.,  3.,  5.,  1.,  8.,  6., 12., 98.,  7., 10., 24.,
       20., 15., 76., 14., 11.])

### feetchk
- number of times respondent had their feet checked by a health professional in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining values as valid counts so this can later be recoded into annual foot check vs not annual foot check

In [ ]:
features_df = features_df[features_df['feetchk'] != 77]
features_df = features_df[features_df['feetchk'] != 99]
features_df['feetchk'].unique()

array([88.,  4.,  1.,  2.,  3.,  6.,  8., 74., 24., 12.,  7., 10.,  5.,
       11., 42., 15.,  9., 58.])

### eyeexam1
- how recently respondent had a dilated eye exam
- remove `7` and `9` because they represent don't know / refused
- keep the remaining categories so you can later convert this into annual exam vs not annual

In [ ]:
features_df = features_df[features_df['eyeexam1'] != 7]
features_df = features_df[features_df['eyeexam1'] != 9]
features_df['eyeexam1'].unique()

array([2., 3., 4., 1., 8.])

### menthlth
- number of bad mental health days in the past 30 days
- change `88` to `0` because BRFSS uses `88` for none
- remove `77` and `99` because they indicate don't know / refused
- keep this as a count variable from `0` to `30`

In [ ]:
features_df['menthlth'] = features_df['menthlth'].replace({88: 0})
features_df = features_df[features_df['menthlth'] != 77]
features_df = features_df[features_df['menthlth'] != 99]
features_df['menthlth'].unique()

array([ 0., 10.,  2., 15., 30.,  3.,  5.,  1., 20.,  7., 25., 12., 14.,
        4.,  6., 18., 26.,  8., 28., 21., 17., 24.])

### educa
- respondent education level
- remove `9` because it represents refused / missing
- keep the remaining categories as an ordinal education variable

In [ ]:
features_df = features_df[features_df['educa'] != 9]
features_df['educa'].unique()

array([6., 5., 4., 3., 2., 1.])

### x.ageg5yr
- respondent age group
- remove `14` because it corresponds to missing / refused rather than a real age group
- keep the remaining ordered age-group categories as valid responses

In [ ]:
features_df = features_df[features_df['x.ageg5yr'] != 14]
features_df['x.ageg5yr'].unique()

array([10,  6, 12,  9, 11,  5, 13,  8,  7,  1,  4,  3,  2])

### sex1
- whether respondent is male
- change `2` to `0` so female is `0` and male remains `1`
- this makes the variable binary and easier to interpret in modeling

In [ ]:
features_df['birthsex'] = features_df['birthsex'].replace({2: 0})
features_df['birthsex'].unique()

array([1., 0., 9.])

### marital
- respondent marital or partnered status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into married/partnered vs not married/partnered

In [ ]:
features_df = features_df[features_df['marital'] != 9]
features_df['marital'].unique()

array([2., 1., 3., 6., 5., 4.])

### employ1
- respondent employment status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into employed vs not employed

In [ ]:
features_df = features_df[features_df['employ1'] != 9]
features_df['employ1'].unique()

array([7., 4., 5., 8., 1., 2., 6., 3.])

### income2
- annual household income category
- remove `77` and `99` because they represent don't know / refused
- keep the remaining categories as an ordinal income variable

In [ ]:
features_df = features_df[features_df['income2'] != 77]
features_df = features_df[features_df['income2'] != 99]
features_df['income2'].unique()

array([7., 6., 5., 4., 8., 1., 3., 2.])

### x.urbstat
- whether respondent lives in an urban or rural county
- inspect values here because this is a derived variable
- if only valid categories are present, no additional cleaning is needed

In [ ]:
features_df['x.urbstat'].unique()

array([1., 2.])

### persdoc2
- whether respondent has at least one personal health care provider
- remove `7` and `9` because they represent don't know / refused
- keep the valid categories, then collapse later if you want at least one provider vs none

In [ ]:
features_df = features_df[features_df['persdoc2'] != 7]
features_df = features_df[features_df['persdoc2'] != 9]
features_df['persdoc2'].unique()

array([1., 3., 2.])

### hlthpln1
- whether respondent has any health care coverage
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no coverage is `0` and yes remains `1`

In [ ]:
features_df = features_df[features_df['hlthpln1'] != 7]
features_df = features_df[features_df['hlthpln1'] != 9]
features_df['hlthpln1'] = features_df['hlthpln1'].replace({2: 0})
features_df['hlthpln1'].unique()

array([1., 0.])

### addepev2
- whether respondent was ever told they had a depressive disorder
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [ ]:
features_df = features_df[features_df['addepev3'] != 7]
features_df = features_df[features_df['addepev3'] != 9]
features_df['addepev3'] = features_df['addepev3'].replace({2: 0})
features_df['addepev3'].unique()

array([0., 1.])

### diabete3
- remove `7` and `9` because they represent don't know / refused
- inspect the remaining diabetes-status values in the diabetes-management subset
- keep this as an inspection step rather than forcing the dataset to diagnosed diabetes only

In [ ]:
features_df = features_df[features_df['diabete4'] != 7]
features_df = features_df[features_df['diabete4'] != 9]
features_df.groupby(['diabete4']).size()

diabete4
1.0    976
dtype: int64

### diabage2
- respondent age when first told they had diabetes
- remove `98` and `99` because they represent don't know / refused
- keep the remaining values as a numeric age-at-diagnosis variable

In [ ]:
features_df = features_df[features_df['diabage3'] != 98]
features_df = features_df[features_df['diabage3'] != 99]
features_df['diabage3'].unique()

array([43., 38., 60., 52., 68., 78., 40., 37., 42., 30., 45., 50., 69.,
       71., 65., 75., 59.,  8., 81., 56., 66., 58., 67., 53., 73., 70.,
       46., 54., 51., 33., 55., 63., 64., 35., 62., 27., 44., 39., 72.,
       83., 48., 23., 49., 47., 28., 25., 31., 79., 16., 22., 20., 61.,
       32., 89., 12., 74., 80., 57.,  9., 34., 82., 94., 77., 76., 18.,
       19., 26., 41., 10., 24., 17., 36., 29., 21.,  5.])

### Rename Management Columns
- rename the cleaned diabetes-management variables to readable analysis names before EDA and export

In [ ]:
features_df = features_df.rename(columns={
    'diabedu': 'Diabetes_Class',
    'feetchk3': 'Foot_Self_Check_Freq',
    'bldsugar': 'Blood_Sugar_Check_Freq',
    'doctdiab': 'Doctor_Visit_Diabetes_Freq',
    'chkhemo3': 'A1C_Check_Freq',
    'feetchk': 'Professional_Foot_Check_Freq',
    'eyeexam1': 'Eye_Exam_Recency',
    'menthlth': 'Bad_Mental_Health_Days',
    'educa': 'Education',
    'x.ageg5yr': 'Age_Group',
    'sex1': 'Male',
    'marital': 'Marital_Status',
    'employ1': 'Employment_Status',
    'income2': 'Income',
    'x.urbstat': 'Urban_Rural_Status',
    'persdoc2': 'Personal_Doctor',
    'hlthpln1': 'Health_Coverage',
    'addepev2': 'Depressive_Disorder',
    'diabete3': 'Diabetes_Status',
    'diabage2': 'Diabetes_Age'
})

In [ ]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,birthsex,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,addepev3,diabete4,diabage3
67919,1.0,101.0,330.0,4.0,2.0,88.0,2.0,0.0,6.0,10,1.0,2.0,7.0,7.0,1.0,1.0,1.0,0.0,1.0,43.0
67928,1.0,301.0,301.0,88.0,88.0,88.0,3.0,10.0,5.0,6,0.0,1.0,4.0,6.0,1.0,1.0,0.0,1.0,1.0,38.0
67930,0.0,107.0,303.0,4.0,4.0,88.0,3.0,2.0,4.0,12,0.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,1.0,60.0
67940,1.0,101.0,102.0,4.0,4.0,4.0,3.0,15.0,5.0,9,0.0,3.0,7.0,4.0,1.0,3.0,0.0,0.0,1.0,52.0
67950,0.0,101.0,201.0,88.0,3.0,4.0,2.0,0.0,3.0,12,1.0,3.0,7.0,4.0,1.0,1.0,1.0,0.0,1.0,68.0

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [ ]:
features_df.shape

(944, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [ ]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,birthsex,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,addepev3,diabete4,diabage3
67919,1.0,101.0,330.0,4.0,2.0,88.0,2.0,0.0,6.0,10,1.0,2.0,7.0,7.0,1.0,1.0,1.0,0.0,1.0,43.0
67928,1.0,301.0,301.0,88.0,88.0,88.0,3.0,10.0,5.0,6,0.0,1.0,4.0,6.0,1.0,1.0,0.0,1.0,1.0,38.0
67930,0.0,107.0,303.0,4.0,4.0,88.0,3.0,2.0,4.0,12,0.0,1.0,5.0,5.0,1.0,1.0,1.0,0.0,1.0,60.0
67940,1.0,101.0,102.0,4.0,4.0,4.0,3.0,15.0,5.0,9,0.0,3.0,7.0,4.0,1.0,3.0,0.0,0.0,1.0,52.0
67950,0.0,101.0,201.0,88.0,3.0,4.0,2.0,0.0,3.0,12,1.0,3.0,7.0,4.0,1.0,1.0,1.0,0.0,1.0,68.0

In [ ]:
features_df.tail()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,birthsex,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,addepev3,diabete4,diabage3
76374,1.0,101.0,103.0,5.0,1.0,7.0,4.0,1.0,4.0,7,1.0,4.0,8.0,1.0,1.0,1.0,1.0,1.0,1.0,40.0
76378,0.0,102.0,102.0,2.0,1.0,1.0,8.0,0.0,4.0,7,1.0,2.0,1.0,6.0,1.0,1.0,1.0,0.0,1.0,50.0
76379,1.0,105.0,104.0,5.0,3.0,4.0,1.0,0.0,6.0,5,0.0,5.0,1.0,4.0,1.0,1.0,0.0,0.0,1.0,8.0
76397,1.0,888.0,102.0,3.0,1.0,1.0,2.0,0.0,4.0,13,1.0,3.0,8.0,6.0,1.0,1.0,1.0,0.0,1.0,48.0
76403,1.0,101.0,301.0,1.0,3.0,1.0,2.0,0.0,5.0,9,1.0,2.0,1.0,7.0,1.0,3.0,1.0,0.0,1.0,50.0

### Save Management Dataset
- save the cleaned diabetes module dataframe to CSV

In [ ]:
features_df.to_csv('2020_brfss_diabetes_module_features.csv', index=False)