# Getting Data

### Imports

In [1]:
import pandas as pd

### Define Your Path

In [2]:
# path = '/Users/absfolder/Dektop/Projects/'

### Survey Year

In [3]:
year = '2021'

### Load CSV

In [4]:
df = pd.read_csv(f'brfss{year}.csv')

### Dataset Shape

In [5]:
df.shape

(438693, 304)

### Display Settings

In [6]:
pd.set_option('display.max_columns', 500)
df.head()

,Unnamed: 0,x.state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,x.psu,ctelenm1,pvtresd1,colghous,statere1,celphon1,ladult1,colgsex,numadult,landsex,nummen,numwomen,respslct,safetime,ctelnum1,cellfon5,cadult1,cellsex,pvtresd3,cclghous,cstate1,landline,hhadult,sexvar,genhlth,physhlth,menthlth,poorhlth,priminsr,persdoc3,medcost1,checkup1,exerany2,bphigh6,bpmeds,cholchk3,toldhi3,cholmed3,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd3,addepev3,chckdny2,diabete4,diabage3,havarth5,arthexer,arthedu,lmtjoin3,arthdis2,joinpai2,marital,educa,renthom1,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income3,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,usenow3,ecignow1,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,flshtmy3,imfvpla2,pneuvac4,hivtst7,hivtstd3,fruit2,fruitju2,fvgreen1,frenchf1,potatoe1,vegetab2,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hpvadvc4,hpvadsht,tetanus1,shingle2,lcsfirst,lcslast,lcsnumcg,lcsctscn,hadmam,howlong,cervscrn,crvclcnc,crvclpap,crvclhpv,hadhyst2,psatest1,psatime1,pcpsars2,pcstalk,hadsigm4,colnsigm,colntes1,sigmtes1,lastsig4,colncncr,vircolo1,vclntes1,smalstol,stoltest,stooldn1,bldstfit,sdnates1,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,hombpchk,homrgchk,wherebp,sharebp,wtchsalt,dradvise,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvalzd,crgvper1,crgvhou1,crgvexpt,acedeprs,acedrink,acedrugs,aceprisn,acedivrc,acepunch,acehurt1,aceswear,acetouch,acetthem,acehvsex,aceadsaf,aceadned,marijan1,usemrjn3,rsnmrjn2,lastsmk2,stopsmk2,firearm5,gunload,loadulk2,rcsgendr,rcsrltn2,casthdx2,casthno2,birthsex,somale,sofemale,trnsgndr,qstver,qstlang,x.metstat,x.urbstat,mscode,x.ststr,x.strwt,x.rawrake,x.wt2rake,x.imprace,x.chispnc,x.crace1,x.cprace1,cageg,x.cllcpwt,x.dualuse,x.dualcor,x.llcpwt2,x.llcpwt,x.rfhlth,x.phys14d,x.ment14d,x.hlthpln,x.hcvu652,x.totinda,x.rfhype6,x.cholch3,x.rfchol3,x.michd,x.ltasth1,x.casthm1,x.asthms1,x.drdxar3,x.lmtact3,x.lmtwrk3,x.prace1,x.mrace1,x.hispanc,x.race,x.raceg21,x.racegr3,x.raceprv,x.sex,x.ageg5yr,x.age65yr,x.age80,x.age.g,htin4,htm4,wtkg3,x.bmi5,x.bmi5cat,x.rfbmi5,x.chldcnt,x.educag,x.incomg1,x.smoker3,x.rfsmok3,x.cureci1,drnkany5,drocdy3.,x.rfbing5,x.drnkwk1,x.rfdrhv7,x.flshot7,x.pneumo3,x.aidtst4,ftjuda2.,frutda2.,grenda1.,frnchda.,potada1.,vegeda2.,x.misfrt1,x.misveg1,x.frtres1,x.vegres1,x.frutsu1,x.vegesu1,x.frtlt1a,x.veglt1a,x.frt16a,x.veg23a,x.fruite1,x.vegete1
0,1,1,1,1192021,1,19,2021,1100,2021000001,2021000001,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,5.0,20.0,10.0,88.0,3.0,1.0,2.0,2.0,2.0,3.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,2.0,2.0,2.0,1.0,8.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,5.0,NaN,72.0,411.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,2.0,NaN,101.0,555.0,204.0,203.0,201.0,101.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,39.766158,2.0,79.532315,1,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,744.745531,2,3,2,1,9,2,1,1,2.0,2.0,2,2,1,1.0,2.0,1.0,1.0,1.0,2,1,1,1,1,2,11,2,70,6,59.0,150.0,3266.0,1454.0,1.0,1,1,2,3,3,1,1,2,0,1,0,1,1.0,1.0,2.0,0.0,100.0,57.0,43.0,14.0,100.0,0,0,1,1,100.0,214.0,1,1,1,1,0,0
1,2,1,1,1212021,1,21,2021,1100,2021000002,2021000002,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,1.0,98.0,1.0,1.0,2.0,1.0,1.0,10.0,9.0,6.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,77.0,NaN,7777.0,506.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,201.0,555.0,201.0,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,2.0,11011,39.766158,2.0,79.532315,2,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,299.137394,1,1,1,1,9,1,2,1,2.0,1.0,1,1,3,1.0,1.0,1.0,2.0,2.0,2,2,2,2,2,2,10,2,67,6,66.0,168.0,NaN,NaN,NaN,9,1,4,9,4,1,1,2,0,1,0,1,2.0,2.0,2.0,0.0,100.0,14.0,0.0,14.0,100.0,0,0,1,1,100.0,128.0,1,1,1,1,0,0
2,3,1,1,1212021,1,21,2021,1100,2021000003,2021000003,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,88.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,98.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,3.0,NaN,170.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,555.0,201.0,201.0,203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,39.766158,2.0,79.532315,2,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,587.862986,1,1,1,1,9,2,2,1,1.0,1.0,1,1,3,2.0,3.0,3.0,2.0,2.0,2,2,2,2,2,2,11,2,72,6,65.0,165.0,7711.0,2829.0,3.0,2,1,2,2,4,1,1,2,0,1,0,1,2.0,2.0,2.0,0.0,100.0,0.0,14.0,14.0,43.0,0,0,1,1,100.0,71.0,1,2,1,1,0,0
3,4,1,1,1172021,1,17,2021,1100,2021000004,2021000004,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,10.0,88.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,56.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,195.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,101.0,3.0,1.0,6.0,1.0,102020.0,1.0,2.0,2.0,NaN,203.0,205.0,303.0,204.0,308.0,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,3.0,11011,39.766158,2.0,79.532315,1,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,1099.621573,1,1,2,1,1,1,2,1,2.0,2.0,1,1,3,2.0,3.0,3.0,1.0,1.0,2,1,1,1,1,2,9,1,62,5,64.0,163.0,8845.0,3347.0,4.0,2,1,2,5,4,1,1,1,14,2,300,1,NaN,NaN,2.0,71.0,43.0,10.0,57.0,27.0,71.0,0,0,1,1,114.0,165.0,1,1,1,1,0,0
4,5,1,1,1152021,1,15,2021,1100,2021000005,2021000005,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5.0,30.0,88.0,30.0,3.0,1.0,2.0,1.0,1.0,4.0,NaN,2.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,65.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,2.0,NaN,8.0,2.0,8.0,88.0,4.0,NaN,206.0,511.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,1.0,777777.0,101.0,555.0,101.0,202.0,202.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,2.0,1.0,2.0,11011,39.766158,2.0,79.532315,6,9.0,NaN,NaN,NaN,NaN,9,NaN,2144.768999,1711.825866,2,3,1,1,9,1,1,1,2.0,1.0,1,1,3,2.0,3.0,3.0,1.0,7.0,2,7,2,4,7,1,12,2,76,6,71.0,180.0,9344.0,2873.0,3.0,2,1,1,2,4,1,1,2,0,1,0,1,1.0,1.0,1.0,0.0,100.0,100.0,29.0,29.0,100.0,0,0,1,1,100.0,258.0,1,1,1,1,0,0

### Feature List

In [7]:
features = [
    # Core Section 1: Health Status
    'genhlth',
    # Core Section 2: Healthy Days
    'physhlth',
    'menthlth',
    'poorhlth',
    # Core Section 3: Health Care Access
    'priminsr',
    'persdoc3',
    'medcost1',
    'checkup1',
    # Core Section 4: Exercise
    'exerany2',
    # Core Section 5: Hypertension Awareness
    'bphigh6',
    'bpmeds',
    # Core Section 6: Cholesterol Awareness
    'cholchk3',
    'toldhi3',
    'cholmed3',
    # Core Section 7: Chronic Health Conditions
    'cvdinfr4',
    'cvdcrhd4',
    'cvdstrk3',
    'asthma3',
    'asthnow',
    'chcscncr',
    'chcocncr',
    'chccopd3',
    'addepev3',
    'chckdny2',
    'diabete4',
    'diabage3',
    # Core Section 8: Arthritis
    'havarth5',
    'arthexer',
    'arthedu',
    'lmtjoin3',
    'arthdis2',
    'joinpai2',
    # Core Section 9: Demographics
    'x.ageg5yr',
    'x.hispanc',
    'x.mrace1',
    'x.prace1',
    'marital',
    'educa',
    'renthom1',
    'x.urbstat',
    'numhhol3',
    'numphon3',
    'cpdemo1b',
    'veteran3',
    'employ1',
    'children',
    'income3',
    'pregnant',
    'weight2',
    'height3',
    # Core Section 10: Disability
    'deaf',
    'blind',
    'decide',
    'diffwalk',
    'diffdres',
    'diffalon',
    # Core Section 11: Tobacco Use
    'smoke100',
    'smokday2',
    'usenow3',
    'ecignow1',
    # Core Section 12: Alcohol Consumption
    'alcday5',
    'avedrnk3',
    'drnk3ge5',
    'maxdrnks',
    # Core Section 13: Immunization
    'flushot7',
    'pneuvac4',
    # Core Section 14: H.I.V./AIDS
    'hivtst7',
    'hivtstd3',
    # Core Section 15: Fruits and Vegetables
    'fruit2',
    'fruitju2',
    'fvgreen1',
    'frenchf1',
    'potatoe1',
    'vegetab2',
    # Module 1: Prediabetes
    'pdiabtst',
    'prediab1',
    # Module 2: Diabetes
    'insulin1',
    'bldsugar',
    'feetchk3',
    'doctdiab',
    'chkhemo3',
    'feetchk',
    'eyeexam1',
    'diabeye',
    'diabedu',
    # Module 3: ME/CFS
    'toldcfs',
    'havecfs',
    'workcfs',
    # Module 4: Hepatitis Treatment 
    'toldhepc',
    'trethepc',
    'prirhepc',
    'havehepc',
    'havehepb',
    'medshepb',
    # Module 5: HPV - Vaccination
    'hpvadvc4',
    'hpvadsht',
    # Module 6: Tetanus Diphtheria (Tdap) (Adults)
    'tetanus1',
    # Module 7: Shingles Vaccination
    'shingle2',
    # Module 8: COVID Vaccination
    # 'covidvac',
    # 'covacget',
    # 'covidnum',
    # 'covidint',
    # 'covidfst',
    # 'covidsec',
    # Module 9: Lung Cancer Screening
    'lcsfirst',
    'lcslast',
    'lcsnumcg',
    'lcsctscn',
    # Module 10: Breast and Cervical Cancer Screening
    'hadmam',
    'howlong',
    'crvclcnc',
    'crvclpap',
    'crvclhpv',
    'hadhyst2',
    # Module 11: Prostate Cancer Screening
    'psatest1',
    'psatime1',
    'pcpsars2',
    'pcstalk',
    # Module 12: Colorectal Cancer Screening
    'hadsigm4',
    'colnsigm',
    'colntes1',
    'sigmtes1',
    'lastsig4',
    'colncncr',
    'vircolo1',
    'vclntes1',
    'smalstol',
    'stoltest',
    'stooldn1',
    'bldstfit',
    'sdnates1',
    # Module 13: Cancer Survivorship: Type of Cancer
    'cncrdiff',
    'cncrage',
    'cncrtyp1',
    # Module 14: Cancer Survivorship: Course of Treatment
    'csrvtrt3',
    'csrvdoc1',
    'csrvsum',
    'csrvrtrn',
    'csrvinst',
    'csrvinsr',
    'csrvdein',
    'csrvclin',
    # Module 15: Cancer Survivorship: Pain Management
    'csrvpain',
    'csrvctl2',
    # Module 16: Home/ Self-measured Blood Pressure
    'hombpchk',
    'homrgchk',
    'wherebp',
    'sharebp',
    # Module 17: Sodium or Salt-Related Behavior
    'wtchsalt',
    'dradvise',
    # Module 18: Cognitive Decline
    'cimemlos',
    'cdhouse',
    'cdassist',
    'cdhelp',
    'cdsocial',
    'cddiscus',
    # Module 19: Caregiver
    'caregiv1',
    'crgvrel4',
    'crgvlng1',
    'crgvhrs1',
    'crgvprb3',
    'crgvper1',
    'crgvhou1',
    'crgvexpt',
    # Module 21: Adverse Childhood Experiences
    # Module 21: Marijuana Use
    'marijan1',
    'usemrjn3',
    'rsnmrjn2',
    # Module 22: Tobacco Cessation
    'lastsmk2',
    'stopsmk2',
    # Module 23: Firearm Safety
    # Module 24: Industry and Occupation
    # Module 25: Random Child Selection
    'rcsgendr',
    'rcsrltn2',
    # Module 26: Childhood Asthma Prevalence
    # Module 27: Sex at Birth
    'birthsex',
    # Module 28: Sexual Orientation and Gender Identity (SOGI)
    'somale',
    'sofemale',
    'trnsgndr',
    'casthdx2',
    'casthno2',
    # Asthma Call-Back Permission Script
]

In [8]:
df_copy = df[features].copy()

### Analysis Shape

In [9]:
df_copy.shape

(438693, 171)

### Analysis Preview

In [10]:
df_copy.head()

,genhlth,physhlth,menthlth,poorhlth,priminsr,persdoc3,medcost1,checkup1,exerany2,bphigh6,bpmeds,cholchk3,toldhi3,cholmed3,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd3,addepev3,chckdny2,diabete4,diabage3,havarth5,arthexer,arthedu,lmtjoin3,arthdis2,joinpai2,x.ageg5yr,x.hispanc,x.mrace1,x.prace1,marital,educa,renthom1,x.urbstat,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income3,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,usenow3,ecignow1,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,pneuvac4,hivtst7,hivtstd3,fruit2,fruitju2,fvgreen1,frenchf1,potatoe1,vegetab2,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hpvadvc4,hpvadsht,tetanus1,shingle2,lcsfirst,lcslast,lcsnumcg,lcsctscn,hadmam,howlong,crvclcnc,crvclpap,crvclhpv,hadhyst2,psatest1,psatime1,pcpsars2,pcstalk,hadsigm4,colnsigm,colntes1,sigmtes1,lastsig4,colncncr,vircolo1,vclntes1,smalstol,stoltest,stooldn1,bldstfit,sdnates1,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,hombpchk,homrgchk,wherebp,sharebp,wtchsalt,dradvise,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvper1,crgvhou1,crgvexpt,marijan1,usemrjn3,rsnmrjn2,lastsmk2,stopsmk2,rcsgendr,rcsrltn2,birthsex,somale,sofemale,trnsgndr,casthdx2,casthno2
0,5.0,20.0,10.0,88.0,3.0,1.0,2.0,2.0,2.0,3.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,2.0,2.0,2.0,1.0,8.0,11,2,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,5.0,NaN,72.0,411.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,888.0,NaN,NaN,NaN,1.0,1.0,2.0,NaN,101.0,555.0,204.0,203.0,201.0,101.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,1.0,98.0,1.0,1.0,2.0,1.0,1.0,10.0,10,2,2.0,2.0,9.0,6.0,1.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,77.0,NaN,7777.0,506.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,2.0,2.0,NaN,101.0,555.0,201.0,555.0,201.0,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2.0,88.0,88.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,98.0,2.0,NaN,NaN,NaN,NaN,NaN,11,2,2.0,2.0,3.0,4.0,1.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,3.0,NaN,170.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,2.0,2.0,NaN,101.0,555.0,555.0,201.0,201.0,203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2.0,88.0,10.0,88.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,56.0,2.0,NaN,NaN,NaN,NaN,NaN,9,2,1.0,1.0,1.0,4.0,1.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,195.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,101.0,3.0,1.0,6.0,1.0,2.0,2.0,NaN,203.0,205.0,303.0,204.0,308.0,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,30.0,88.0,30.0,3.0,1.0,2.0,1.0,1.0,4.0,NaN,2.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,65.0,2.0,NaN,NaN,NaN,NaN,NaN,12,2,7.0,1.0,1.0,3.0,1.0,1.0,2.0,NaN,8.0,2.0,8.0,88.0,4.0,NaN,206.0,511.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,1.0,1.0,1.0,777777.0,101.0,555.0,101.0,202.0,202.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# Cleaning

## Core Section 1: Health Status

### genhlth
**Question:** Would you say that in general your health is excellent, very good, good, fair, or poor?
- `1` = Excellent
- `2` = Very Good
- `3` = Good
- `4` = Fair
- `5` = Poor
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [11]:
df_copy['genhlth'] = df_copy['genhlth'].replace([7, 9], pd.NA)
df_copy['genhlth'].value_counts(dropna=False)

genhlth
2.0     149112
3.0     137938
1.0      77741
4.0      54736
5.0      18005
<NA>      1157
NaN          4
Name: count, dtype: int64

## Core Section 2: Healthy Days

### physhlth
**Question:** For how many days during the past 30 days was your physical health not good?
- `1-30` = number of bad physical health days in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [12]:
df_copy['physhlth'] = df_copy['physhlth'].replace({88: 0})
df_copy['physhlth'] = df_copy['physhlth'].replace([77, 99], pd.NA)
df_copy['physhlth'].value_counts(dropna=False)

physhlth
0.0     287796
30.0     29732
2.0      22220
1.0      17063
3.0      12868
5.0      11642
<NA>      9491
10.0      8595
15.0      7623
4.0       6821
7.0       6695
20.0      4670
14.0      3994
6.0       1901
25.0      1866
8.0       1254
21.0       927
12.0       813
28.0       671
9.0        302
29.0       279
18.0       253
16.0       222
17.0       158
27.0       155
13.0       126
22.0       120
11.0       119
26.0       108
24.0        98
23.0        65
19.0        43
NaN          3
Name: count, dtype: int64

### menthlth
**Question:** For how many days during the past 30 days was your mental health not good?
- `1-30` = number of bad mental health days in past 30 days
- `77` = Don't know / Not sure
- `88` = None
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [13]:
df_copy['menthlth'] = df_copy['menthlth'].replace({88: 0})
df_copy['menthlth'] = df_copy['menthlth'].replace([77, 99], pd.NA)
df_copy['menthlth'].value_counts(dropna=False)

menthlth
0.0     271161
30.0     24953
2.0      22717
5.0      19130
3.0      14567
10.0     14554
15.0     13475
1.0      13091
20.0      7993
<NA>      7915
7.0       7428
4.0       7419
25.0      2954
14.0      2722
6.0       2227
8.0       1565
12.0      1082
28.0       819
21.0       516
29.0       400
18.0       289
9.0        252
16.0       230
27.0       208
17.0       198
13.0       160
22.0       159
11.0       134
24.0       128
26.0       116
23.0       102
19.0        27
NaN          2
Name: count, dtype: int64

### poorhlth
**Question:** During the past 30 days, for how many days did poor physical or mental health keep you from doing your usual activities?
- `1-30` = number of days poor physical or mental health kept respondent from usual activities in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [14]:
df_copy['poorhlth'] = df_copy['poorhlth'].replace({88: 0})
df_copy['poorhlth'] = df_copy['poorhlth'].replace([77, 99], pd.NA)
df_copy['poorhlth'].value_counts(dropna=False)

poorhlth
NaN     205279
0.0     124793
30.0     17822
2.0      13115
1.0      10760
5.0      10293
10.0      8622
15.0      8603
3.0       8481
<NA>      5307
20.0      5192
7.0       5017
4.0       4744
14.0      2610
25.0      1841
6.0       1555
8.0       1175
12.0       810
21.0       607
28.0       420
9.0        228
18.0       199
16.0       163
29.0       161
17.0       138
27.0       124
22.0       122
13.0       116
11.0       115
26.0        90
24.0        81
23.0        74
19.0        36
Name: count, dtype: int64

## Core Section 3: Health Care Access

### x.hlthpln
**Question:** Do you have any kind of health care coverage?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [15]:
df_copy['priminsr'] = df_copy['priminsr'].replace({2: 0})
df_copy['priminsr'] = df_copy['priminsr'].replace([7, 9], pd.NA)
df_copy['priminsr'].value_counts(dropna=False)

priminsr
1.0     164977
3.0     130464
0.0      35887
5.0      27526
<NA>     25688
88.0     23215
10.0     11463
77.0      9340
99.0      8054
8.0       1462
4.0        478
6.0        136
NaN          3
Name: count, dtype: int64

### persdoc3
**Question:** Do you have one person you think of as your personal doctor or health care provider, more than one, or none?
- `1` = Yes, only one personal doctor
- `2` = More than one
- `3` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [16]:
df_copy['persdoc3'] = df_copy['persdoc3'].replace([7, 9], pd.NA)
df_copy['persdoc3'].value_counts(dropna=False)

persdoc3
1.0     257955
2.0     124323
3.0      52710
<NA>      3703
NaN          2
Name: count, dtype: int64

### medcost1
**Question:** Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [17]:
df_copy['medcost1'] = df_copy['medcost1'].replace({2: 0})
df_copy['medcost1'] = df_copy['medcost1'].replace([7, 9], pd.NA)
df_copy['medcost1'].value_counts(dropna=False)

medcost1
0.0     404732
1.0      32597
<NA>      1359
NaN          5
Name: count, dtype: int64

### checkup1
**Question:** About how long has it been since you last visited a doctor for a routine checkup?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 5 years
- `4` = 5 or more years ago
- `7` = Don't know / Not sure
- `8` = Never
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [18]:
df_copy['checkup1'] = df_copy['checkup1'].replace([7, 9], pd.NA)
df_copy['checkup1'].value_counts(dropna=False)

checkup1
1.0     337289
2.0      51271
3.0      23427
4.0      18490
<NA>      5903
8.0       2311
NaN          2
Name: count, dtype: int64

## Core Section 4: Exercise

### exerany2
**Question:** During the past month, other than your regular job, did you participate in any physical activities or exercises?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [19]:
df_copy['exerany2'] = df_copy['exerany2'].replace({2: 0})
df_copy['exerany2'] = df_copy['exerany2'].replace([7, 9], pd.NA)
df_copy['exerany2'].value_counts(dropna=False)

exerany2
1.0     330738
0.0     107027
<NA>       926
NaN          2
Name: count, dtype: int64

## Core Section 5: Hypertension Awareness

### bphigh6
**Question:** What is the respondent's high blood pressure status?
- `1` = Yes
- `2` = Yes, but female told only during pregnancy
- `3` = No
- `4` = Told borderline high or pre-hypertensive or elevated blood pressure
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [20]:
df_copy['bphigh6'] = df_copy['bphigh6'].replace([7, 9], pd.NA)
df_copy['bphigh6'].value_counts(dropna=False)

bphigh6
3.0     256603
1.0     172133
4.0       4571
2.0       3474
<NA>      1910
NaN          2
Name: count, dtype: int64

### bpmeds
**Question:** What is the respondent's status for taking prescription medicine for high blood pressure?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [21]:
df_copy['bpmeds'] = df_copy['bpmeds'].replace({2: 0})
df_copy['bpmeds'] = df_copy['bpmeds'].replace([7, 9], pd.NA)
df_copy['bpmeds'].value_counts(dropna=False)

bpmeds
NaN     266560
1.0     142417
0.0      29257
<NA>       459
Name: count, dtype: int64

## Core Section 6: Cholesterol Awareness

### cholchk3
**Question:** What is the respondent's cholesterol check recency?
- `1` = Never
- `2` = Within the past year
- `3` = Within the past 2 years
- `4` = Within the past 3 years
- `5` = Within the past 4 years
- `6` = Within the past 5 years
- `8` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [22]:
df_copy['cholchk3'] = df_copy['cholchk3'].replace([7, 9], pd.NA)
df_copy['cholchk3'].value_counts(dropna=False)

cholchk3
2.0     289789
3.0      48223
1.0      31369
<NA>     29780
4.0      15422
8.0      13540
5.0       5543
6.0       5025
NaN          2
Name: count, dtype: int64

### toldhi3
**Question:** What is the respondent's status for told has high cholesterol?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [23]:
df_copy['toldhi3'] = df_copy['toldhi3'].replace({2: 0})
df_copy['toldhi3'] = df_copy['toldhi3'].replace([7, 9], pd.NA)
df_copy['toldhi3'].value_counts(dropna=False)

toldhi3
0.0     224989
1.0     149724
NaN      60836
<NA>      3144
Name: count, dtype: int64

### cholmed3
**Question:** What is the respondent's status for taking medicine for cholesterol?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [24]:
df_copy['cholmed3'] = df_copy['cholmed3'].replace({2: 0})
df_copy['cholmed3'] = df_copy['cholmed3'].replace([7, 9], pd.NA)
df_copy['cholmed3'].value_counts(dropna=False)

cholmed3
0.0     260185
1.0     115053
NaN      61571
<NA>      1884
Name: count, dtype: int64

## Core Section 7: Chronic Health Conditions

### cvdinfr4
**Question:** What is the respondent's status for heart attack?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [25]:
df_copy['cvdinfr4'] = df_copy['cvdinfr4'].replace({2: 0})
df_copy['cvdinfr4'] = df_copy['cvdinfr4'].replace([7, 9], pd.NA)
df_copy['cvdinfr4'].value_counts(dropna=False)

cvdinfr4
0.0     413207
1.0      22831
<NA>      2653
NaN          2
Name: count, dtype: int64

### cvdcrhd4
**Question:** What is the respondent's status for coronary heart disease?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [26]:
df_copy['cvdcrhd4'] = df_copy['cvdcrhd4'].replace({2: 0})
df_copy['cvdcrhd4'] = df_copy['cvdcrhd4'].replace([7, 9], pd.NA)
df_copy['cvdcrhd4'].value_counts(dropna=False)

cvdcrhd4
0.0     411527
1.0      22891
<NA>      4273
NaN          2
Name: count, dtype: int64

### cvdstrk3
**Question:** What is the respondent's status for stroke?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [27]:
df_copy['cvdstrk3'] = df_copy['cvdstrk3'].replace({2: 0})
df_copy['cvdstrk3'] = df_copy['cvdstrk3'].replace([7, 9], pd.NA)
df_copy['cvdstrk3'].value_counts(dropna=False)

cvdstrk3
0.0     420051
1.0      17213
<NA>      1427
NaN          2
Name: count, dtype: int64

### asthma3
**Question:** What is the respondent's status for ever asthma?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [28]:
df_copy['asthma3'] = df_copy['asthma3'].replace({2: 0})
df_copy['asthma3'] = df_copy['asthma3'].replace([7, 9], pd.NA)
df_copy['asthma3'].value_counts(dropna=False)

asthma3
0.0     375445
1.0      61502
<NA>      1744
NaN          2
Name: count, dtype: int64

### asthnow
**Question:** What is the respondent's status for current asthma?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [29]:
df_copy['asthnow'] = df_copy['asthnow'].replace({2: 0})
df_copy['asthnow'] = df_copy['asthnow'].replace([7, 9], pd.NA)
df_copy['asthnow'].value_counts(dropna=False)

asthnow
NaN     377191
1.0      42660
0.0      17030
<NA>      1812
Name: count, dtype: int64

### chcscncr
**Question:** What is the respondent's status for skin cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [30]:
df_copy['chcscncr'] = df_copy['chcscncr'].replace({2: 0})
df_copy['chcscncr'] = df_copy['chcscncr'].replace([7, 9], pd.NA)
df_copy['chcscncr'].value_counts(dropna=False)

chcscncr
0.0     396140
1.0      41112
<NA>      1439
NaN          2
Name: count, dtype: int64

### chcocncr
**Question:** What is the respondent's status for other cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [31]:
df_copy['chcocncr'] = df_copy['chcocncr'].replace({2: 0})
df_copy['chcocncr'] = df_copy['chcocncr'].replace([7, 9], pd.NA)
df_copy['chcocncr'].value_counts(dropna=False)

chcocncr
0.0     394980
1.0      42349
<NA>      1361
NaN          3
Name: count, dtype: int64

### chccopd3
**Question:** What is the respondent's status for copd?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [32]:
df_copy['chccopd3'] = df_copy['chccopd3'].replace({2: 0})
df_copy['chccopd3'] = df_copy['chccopd3'].replace([7, 9], pd.NA)
df_copy['chccopd3'].value_counts(dropna=False)

chccopd3
0.0     402417
1.0      34169
<NA>      2104
NaN          3
Name: count, dtype: int64

### addepev3
**Question:** What is the respondent's status for depressive disorder?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [33]:
df_copy['addepev3'] = df_copy['addepev3'].replace({2: 0})
df_copy['addepev3'] = df_copy['addepev3'].replace([7, 9], pd.NA)
df_copy['addepev3'].value_counts(dropna=False)

addepev3
0.0     350778
1.0      85398
<NA>      2514
NaN          3
Name: count, dtype: int64

### chckdny2
**Question:** What is the respondent's status for kidney disease?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [34]:
df_copy['chckdny2'] = df_copy['chckdny2'].replace({2: 0})
df_copy['chckdny2'] = df_copy['chckdny2'].replace([7, 9], pd.NA)
df_copy['chckdny2'].value_counts(dropna=False)

chckdny2
0.0     419779
1.0      17101
<NA>      1810
NaN          3
Name: count, dtype: int64

### diabete4
**Question:** What is the respondent's diabetes status?
- `1` = Yes
- `2` = Yes, but female told only during pregnancy
- `3` = No
- `4` = No, pre-diabetes or borderline diabetes
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [35]:
df_copy['diabete4'] = df_copy['diabete4'].replace([7, 9], pd.NA)
df_copy['diabete4'].value_counts(dropna=False)

diabete4
3.0     366342
1.0      57616
4.0       9942
2.0       3808
<NA>       982
NaN          3
Name: count, dtype: int64

### diabage3
**Question:** What is the respondent's diabetes age?
- `1-97` = age in years (`97` means 97 or older)
- `98` = Don't know / Not sure
- `99` = Refused
- cleaning: set `98` and `99` to `pd.NA`

In [36]:
df_copy['diabage3'] = df_copy['diabage3'].replace([98, 99], pd.NA)
df_copy['diabage3'].value_counts(dropna=False)

diabage3
NaN     381078
50.0      5398
<NA>      4671
60.0      3936
55.0      3395
         ...
97.0         2
96.0         2
94.0         2
93.0         2
91.0         1
Name: count, Length: 99, dtype: int64

## Core Section 8: Arthritis

### havarth5
**Question:** What is the respondent's status for arthritis?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [37]:
df_copy['havarth5'] = df_copy['havarth5'].replace({2: 0})
df_copy['havarth5'] = df_copy['havarth5'].replace([7, 9], pd.NA)
df_copy['havarth5'].value_counts(dropna=False)

havarth5
0.0     293256
1.0     142541
<NA>      2893
NaN          3
Name: count, dtype: int64

## Core Section 9: Demographics

### x.ageg5yr
**Question:** What is the respondent's age group?
- `1` = Age 18 to 24
- `2` = Age 25 to 29
- `3` = Age 30 to 34
- `4` = Age 35 to 39
- `5` = Age 40 to 44
- `6` = Age 45 to 49
- `7` = Age 50 to 54
- `8` = Age 55 to 59
- `9` = Age 60 to 64
- `10` = Age 65 to 69
- `11` = Age 70 to 74
- `12` = Age 75 to 79
- `13` = Age 80 or older
- `14` = Don't know / Refused / Missing
- cleaning: set `14` to `pd.NA`

In [38]:
df_copy['x.ageg5yr'] = df_copy['x.ageg5yr'].replace([14], pd.NA)
df_copy['x.ageg5yr'].value_counts(dropna=False)

x.ageg5yr
10      45762
9       44298
11      42920
8       38009
13      34507
7       34086
12      29747
5       29435
4       28559
6       28391
1       26025
3       25724
2       21623
<NA>     9607
Name: count, dtype: int64

### x.hispanc
**Question:** What is the respondent's status for hispanic?
- `1` = Hispanic
- `2` = Not Hispanic
- `9` = Refused
- cleaning: recode `2 -> 0`; set `9` to `pd.NA`

In [39]:
df_copy['x.hispanc'] = df_copy['x.hispanc'].replace({2: 0})
df_copy['x.hispanc'] = df_copy['x.hispanc'].replace([9], pd.NA)
df_copy['x.hispanc'].value_counts(dropna=False)

x.hispanc
0       394360
1        38396
<NA>      5937
Name: count, dtype: int64

### x.mrace1
**Question:** What is the respondent's status for race multi select?
- `1` = White only
- `2` = Black only
- `3` = American Indian or Alaska Native only
- `4` = Asian only
- `5` = Native Hawaiian or other Pacific Islander only
- `6` = Other race only
- `7` = Multiracial
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [40]:
df_copy['x.mrace1'] = df_copy['x.mrace1'].replace([77, 99], pd.NA)
df_copy['x.mrace1'].value_counts(dropna=False)

x.mrace1
1.0     344097
2.0      34938
<NA>     13359
6.0      12838
4.0      11756
7.0      10542
3.0       8761
5.0       2398
NaN          4
Name: count, dtype: int64

### x.prace1
**Question:** What is the respondent's status for race best represents?
- `1` = White
- `2` = Black or African American
- `3` = American Indian or Alaska Native
- `4` = Asian
- `5` = Native Hawaiian or other Pacific Islander
- `6` = Other race
- `7` = Multiracial / best represented by another race code
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [41]:
df_copy['x.prace1'] = df_copy['x.prace1'].replace([77, 99], pd.NA)
df_copy['x.prace1'].value_counts(dropna=False)

x.prace1
1.0     348344
2.0      36308
6.0      13849
<NA>     13359
4.0      12546
3.0       9685
5.0       3220
7.0       1372
8.0          6
NaN          4
Name: count, dtype: int64

### marital
**Question:** What is the respondent's marital status?
- `1` = Married
- `2` = Divorced
- `3` = Widowed
- `4` = Separated
- `5` = Never married
- `6` = A member of an unmarried couple
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [42]:
df_copy['marital'] = df_copy['marital'].replace([9], pd.NA)
df_copy['marital'].value_counts(dropna=False)

marital
1.0     227242
5.0      77554
2.0      55677
3.0      47275
6.0      17524
4.0       8433
<NA>      4983
NaN          5
Name: count, dtype: int64

### educa
**Question:** What is the respondent's status for education?
- `1` = Never attended school or only kindergarten
- `2` = Grades 1 through 8
- `3` = Grades 9 through 11
- `4` = Grade 12 or GED
- `5` = College 1 year to 3 years
- `6` = College 4 years or more
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [43]:
df_copy['educa'] = df_copy['educa'].replace([9], pd.NA)
df_copy['educa'].value_counts(dropna=False)

educa
6.0     178577
5.0     120102
4.0     111545
3.0      17126
2.0       8259
<NA>      2473
1.0        606
NaN          5
Name: count, dtype: int64

### renthom1
**Question:** What is the respondent's status for own or rent?
- `1` = Own
- `2` = Rent
- `3` = Other arrangement
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [44]:
df_copy['renthom1'] = df_copy['renthom1'].replace([7, 9], pd.NA)
df_copy['renthom1'].value_counts(dropna=False)

renthom1
1.0     308963
2.0     103944
3.0      21187
<NA>      4591
NaN          8
Name: count, dtype: int64

### x.urbstat
**Question:** Does the respondent live in an urban county or a rural county?
- `1` = Urban county
- `2` = Rural county
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [45]:
df_copy['x.urbstat'] = df_copy['x.urbstat'].replace([7, 9, 77, 99], pd.NA)
df_copy['x.urbstat'].value_counts(dropna=False)

x.urbstat
1.0    369461
2.0     62178
NaN      7054
Name: count, dtype: int64

### numhhol3
**Question:** What is the respondent's status for multiple phones in household?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [46]:
df_copy['numhhol3'] = df_copy['numhhol3'].replace({2: 0})
df_copy['numhhol3'] = df_copy['numhhol3'].replace([7, 9], pd.NA)
df_copy['numhhol3'].value_counts(dropna=False)

numhhol3
NaN     320910
0.0      84780
1.0      31815
<NA>      1188
Name: count, dtype: int64

### numphon3
**Question:** What is the respondent's status for residential phones?
- `1-5` = Enter number of residential phones
- `6` = 6 or more
- `7` = Don't know / Not sure
- `8` = None
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [47]:
df_copy['numphon3'] = df_copy['numphon3'].replace([7, 9], pd.NA)
df_copy['numphon3'].value_counts(dropna=False)

numphon3
NaN     406880
1.0      20557
2.0       7150
3.0       2128
<NA>      1049
8.0        437
4.0        298
5.0        112
6.0         82
Name: count, dtype: int64

### cpdemo1b
**Question:** What is the respondent's status for personal cell phones?
- `1-5` = Enter number of personal cell phones
- `6` = 6 or more
- `7` = Don't know / Not sure
- `8` = None
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [48]:
df_copy['cpdemo1b'] = df_copy['cpdemo1b'].replace([7, 9], pd.NA)
df_copy['cpdemo1b'].value_counts(dropna=False)

cpdemo1b
1.0     372708
2.0      35754
8.0      16047
<NA>      6132
3.0       4615
4.0       1976
5.0        734
6.0        435
NaN        292
Name: count, dtype: int64

### veteran3
**Question:** What is the respondent's veteran status?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [49]:
df_copy['veteran3'] = df_copy['veteran3'].replace({2: 0})
df_copy['veteran3'] = df_copy['veteran3'].replace([7, 9], pd.NA)
df_copy['veteran3'].value_counts(dropna=False)

veteran3
0.0     382958
1.0      52518
NaN       1636
<NA>      1581
Name: count, dtype: int64

### employ1
**Question:** What is the respondent's employment status?
- `1` = Employed for wages
- `2` = Self-employed
- `3` = Out of work for 1 year or more
- `4` = Out of work for less than 1 year
- `5` = A homemaker
- `6` = A student
- `7` = Retired
- `8` = Unable to work
- `9` = Refused
- cleaning: set `9` to `pd.NA`

In [50]:
df_copy['employ1'] = df_copy['employ1'].replace([9], pd.NA)
df_copy['employ1'].value_counts(dropna=False)

employ1
1.0     186076
7.0     131546
2.0      37759
8.0      25702
5.0      17579
3.0      11406
6.0      10661
4.0       9713
<NA>      4663
NaN       3588
Name: count, dtype: int64

### children
**Question:** What is the respondent's status for children in household?
- `0-87` = number of children younger than 18 in the household
- `88` = None
- `99` = Refused
- cleaning: recode `88 -> 0`; set `99` to `pd.NA`

In [51]:
df_copy['children'] = df_copy['children'].replace({88: 0})
df_copy['children'] = df_copy['children'].replace([99], pd.NA)
df_copy['children'].value_counts(dropna=False)

children
0.0     317258
1.0      46250
2.0      38985
3.0      16345
NaN       6135
4.0       5982
<NA>      4560
5.0       1917
6.0        733
7.0        288
8.0        107
9.0         51
10.0        30
11.0         8
12.0         8
14.0         5
15.0         5
13.0         5
20.0         4
83.0         3
23.0         2
16.0         2
17.0         2
75.0         1
82.0         1
21.0         1
80.0         1
18.0         1
32.0         1
55.0         1
81.0         1
Name: count, dtype: int64

### income3
**Question:** What is the respondent's status for income?
- `1` = Less than $10,000
- `2` = $10,000 to less than $15,000
- `3` = $15,000 to less than $20,000
- `4` = $20,000 to less than $25,000
- `5` = $25,000 to less than $35,000
- `6` = $35,000 to less than $50,000
- `7` = $50,000 to less than $75,000
- `8` = $75,000 or more
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [52]:
df_copy['income3'] = df_copy['income3'].replace([77, 99], pd.NA)
df_copy['income3'].value_counts(dropna=False)

income3
<NA>    85566
7.0     59408
6.0     48339
8.0     47838
9.0     47642
5.0     43893
4.0     21071
10.0    19769
11.0    18952
3.0     14960
2.0     11530
1.0     10878
NaN      8847
Name: count, dtype: int64

### pregnant
**Question:** What is the respondent's status for pregnant?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [53]:
df_copy['pregnant'] = df_copy['pregnant'].replace({2: 0})
df_copy['pregnant'] = df_copy['pregnant'].replace([7, 9], pd.NA)
df_copy['pregnant'].value_counts(dropna=False)

pregnant
NaN     358021
0.0      77679
1.0       2368
<NA>       625
Name: count, dtype: int64

### weight2
**Question:** What is the respondent's status for weight?
- recorded weight code from BRFSS
- `7777` = Don't know / Not sure
- `9999` = Refused
- cleaning: set `7777` and `9999` to `pd.NA`

In [54]:
df_copy['weight2'] = df_copy['weight2'].replace([7777, 9999], pd.NA)
df_copy['weight2'].value_counts(dropna=False)

weight2
<NA>      28759
200.0     21458
180.0     19506
150.0     17451
160.0     17282
          ...
9025.0        1
602.0         1
469.0         1
421.0         1
9042.0        1
Name: count, Length: 587, dtype: int64

### height3
**Question:** What is the respondent's status for height?
- recorded height code from BRFSS
- `7777` = Don't know / Not sure
- `9999` = Refused
- cleaning: set `7777` and `9999` to `pd.NA`

In [55]:
df_copy['height3'] = df_copy['height3'].replace([7777, 9999], pd.NA)
df_copy['height3'].value_counts(dropna=False)

height3
506.0     36795
504.0     35413
507.0     33030
505.0     32282
510.0     31798
          ...
9136.0        1
9198.0        1
9138.0        1
9197.0        1
9199.0        1
Name: count, Length: 142, dtype: int64

## Core Section 10: Disability

### deaf
**Question:** What is the respondent's status for deaf or serious hearing difficulty?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [56]:
df_copy['deaf'] = df_copy['deaf'].replace({2: 0})
df_copy['deaf'] = df_copy['deaf'].replace([7, 9], pd.NA)
df_copy['deaf'].value_counts(dropna=False)

deaf
0.0     384717
1.0      37578
NaN      14602
<NA>      1796
Name: count, dtype: int64

### blind
**Question:** What is the respondent's status for blind or serious vision difficulty?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [57]:
df_copy['blind'] = df_copy['blind'].replace({2: 0})
df_copy['blind'] = df_copy['blind'].replace([7, 9], pd.NA)
df_copy['blind'].value_counts(dropna=False)

blind
0.0     399597
1.0      21745
NaN      15744
<NA>      1607
Name: count, dtype: int64

### decide
**Question:** What is the respondent's status for serious difficulty decisions?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [58]:
df_copy['decide'] = df_copy['decide'].replace({2: 0})
df_copy['decide'] = df_copy['decide'].replace([7, 9], pd.NA)
df_copy['decide'].value_counts(dropna=False)

decide
0.0     372376
1.0      46337
NaN      16843
<NA>      3137
Name: count, dtype: int64

### diffwalk
**Question:** What is the respondent's status for serious difficulty walking?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [59]:
df_copy['diffwalk'] = df_copy['diffwalk'].replace({2: 0})
df_copy['diffwalk'] = df_copy['diffwalk'].replace([7, 9], pd.NA)
df_copy['diffwalk'].value_counts(dropna=False)

diffwalk
0.0     351306
1.0      67557
NaN      18009
<NA>      1821
Name: count, dtype: int64

### diffdres
**Question:** What is the respondent's status for serious difficulty dressing?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [60]:
df_copy['diffdres'] = df_copy['diffdres'].replace({2: 0})
df_copy['diffdres'] = df_copy['diffdres'].replace([7, 9], pd.NA)
df_copy['diffdres'].value_counts(dropna=False)

diffdres
0.0     401965
NaN      18786
1.0      17012
<NA>       930
Name: count, dtype: int64

### diffalon
**Question:** What is the respondent's status for serious difficulty doing errands?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [61]:
df_copy['diffalon'] = df_copy['diffalon'].replace({2: 0})
df_copy['diffalon'] = df_copy['diffalon'].replace([7, 9], pd.NA)
df_copy['diffalon'].value_counts(dropna=False)

diffalon
0.0     386212
1.0      31056
NaN      19853
<NA>      1572
Name: count, dtype: int64

## Core Section 11: Tobacco Use

### smoke100
**Question:** What is the respondent's status for smoked 100 cigarettes?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [62]:
df_copy['smoke100'] = df_copy['smoke100'].replace({2: 0})
df_copy['smoke100'] = df_copy['smoke100'].replace([7, 9], pd.NA)
df_copy['smoke100'].value_counts(dropna=False)

smoke100
0.0     246644
1.0     167588
NaN      21232
<NA>      3229
Name: count, dtype: int64

### smokday2
**Question:** What is the respondent's smoke frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [63]:
df_copy['smokday2'] = df_copy['smokday2'].replace([7, 9], pd.NA)
df_copy['smokday2'].value_counts(dropna=False)

smokday2
NaN     271240
3.0     113247
1.0      38913
2.0      14919
<NA>       374
Name: count, dtype: int64

### usenow3
**Question:** What is the respondent's smokeless tobacco frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [64]:
df_copy['usenow3'] = df_copy['usenow3'].replace([7, 9], pd.NA)
df_copy['usenow3'].value_counts(dropna=False)

usenow3
3.0     402556
NaN      21989
1.0       7769
2.0       5486
<NA>       893
Name: count, dtype: int64

### ecignow1
**Question:** What is the respondent's e cigarette frequency?
- `1` = Every day
- `2` = Some days
- `3` = Not at all
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [65]:
df_copy['ecignow1'] = df_copy['ecignow1'].replace([7, 9], pd.NA)
df_copy['ecignow1'].value_counts(dropna=False)

ecignow1
3.0     311502
4.0      83907
NaN      23025
2.0      10296
1.0       9050
<NA>       913
Name: count, dtype: int64

## Core Section 12: Alcohol Consumption

### alcday5
**Question:** What is the respondent's alcohol frequency?
- first digit is the time unit:
- `1xx` = days per week
- `2xx` = days in past 30 days
- `777` = Don't know / Not sure
- `888` = No drinks in past 30 days
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [66]:
df_copy['alcday5'] = df_copy['alcday5'].replace([777, 999], pd.NA)
df_copy['alcday5'].value_counts(dropna=False)

alcday5
888.0    196872
201.0     32386
202.0     24986
NaN       24487
101.0     18087
230.0     15352
203.0     14358
102.0     13097
204.0     11801
205.0     11780
210.0      9528
103.0      8989
215.0      7441
220.0      7313
107.0      6744
<NA>       6102
206.0      4218
104.0      4193
105.0      3960
208.0      3550
225.0      3119
207.0      3078
212.0      1940
106.0      1316
228.0       920
214.0       594
229.0       365
209.0       280
227.0       244
216.0       243
224.0       240
221.0       233
218.0       229
222.0       177
226.0       157
217.0        95
213.0        82
223.0        72
211.0        49
219.0        16
Name: count, dtype: int64

### avedrnk3
**Question:** What is the respondent's average drinks?
- `1-76` = average number of drinks
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [67]:
df_copy['avedrnk3'] = df_copy['avedrnk3'].replace([77, 99], pd.NA)
df_copy['avedrnk3'].value_counts(dropna=False)

avedrnk3
NaN     228271
1.0      91833
2.0      61810
3.0      24451
4.0      10392
5.0       5693
6.0       4936
<NA>      3594
10.0      1579
88.0      1471
8.0       1421
7.0        940
12.0       907
15.0       356
20.0       194
9.0        187
30.0       160
24.0        70
18.0        64
16.0        52
13.0        46
14.0        46
11.0        40
25.0        39
76.0        19
40.0        17
60.0        16
50.0        12
17.0        11
48.0         7
35.0         6
32.0         5
36.0         5
56.0         4
45.0         4
28.0         4
55.0         3
70.0         3
19.0         3
23.0         3
22.0         2
21.0         2
29.0         2
65.0         2
27.0         2
34.0         1
74.0         1
42.0         1
31.0         1
62.0         1
26.0         1
37.0         1
58.0         1
75.0         1
Name: count, dtype: int64

### drnk3ge5
**Question:** What is the respondent's binge drinking frequency?
- `1-76` = number of times
- `77` = Don't know / Not sure
- `88` = None
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [68]:
df_copy['drnk3ge5'] = df_copy['drnk3ge5'].replace([77, 99], pd.NA)
df_copy['drnk3ge5'].value_counts(dropna=False)

drnk3ge5
NaN     228868
88.0    152738
1.0      18827
2.0      10823
3.0       5037
4.0       4796
5.0       3752
<NA>      3326
30.0      2144
10.0      1891
6.0       1387
8.0       1259
15.0       997
7.0        808
20.0       722
12.0       401
25.0       241
9.0         94
28.0        93
14.0        88
16.0        80
29.0        45
27.0        31
26.0        30
18.0        26
13.0        25
11.0        25
24.0        23
17.0        22
21.0        20
23.0        15
22.0        14
76.0        13
31.0         6
19.0         6
55.0         4
40.0         4
74.0         1
41.0         1
45.0         1
70.0         1
60.0         1
34.0         1
37.0         1
75.0         1
50.0         1
52.0         1
43.0         1
35.0         1
Name: count, dtype: int64

### maxdrnks
**Question:** What is the respondent's status for max drinks?
- `1-76` = maximum number of drinks
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [69]:
df_copy['maxdrnks'] = df_copy['maxdrnks'].replace([77, 99], pd.NA)
df_copy['maxdrnks'].value_counts(dropna=False)

maxdrnks
NaN     229430
1.0      56620
2.0      53954
3.0      32355
4.0      17189
         ...
53.0         1
72.0         1
29.0         1
44.0         1
66.0         1
Name: count, Length: 61, dtype: int64

## Core Section 13: Immunization

### flushot7
**Question:** What is the respondent's status for flu shot?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [70]:
df_copy['flushot7'] = df_copy['flushot7'].replace({2: 0})
df_copy['flushot7'] = df_copy['flushot7'].replace([7, 9], pd.NA)
df_copy['flushot7'].value_counts(dropna=False)

flushot7
1.0     212164
0.0     195137
NaN      27648
<NA>      3744
Name: count, dtype: int64

### pneuvac4
**Question:** What is the respondent's status for pneumonia vaccine?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [71]:
df_copy['pneuvac4'] = df_copy['pneuvac4'].replace({2: 0})
df_copy['pneuvac4'] = df_copy['pneuvac4'].replace([7, 9], pd.NA)
df_copy['pneuvac4'].value_counts(dropna=False)

pneuvac4
0.0     224324
1.0     151568
<NA>     33714
NaN      29087
Name: count, dtype: int64

## Core Section 14: H.I.V./AIDS

### hivtst7
**Question:** What is the respondent's status for ever had hiv test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [72]:
df_copy['hivtst7'] = df_copy['hivtst7'].replace({2: 0})
df_copy['hivtst7'] = df_copy['hivtst7'].replace([7, 9], pd.NA)
df_copy['hivtst7'].value_counts(dropna=False)

hivtst7
0.0     257829
1.0     129008
NaN      30151
<NA>     21705
Name: count, dtype: int64

### hivtstd3
**Question:** What is the respondent's hiv test time?
- BRFSS combined month/year code for most recent HIV test
- `777777` = Don't know / Not sure
- `999999` = Refused
- cleaning: set `777777` and `999999` to `pd.NA`

In [73]:
df_copy['hivtstd3'] = df_copy['hivtstd3'].replace([777777, 999999], pd.NA)
df_copy['hivtstd3'].value_counts(dropna=False)

hivtstd3
NaN         309898
<NA>         38814
772019.0      2937
772020.0      2835
772018.0      2004
             ...
22022.0          5
21987.0          4
772022.0         2
771984.0         1
120121.0         1
Name: count, Length: 488, dtype: int64

## Core Section 15: Fruits and Vegetables

### fruit2
**Question:** What is the respondent's fruit frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [74]:
df_copy['fruit2'] = df_copy['fruit2'].replace([777, 999], pd.NA)
df_copy['fruit2'].value_counts(dropna=False)

fruit2
101.0    109809
102.0     59227
203.0     35869
NaN       34175
202.0     26766
          ...
231.0         1
341.0         1
275.0         1
261.0         1
135.0         1
Name: count, Length: 173, dtype: int64

### fruitju2
**Question:** What is the respondent's 100% fruit juice frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [75]:
df_copy['fruitju2'] = df_copy['fruitju2'].replace([777, 999], pd.NA)
df_copy['fruitju2'].value_counts(dropna=False)

fruitju2
555.0    167018
101.0     45432
NaN       35762
201.0     26033
202.0     22777
          ...
128.0         1
160.0         1
292.0         1
251.0         1
224.0         1
Name: count, Length: 140, dtype: int64

### fvgreen1
**Question:** What is the respondent's green vegetable frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [76]:
df_copy['fvgreen1'] = df_copy['fvgreen1'].replace([777, 999], pd.NA)
df_copy['fvgreen1'].value_counts(dropna=False)

fvgreen1
101.0    61344
203.0    49740
202.0    48031
201.0    40187
NaN      36995
         ...
216.0        1
361.0        1
145.0        1
123.0        1
353.0        1
Name: count, Length: 171, dtype: int64

### frenchf1
**Question:** What is the respondent's fried potato frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [77]:
df_copy['frenchf1'] = df_copy['frenchf1'].replace([777, 999], pd.NA)
df_copy['frenchf1'].value_counts(dropna=False)

frenchf1
201.0    70047
555.0    57327
302.0    44441
202.0    44334
NaN      38111
         ...
396.0        1
113.0        1
259.0        1
362.0        1
348.0        1
Name: count, Length: 147, dtype: int64

### potatoe1
**Question:** What is the respondent's other potato frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [78]:
df_copy['potatoe1'] = df_copy['potatoe1'].replace([777, 999], pd.NA)
df_copy['potatoe1'].value_counts(dropna=False)

potatoe1
201.0    69200
202.0    51199
555.0    46086
NaN      39306
302.0    37926
         ...
122.0        1
155.0        1
368.0        1
366.0        1
377.0        1
Name: count, Length: 141, dtype: int64

### vegetab2
**Question:** What is the respondent's other vegetable frequency?
- `1__` = Day
- `2__` = Week
- `3__` = Month
- `300` = Less than once a month
- `555` = Never
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [79]:
df_copy['vegetab2'] = df_copy['vegetab2'].replace([777, 999], pd.NA)
df_copy['vegetab2'].value_counts(dropna=False)

vegetab2
101.0    116675
NaN       40615
102.0     37962
203.0     33458
202.0     27295
          ...
275.0         1
116.0         1
354.0         1
192.0         1
227.0         1
Name: count, Length: 168, dtype: int64

## Module 1: Prediabetes

### pdiabtst
**Question:** What is the respondent's status for prediabetes test past 3 years?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [80]:
df_copy['pdiabtst'] = df_copy['pdiabtst'].replace({2: 0})
df_copy['pdiabtst'] = df_copy['pdiabtst'].replace([7, 9], pd.NA)
df_copy['pdiabtst'].value_counts(dropna=False)

pdiabtst
NaN     324075
1.0      62367
0.0      46675
<NA>      5576
Name: count, dtype: int64

### prediab1
**Question:** What is the respondent's status for told has prediabetes?
- `1` = Yes
- `2` = Yes, during pregnancy
- `3` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [81]:
df_copy['prediab1'] = df_copy['prediab1'].replace([7, 9], pd.NA)
df_copy['prediab1'].value_counts(dropna=False)

prediab1
NaN     324076
3.0      97580
1.0      15142
2.0       1266
<NA>       629
Name: count, dtype: int64

## Module 2: Diabetes

### insulin1
**Question:** What is the respondent's status for taking insulin1?
- `1` = Yes
- `2` = No
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [82]:
df_copy['insulin1'] = df_copy['insulin1'].replace({2: 0})
df_copy['insulin1'] = df_copy['insulin1'].replace([7, 9], pd.NA)
df_copy['insulin1'].value_counts(dropna=False)

insulin1
NaN     416455
0.0      14815
1.0       7355
<NA>        68
Name: count, dtype: int64

### bldsugar
**Question:** What is the respondent's status for blood sugar check freq?
- first digit is the time unit:
- `1xx` = times per day
- `2xx` = times per week
- `3xx` = times per month
- `4xx` = times per year
- `777` = Don't know / Not sure
- `888` = Never
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [83]:
df_copy['bldsugar'] = df_copy['bldsugar'].replace([777, 999], pd.NA)
df_copy['bldsugar'].value_counts(dropna=False)

bldsugar
NaN      416454
101.0      5679
102.0      3041
888.0      2688
103.0      1701
          ...
316.0         1
123.0         1
175.0         1
477.0         1
325.0         1
Name: count, Length: 101, dtype: int64

### feetchk3
**Question:** What is the respondent's status for foot self check freq?
- first digit is the time unit:
- `1xx` = times per day
- `2xx` = times per week
- `3xx` = times per month
- `4xx` = times per year
- `555` = No feet
- `777` = Don't know / Not sure
- `888` = Never
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [84]:
df_copy['feetchk3'] = df_copy['feetchk3'].replace([777, 999], pd.NA)
df_copy['feetchk3'].value_counts(dropna=False)

feetchk3
NaN      416460
101.0     10636
888.0      3286
201.0      1744
102.0       923
          ...
198.0         1
111.0         1
191.0         1
424.0         1
213.0         1
Name: count, Length: 80, dtype: int64

### doctdiab
**Question:** What is the respondent's status for doctor visit diabetes freq?
- `1-76` = number of visits in past 12 months (`76` means 76 or more)
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [85]:
df_copy['doctdiab'] = df_copy['doctdiab'].replace([77, 99], pd.NA)
df_copy['doctdiab'].value_counts(dropna=False)

doctdiab
NaN     416463
2.0       5409
4.0       4841
1.0       3914
3.0       2789
88.0      2450
<NA>       749
12.0       562
6.0        544
5.0        370
8.0        127
10.0       105
7.0         70
24.0        49
76.0        40
9.0         35
20.0        29
30.0        24
15.0        23
40.0         9
52.0         9
16.0         8
36.0         8
14.0         8
11.0         7
18.0         7
48.0         6
25.0         6
26.0         4
50.0         4
22.0         2
13.0         2
72.0         2
27.0         2
45.0         2
32.0         2
60.0         2
43.0         1
55.0         1
47.0         1
38.0         1
75.0         1
56.0         1
33.0         1
41.0         1
23.0         1
28.0         1
Name: count, dtype: int64

### chkhemo3
**Question:** What is the respondent's status for a1c check freq?
- `1-76` = number of A1C checks in past 12 months (`76` means 76 or more)
- `88` = None
- `98` = Never heard of A1C test
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [86]:
df_copy['chkhemo3'] = df_copy['chkhemo3'].replace([77, 99], pd.NA)
df_copy['chkhemo3'].value_counts(dropna=False)

chkhemo3
NaN     416464
2.0       6506
4.0       4847
1.0       4344
3.0       2770
88.0      1300
<NA>      1100
6.0        349
12.0       278
98.0       235
5.0        211
8.0         64
7.0         36
24.0        26
10.0        26
9.0         25
76.0        25
20.0        15
30.0        13
11.0         8
15.0         8
52.0         7
40.0         6
48.0         5
60.0         3
16.0         3
36.0         3
25.0         2
14.0         2
18.0         2
13.0         2
44.0         1
31.0         1
21.0         1
33.0         1
56.0         1
38.0         1
28.0         1
26.0         1
Name: count, dtype: int64

### feetchk
**Question:** What is the respondent's status for professional foot check freq?
- `1-76` = number of professional foot checks in past 12 months (`76` means 76 or more)
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [87]:
df_copy['feetchk'] = df_copy['feetchk'].replace([77, 99], pd.NA)
df_copy['feetchk'].value_counts(dropna=False)

feetchk
NaN     416630
1.0       5636
88.0      5251
2.0       4483
4.0       2865
3.0       1618
<NA>       691
6.0        460
12.0       366
5.0        240
8.0         71
10.0        67
76.0        43
24.0        36
7.0         32
52.0        29
20.0        28
9.0         27
30.0        19
15.0        15
60.0        10
40.0        10
11.0         8
48.0         7
50.0         6
14.0         6
26.0         4
27.0         4
38.0         3
25.0         3
18.0         3
13.0         2
21.0         2
33.0         2
45.0         2
41.0         1
35.0         1
44.0         1
43.0         1
75.0         1
23.0         1
47.0         1
19.0         1
56.0         1
51.0         1
36.0         1
22.0         1
32.0         1
16.0         1
Name: count, dtype: int64

### eyeexam1
**Question:** What is the respondent's eye exam recency?
- `1` = Within the past month
- `2` = Within the past year
- `3` = Within the past 2 years
- `4` = 2 or more years ago
- `7` = Don't know / Not sure
- `8` = Never
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [88]:
df_copy['eyeexam1'] = df_copy['eyeexam1'].replace([7, 9], pd.NA)
df_copy['eyeexam1'].value_counts(dropna=False)

eyeexam1
NaN     416468
2.0      10953
1.0       4301
3.0       3180
4.0       2548
8.0        751
<NA>       492
Name: count, dtype: int64

### diabeye
**Question:** What is the respondent's status for diabetes affected eyes?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [89]:
df_copy['diabeye'] = df_copy['diabeye'].replace({2: 0})
df_copy['diabeye'] = df_copy['diabeye'].replace([7, 9], pd.NA)
df_copy['diabeye'].value_counts(dropna=False)

diabeye
NaN     416471
0.0      18059
1.0       3846
<NA>       317
Name: count, dtype: int64

### diabedu
**Question:** What is the respondent's status for diabetes education?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [90]:
df_copy['diabedu'] = df_copy['diabedu'].replace({2: 0})
df_copy['diabedu'] = df_copy['diabedu'].replace([7, 9], pd.NA)
df_copy['diabedu'].value_counts(dropna=False)

diabedu
NaN     416472
1.0      11811
0.0      10264
<NA>       146
Name: count, dtype: int64

## Module 3: ME/CFS

### toldcfs
**Question:** What is the respondent's status for told has ME/CFS?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [91]:
df_copy['toldcfs'] = df_copy['toldcfs'].replace({2: 0})
df_copy['toldcfs'] = df_copy['toldcfs'].replace([7, 9], pd.NA)
df_copy['toldcfs'].value_counts(dropna=False)

toldcfs
NaN    438693
Name: count, dtype: int64

### havecfs
**Question:** What is the respondent's status for still has ME/CFS?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [92]:
df_copy['havecfs'] = df_copy['havecfs'].replace({2: 0})
df_copy['havecfs'] = df_copy['havecfs'].replace([7, 9], pd.NA)
df_copy['havecfs'].value_counts(dropna=False)

havecfs
NaN    438693
Name: count, dtype: int64

### workcfs
**Question:** What is the respondent's work hours per week during the past 6 months with ME/CFS?
- `1` = 0 or no hours, cannot work at all because of CFS or ME
- `2` = 1-10 hours a week
- `3` = 11-20 hours a week
- `4` = 21-30 hours a week
- `5` = 31-40 hours a week
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [93]:
df_copy['workcfs'] = df_copy['workcfs'].replace([7, 9], pd.NA)
df_copy['workcfs'].value_counts(dropna=False)

workcfs
NaN    438693
Name: count, dtype: int64

## Module 4: Hepatitis Treatment

### toldhepc
**Question:** What is the respondent's status for told has hepatitis C?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [94]:
df_copy['toldhepc'] = df_copy['toldhepc'].replace({2: 0})
df_copy['toldhepc'] = df_copy['toldhepc'].replace([7, 9], pd.NA)
df_copy['toldhepc'].value_counts(dropna=False)

toldhepc
NaN     427889
0.0      10580
1.0        163
<NA>        61
Name: count, dtype: int64

### trethepc
**Question:** What is the respondent's status for treated hepatitis C in 2015 or after?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [95]:
df_copy['trethepc'] = df_copy['trethepc'].replace({2: 0})
df_copy['trethepc'] = df_copy['trethepc'].replace([7, 9], pd.NA)
df_copy['trethepc'].value_counts(dropna=False)

trethepc
NaN     438531
0.0         79
1.0         77
<NA>         6
Name: count, dtype: int64

### prirhepc
**Question:** What is the respondent's status for treated hepatitis C before 2015?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [96]:
df_copy['prirhepc'] = df_copy['prirhepc'].replace({2: 0})
df_copy['prirhepc'] = df_copy['prirhepc'].replace([7, 9], pd.NA)
df_copy['prirhepc'].value_counts(dropna=False)

prirhepc
NaN     438531
0.0         91
1.0         65
<NA>         6
Name: count, dtype: int64

### havehepc
**Question:** What is the respondent's status for still has hepatitis C?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [97]:
df_copy['havehepc'] = df_copy['havehepc'].replace({2: 0})
df_copy['havehepc'] = df_copy['havehepc'].replace([7, 9], pd.NA)
df_copy['havehepc'].value_counts(dropna=False)

havehepc
NaN     438531
0.0        124
1.0         21
<NA>        17
Name: count, dtype: int64

### havehepb
**Question:** What is the respondent's status for told has hepatitis B?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [98]:
df_copy['havehepb'] = df_copy['havehepb'].replace({2: 0})
df_copy['havehepb'] = df_copy['havehepb'].replace([7, 9], pd.NA)
df_copy['havehepb'].value_counts(dropna=False)

havehepb
NaN     427914
0.0      10602
1.0         95
<NA>        82
Name: count, dtype: int64

### medshepb
**Question:** What is the respondent's status for taking medicine to treat hepatitis B?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [99]:
df_copy['medshepb'] = df_copy['medshepb'].replace({2: 0})
df_copy['medshepb'] = df_copy['medshepb'].replace([7, 9], pd.NA)
df_copy['medshepb'].value_counts(dropna=False)

medshepb
NaN    438598
0.0        90
1.0         5
Name: count, dtype: int64

## Module 5: HPV - Vaccination

### hpvadvc4
**Question:** What is the respondent's hpv vaccine status?
- `1` = Yes
- `2` = No
- `3` = Doctor refused when asked
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [100]:
df_copy['hpvadvc4'] = df_copy['hpvadvc4'].replace([7, 9], pd.NA)
df_copy['hpvadvc4'].value_counts(dropna=False)

hpvadvc4
NaN     425379
2.0       9102
1.0       2515
<NA>      1688
3.0          9
Name: count, dtype: int64

### hpvadsht
**Question:** What is the respondent's hpv vaccine shot count?
- number of H.P.V. shots received
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [101]:
df_copy['hpvadsht'] = df_copy['hpvadsht'].replace([77, 99], pd.NA)
df_copy['hpvadsht'].value_counts(dropna=False)

hpvadsht
NaN     436183
3.0        956
2.0        592
<NA>       574
1.0        388
Name: count, dtype: int64

## Module 6: Tetanus Diphtheria (Tdap) (Adults)

### tetanus1
**Question:** What is the respondent's tetanus tdap status?
- `1` = Yes, received Tdap
- `2` = Yes, received tetanus shot, but not Tdap
- `3` = Yes, received tetanus shot but not sure what type
- `4` = No, did not receive any tetanus shot in the past 10 years
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [102]:
df_copy['tetanus1'] = df_copy['tetanus1'].replace([7, 9], pd.NA)
df_copy['tetanus1'].value_counts(dropna=False)

tetanus1
NaN     423816
4.0       4376
3.0       4299
1.0       3629
<NA>      1562
2.0       1011
Name: count, dtype: int64

## Module 7: Shingles Vaccination

### shingle2
**Question:** What is the respondent's status for shingles vaccine?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [103]:
df_copy['shingle2'] = df_copy['shingle2'].replace({2: 0})
df_copy['shingle2'] = df_copy['shingle2'].replace([7, 9], pd.NA)
df_copy['shingle2'].value_counts(dropna=False)

shingle2
NaN     425141
0.0       8040
1.0       5199
<NA>       313
Name: count, dtype: int64

## Module 8: COVID Vaccination

### covidvac
**Question:** What is the respondent's status for ever had a COVID-19 vaccination?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [104]:
# df_copy['covidvac'] = df_copy['covidvac'].replace({2: 0})
# df_copy['covidvac'] = df_copy['covidvac'].replace([7, 9], pd.NA)
# df_copy['covidvac'].value_counts(dropna=False)

### covacget
**Question:** What is the respondent's COVID-19 vaccination count?
- `1` = One
- `2` = Two or more
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [105]:
# df_copy['covacget'] = df_copy['covacget'].replace([7, 9], pd.NA)
# df_copy['covacget'].value_counts(dropna=False)

### covidnum
**Question:** What is the respondent's first COVID-19 vaccination date?
- BRFSS combined month/year code
- `777777` = Don't know / Not sure
- `999999` = Refused
- cleaning: set `777777` and `999999` to `pd.NA`

In [106]:
# df_copy['covidnum'] = df_copy['covidnum'].replace([777777, 999999], pd.NA)
# df_copy['covidnum'].value_counts(dropna=False)

### covidint
**Question:** What is the respondent's first COVID-19 vaccination location?
- `1-11` = place vaccination was received
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [107]:
# df_copy['covidint'] = df_copy['covidint'].replace([77, 99], pd.NA)
# df_copy['covidint'].value_counts(dropna=False)

### covidfst
**Question:** What is the respondent's second COVID-19 vaccination date?
- BRFSS combined month/year code
- `777777` = Don't know / Not sure
- `999999` = Refused
- cleaning: set `777777` and `999999` to `pd.NA`

In [108]:
# df_copy['covidfst'] = df_copy['covidfst'].replace([777777, 999999], pd.NA)
# df_copy['covidfst'].value_counts(dropna=False)

### covidsec
**Question:** What is the respondent's second COVID-19 vaccination location?
- `1-11` = place vaccination was received
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [109]:
# df_copy['covidsec'] = df_copy['covidsec'].replace([77, 99], pd.NA)
# df_copy['covidsec'].value_counts(dropna=False)

## Module 9: Lung Cancer Screening

### lcsfirst
**Question:** What is the respondent's age started smoking regularly?
- age in years when respondent first started smoking cigarettes regularly
- `777` = Don't know / Not sure
- `888` = Never smoked cigarettes regularly
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [110]:
df_copy['lcsfirst'] = df_copy['lcsfirst'].replace([777, 999], pd.NA)
df_copy['lcsfirst'].value_counts(dropna=False)

lcsfirst
NaN      426166
18.0       1990
16.0       1763
15.0       1326
17.0       1137
20.0        903
14.0        816
19.0        752
13.0        599
12.0        445
21.0        433
888.0       397
<NA>        297
22.0        287
25.0        235
11.0        142
30.0        139
23.0        132
10.0        118
24.0         88
9.0          66
8.0          51
35.0         51
28.0         51
26.0         44
27.0         43
40.0         33
7.0          21
32.0         20
29.0         18
33.0         12
50.0         12
6.0          11
34.0          9
31.0          8
38.0          7
39.0          6
45.0          6
36.0          6
5.0           6
42.0          6
1.0           5
37.0          4
44.0          4
43.0          3
47.0          3
60.0          3
54.0          3
46.0          2
41.0          2
53.0          2
67.0          2
59.0          2
2.0           1
99.0          1
55.0          1
88.0          1
58.0          1
48.0          1
Name: count, dtype: int64

### lcslast
**Question:** What is the respondent's age last smoked regularly?
- age in years when respondent last smoked cigarettes regularly
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [111]:
df_copy['lcslast'] = df_copy['lcslast'].replace([777, 999], pd.NA)
df_copy['lcslast'].value_counts(dropna=False)

lcslast
NaN     426575
<NA>       682
30.0       631
40.0       604
35.0       466
         ...
4.0          1
3.0          1
95.0         1
89.0         1
11.0         1
Name: count, Length: 92, dtype: int64

### lcsnumcg
**Question:** What is the respondent's status for cigarettes per day when smoking?
- number of cigarettes smoked each day on average when respondent smoked regularly
- `777` = Don't know / Not sure
- `999` = Refused
- cleaning: set `777` and `999` to `pd.NA`

In [112]:
df_copy['lcsnumcg'] = df_copy['lcsnumcg'].replace([777, 999], pd.NA)
df_copy['lcsnumcg'].value_counts(dropna=False)

lcsnumcg
NaN      426594
20.0       3408
10.0       2515
5.0         865
15.0        738
          ...
105.0         1
88.0          1
36.0          1
90.0          1
180.0         1
Name: count, Length: 64, dtype: int64

### lcsctscn
**Question:** What is the respondent's status for had lung cancer ct scan?
- `1` = Yes, to check for lung cancer
- `2` = No, did not have a CT scan
- `3` = Had a CT scan, but for some other reason
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [113]:
df_copy['lcsctscn'] = df_copy['lcsctscn'].replace([7, 9], pd.NA)
df_copy['lcsctscn'].value_counts(dropna=False)

lcsctscn
NaN     408532
2.0      23050
3.0       4884
1.0       1716
<NA>       511
Name: count, dtype: int64

## Module 10: Breast and Cervical Cancer Screening

### hadmam
**Question:** What is the respondent's status for ever had mammogram?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [114]:
df_copy['hadmam'] = df_copy['hadmam'].replace({2: 0})
df_copy['hadmam'] = df_copy['hadmam'].replace([7, 9], pd.NA)
df_copy['hadmam'].value_counts(dropna=False)

hadmam
NaN     429170
1.0       7459
0.0       2016
<NA>        48
Name: count, dtype: int64

### howlong
**Question:** What is the respondent's mammogram recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [115]:
df_copy['howlong'] = df_copy['howlong'].replace([7, 9], pd.NA)
df_copy['howlong'].value_counts(dropna=False)

howlong
NaN     431237
1.0       4236
2.0       1446
5.0        671
3.0        598
4.0        379
<NA>       126
Name: count, dtype: int64

### crvclcnc
**Question:** What is the respondent's cervical cancer screening recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [116]:
df_copy['crvclcnc'] = df_copy['crvclcnc'].replace([7, 9], pd.NA)
df_copy['crvclcnc'].value_counts(dropna=False)

crvclcnc
NaN     433810
1.0       1787
5.0       1063
2.0        901
3.0        533
4.0        411
<NA>       188
Name: count, dtype: int64

### crvclpap
**Question:** What is the respondent's status for Pap test at most recent cervical cancer screening?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [117]:
df_copy['crvclpap'] = df_copy['crvclpap'].replace({2: 0})
df_copy['crvclpap'] = df_copy['crvclpap'].replace([7, 9], pd.NA)
df_copy['crvclpap'].value_counts(dropna=False)

crvclpap
NaN     433847
1.0       4411
0.0        273
<NA>       162
Name: count, dtype: int64

### crvclhpv
**Question:** What is the respondent's status for HPV test at most recent cervical cancer screening?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [118]:
df_copy['crvclhpv'] = df_copy['crvclhpv'].replace({2: 0})
df_copy['crvclhpv'] = df_copy['crvclhpv'].replace([7, 9], pd.NA)
df_copy['crvclhpv'].value_counts(dropna=False)

crvclhpv
NaN     433829
0.0       1945
<NA>      1510
1.0       1409
Name: count, dtype: int64

### hadhyst2
**Question:** What is the respondent's status for had hysterectomy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [119]:
df_copy['hadhyst2'] = df_copy['hadhyst2'].replace({2: 0})
df_copy['hadhyst2'] = df_copy['hadhyst2'].replace([7, 9], pd.NA)
df_copy['hadhyst2'].value_counts(dropna=False)

hadhyst2
NaN     429293
0.0       6540
1.0       2782
<NA>        78
Name: count, dtype: int64

## Module 11: Prostate Cancer Screening

### psatest1
**Question:** What is the respondent's status for ever had psa test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [120]:
df_copy['psatest1'] = df_copy['psatest1'].replace({2: 0})
df_copy['psatest1'] = df_copy['psatest1'].replace([7, 9], pd.NA)
df_copy['psatest1'].value_counts(dropna=False)

psatest1
NaN     436441
1.0       1123
0.0        964
<NA>       165
Name: count, dtype: int64

### psatime1
**Question:** What is the respondent's psa test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [121]:
df_copy['psatime1'] = df_copy['psatime1'].replace([7, 9], pd.NA)
df_copy['psatime1'].value_counts(dropna=False)

psatime1
NaN     437573
1.0        781
2.0        148
5.0         62
3.0         54
4.0         52
<NA>        23
Name: count, dtype: int64

### pcpsars2
**Question:** What is the respondent's reason for psa test?
- `1` = Part of a routine exam
- `2` = Because of a prostate problem
- `3` = Because of a family history of prostate cancer
- `4` = Because you were told you had prostate cancer
- `5` = Some other reason
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [122]:
df_copy['pcpsars2'] = df_copy['pcpsars2'].replace([7, 9], pd.NA)
df_copy['pcpsars2'].value_counts(dropna=False)

pcpsars2
NaN     437574
1.0        907
2.0        115
3.0         81
<NA>        16
Name: count, dtype: int64

### pcstalk
**Question:** What is the respondent's PSA discussion content?
- `1` = Advantages
- `2` = Disadvantages
- `3` = Both advantages and disadvantages
- `4` = Neither
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [123]:
df_copy['pcstalk'] = df_copy['pcstalk'].replace([7, 9], pd.NA)
df_copy['pcstalk'].value_counts(dropna=False)

pcstalk
NaN     437576
3.0        476
4.0        297
1.0        227
<NA>       112
2.0          5
Name: count, dtype: int64

## Module 12: Colorectal Cancer Screening

### hadsigm4
**Question:** What is the respondent's status for ever had sigmoidoscopy or colonoscopy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [124]:
df_copy['hadsigm4'] = df_copy['hadsigm4'].replace({2: 0})
df_copy['hadsigm4'] = df_copy['hadsigm4'].replace([7, 9], pd.NA)
df_copy['hadsigm4'].value_counts(dropna=False)

hadsigm4
NaN     430916
1.0       5607
0.0       2078
<NA>        92
Name: count, dtype: int64

### colnsigm
**Question:** What is the respondent's most recent lower endoscopy type?
- `1` = Colonoscopy
- `2` = Sigmoidoscopy
- `3` = Both
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [125]:
df_copy['colnsigm'] = df_copy['colnsigm'].replace([7, 9], pd.NA)
df_copy['colnsigm'].value_counts(dropna=False)

colnsigm
NaN     433086
1.0       4591
3.0        877
<NA>        76
2.0         63
Name: count, dtype: int64

### colntes1
**Question:** What is the respondent's most recent colonoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [126]:
df_copy['colntes1'] = df_copy['colntes1'].replace([7, 9], pd.NA)
df_copy['colntes1'].value_counts(dropna=False)

colntes1
NaN     434102
5.0       1380
1.0        900
4.0        804
2.0        732
3.0        692
<NA>        83
Name: count, dtype: int64

### sigmtes1
**Question:** What is the respondent's most recent sigmoidoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [127]:
df_copy['sigmtes1'] = df_copy['sigmtes1'].replace([7, 9], pd.NA)
df_copy['sigmtes1'].value_counts(dropna=False)

sigmtes1
NaN     438630
5.0         32
1.0         11
2.0          9
4.0          5
3.0          5
<NA>         1
Name: count, dtype: int64

### lastsig4
**Question:** What is the respondent's sigmoidoscopy or colonoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = Within the past 10 years
- `6` = 10 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [128]:
df_copy['lastsig4'] = df_copy['lastsig4'].replace([7, 9], pd.NA)
df_copy['lastsig4'].value_counts(dropna=False)

lastsig4
NaN     437746
1.0        221
5.0        217
2.0        164
4.0        161
3.0        149
<NA>        35
Name: count, dtype: int64

### colncncr
**Question:** What is the respondent's status for ever had other colorectal cancer test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [129]:
df_copy['colncncr'] = df_copy['colncncr'].replace({2: 0})
df_copy['colncncr'] = df_copy['colncncr'].replace([7, 9], pd.NA)
df_copy['colncncr'].value_counts(dropna=False)

colncncr
NaN     430922
0.0       5902
1.0       1616
<NA>       253
Name: count, dtype: int64

### vircolo1
**Question:** What is the respondent's status for ever had virtual colonoscopy?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [130]:
df_copy['vircolo1'] = df_copy['vircolo1'].replace({2: 0})
df_copy['vircolo1'] = df_copy['vircolo1'].replace([7, 9], pd.NA)
df_copy['vircolo1'].value_counts(dropna=False)

vircolo1
NaN     437077
0.0       1366
1.0        203
<NA>        47
Name: count, dtype: int64

### vclntes1
**Question:** What is the respondent's virtual colonoscopy recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [131]:
df_copy['vclntes1'] = df_copy['vclntes1'].replace([7, 9], pd.NA)
df_copy['vclntes1'].value_counts(dropna=False)

vclntes1
NaN     438490
1.0         67
5.0         49
2.0         30
4.0         23
<NA>        17
3.0         17
Name: count, dtype: int64

### smalstol
**Question:** What is the respondent's status for ever had blood stool test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [132]:
df_copy['smalstol'] = df_copy['smalstol'].replace({2: 0})
df_copy['smalstol'] = df_copy['smalstol'].replace([7, 9], pd.NA)
df_copy['smalstol'].value_counts(dropna=False)

smalstol
NaN     437077
1.0       1232
0.0        362
<NA>        22
Name: count, dtype: int64

### stoltest
**Question:** What is the respondent's blood stool test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [133]:
df_copy['stoltest'] = df_copy['stoltest'].replace([7, 9], pd.NA)
df_copy['stoltest'].value_counts(dropna=False)

stoltest
NaN     437462
1.0        490
5.0        244
2.0        211
3.0        123
4.0        120
<NA>        43
Name: count, dtype: int64

### stooldn1
**Question:** What is the respondent's status for ever had Cologuard test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [134]:
df_copy['stooldn1'] = df_copy['stooldn1'].replace({2: 0})
df_copy['stooldn1'] = df_copy['stooldn1'].replace([7, 9], pd.NA)
df_copy['stooldn1'].value_counts(dropna=False)

stooldn1
NaN     437078
0.0       1184
1.0        390
<NA>        41
Name: count, dtype: int64

### bldstfit
**Question:** What is the respondent's status for blood stool or FIT test conducted as part of a Cologuard test?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [135]:
df_copy['bldstfit'] = df_copy['bldstfit'].replace({2: 0})
df_copy['bldstfit'] = df_copy['bldstfit'].replace([7, 9], pd.NA)
df_copy['bldstfit'].value_counts(dropna=False)

bldstfit
NaN     438303
1.0        250
<NA>        76
0.0         64
Name: count, dtype: int64

### sdnates1
**Question:** What is the respondent's Cologuard test recency?
- `1` = Within the past year
- `2` = Within the past 2 years
- `3` = Within the past 3 years
- `4` = Within the past 5 years
- `5` = 5 or more years ago
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [136]:
df_copy['sdnates1'] = df_copy['sdnates1'].replace([7, 9], pd.NA)
df_copy['sdnates1'].value_counts(dropna=False)

sdnates1
NaN     438303
1.0        191
2.0         83
3.0         42
5.0         33
4.0         24
<NA>        17
Name: count, dtype: int64

## Module 13: Cancer Survivorship: Type of Cancer

### cncrdiff
**Question:** What is the respondent's number of cancer types?
- `1` = Only one
- `2` = Two
- `3` = Three or more
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [137]:
df_copy['cncrdiff'] = df_copy['cncrdiff'].replace([7, 9], pd.NA)
df_copy['cncrdiff'].value_counts(dropna=False)

cncrdiff
NaN     428730
1.0       7653
2.0       1798
3.0        355
<NA>       157
Name: count, dtype: int64

### cncrage
**Question:** What is the respondent's age first diagnosed cancer?
- `1-97` = age in years (`97` means 97 and older)
- `98` = Don't know / Not sure
- `99` = Refused
- cleaning: set `98` and `99` to `pd.NA`

In [138]:
df_copy['cncrage'] = df_copy['cncrage'].replace([98, 99], pd.NA)
df_copy['cncrage'].value_counts(dropna=False)

cncrage
NaN     428896
50.0       579
60.0       554
65.0       478
55.0       415
         ...
97.0         2
10.0         2
11.0         1
92.0         1
94.0         1
Name: count, Length: 97, dtype: int64

### cncrtyp1
**Question:** What is the respondent's most recent cancer type?
- `1-30` = type of cancer
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [139]:
df_copy['cncrtyp1'] = df_copy['cncrtyp1'].replace([77, 99], pd.NA)
df_copy['cncrtyp1'].value_counts(dropna=False)

cncrtyp1
NaN     428905
22.0      2998
21.0      1404
1.0       1326
19.0       861
<NA>       509
30.0       394
10.0       319
2.0        278
8.0        227
3.0        201
25.0       182
24.0       166
17.0       146
4.0        123
26.0       119
18.0       116
16.0        84
20.0        59
12.0        38
27.0        31
7.0         29
13.0        29
15.0        28
14.0        28
11.0        25
5.0         23
28.0        18
6.0         16
9.0          6
29.0         4
23.0         1
Name: count, dtype: int64

## Module 14: Cancer Survivorship: Course of Treatment

### csrvtrt3
**Question:** What is the respondent's status for currently receiving cancer treatment?
- `1` = Yes
- `2` = No, I've completed treatment
- `3` = No, I've refused treatment
- `4` = No, I haven't started treatment
- `5` = Treatment not needed
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [140]:
df_copy['csrvtrt3'] = df_copy['csrvtrt3'].replace([7, 9], pd.NA)
df_copy['csrvtrt3'].value_counts(dropna=False)

csrvtrt3
NaN     431374
2.0       4448
5.0       1378
1.0       1044
4.0        235
<NA>       151
3.0         63
Name: count, dtype: int64

### csrvdoc1
**Question:** What is the respondent's cancer care doctor type?
- `1-10` = type of doctor providing most of health care
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [141]:
df_copy['csrvdoc1'] = df_copy['csrvdoc1'].replace([77, 99], pd.NA)
df_copy['csrvdoc1'].value_counts(dropna=False)

csrvdoc1
NaN     434251
2.0       1744
5.0       1235
10.0       627
7.0        242
1.0        148
<NA>       113
9.0         95
4.0         94
3.0         82
8.0         39
6.0         23
Name: count, dtype: int64

### csrvsum
**Question:** What is the respondent's status for received cancer treatment summary?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [142]:
df_copy['csrvsum'] = df_copy['csrvsum'].replace({2: 0})
df_copy['csrvsum'] = df_copy['csrvsum'].replace([7, 9], pd.NA)
df_copy['csrvsum'].value_counts(dropna=False)

csrvsum
NaN     434258
0.0       2179
1.0       2006
<NA>       250
Name: count, dtype: int64

### csrvrtrn
**Question:** What is the respondent's status for received follow up instructions?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [143]:
df_copy['csrvrtrn'] = df_copy['csrvrtrn'].replace({2: 0})
df_copy['csrvrtrn'] = df_copy['csrvrtrn'].replace([7, 9], pd.NA)
df_copy['csrvrtrn'].value_counts(dropna=False)

csrvrtrn
NaN     434263
1.0       3381
0.0        967
<NA>        82
Name: count, dtype: int64

### csrvinst
**Question:** What is the respondent's status for follow up instructions written?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [144]:
df_copy['csrvinst'] = df_copy['csrvinst'].replace({2: 0})
df_copy['csrvinst'] = df_copy['csrvinst'].replace([7, 9], pd.NA)
df_copy['csrvinst'].value_counts(dropna=False)

csrvinst
NaN     435314
1.0       2370
0.0        783
<NA>       226
Name: count, dtype: int64

### csrvinsr
**Question:** What is the respondent's status for insurance paid for cancer treatment?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [145]:
df_copy['csrvinsr'] = df_copy['csrvinsr'].replace({2: 0})
df_copy['csrvinsr'] = df_copy['csrvinsr'].replace([7, 9], pd.NA)
df_copy['csrvinsr'].value_counts(dropna=False)

csrvinsr
NaN     434267
1.0       4199
0.0        184
<NA>        43
Name: count, dtype: int64

### csrvdein
**Question:** What is the respondent's status for denied insurance because of cancer?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [146]:
df_copy['csrvdein'] = df_copy['csrvdein'].replace({2: 0})
df_copy['csrvdein'] = df_copy['csrvdein'].replace([7, 9], pd.NA)
df_copy['csrvdein'].value_counts(dropna=False)

csrvdein
NaN     434269
0.0       4150
1.0        251
<NA>        23
Name: count, dtype: int64

### csrvclin
**Question:** What is the respondent's status for participated in cancer clinical trial?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [147]:
df_copy['csrvclin'] = df_copy['csrvclin'].replace({2: 0})
df_copy['csrvclin'] = df_copy['csrvclin'].replace([7, 9], pd.NA)
df_copy['csrvclin'].value_counts(dropna=False)

csrvclin
NaN     434272
0.0       4120
1.0        257
<NA>        44
Name: count, dtype: int64

## Module 15: Cancer Survivorship: Pain Management

### csrvpain
**Question:** What is the respondent's status for current physical pain from cancer treatment?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [148]:
df_copy['csrvpain'] = df_copy['csrvpain'].replace({2: 0})
df_copy['csrvpain'] = df_copy['csrvpain'].replace([7, 9], pd.NA)
df_copy['csrvpain'].value_counts(dropna=False)

csrvpain
NaN     429677
0.0       8069
1.0        851
<NA>        96
Name: count, dtype: int64

### csrvctl2
**Question:** What is the respondent's cancer pain control status?
- `1` = With medication (or treatment)
- `2` = Without medication (or treatment)
- `3` = Not under control, with medication (or treatment)
- `4` = Not under control, without medication (or treatment)
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [149]:
df_copy['csrvctl2'] = df_copy['csrvctl2'].replace([7, 9], pd.NA)
df_copy['csrvctl2'].value_counts(dropna=False)

csrvctl2
NaN     437842
1.0        336
2.0        300
4.0        109
3.0         90
<NA>        16
Name: count, dtype: int64

## Module 16: Home/Self-measured Blood Pressure

### hombpchk
**Question:** What is the respondent's status for recommended home blood pressure checks?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [150]:
df_copy['hombpchk'] = df_copy['hombpchk'].replace({2: 0})
df_copy['hombpchk'] = df_copy['hombpchk'].replace([7, 9], pd.NA)
df_copy['hombpchk'].value_counts(dropna=False)

hombpchk
NaN     312692
0.0      83818
1.0      41421
<NA>       762
Name: count, dtype: int64

### homrgchk
**Question:** What is the respondent's status for regularly checks blood pressure outside of a healthcare professional's office?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [151]:
df_copy['homrgchk'] = df_copy['homrgchk'].replace({2: 0})
df_copy['homrgchk'] = df_copy['homrgchk'].replace([7, 9], pd.NA)
df_copy['homrgchk'].value_counts(dropna=False)

homrgchk
NaN     312724
0.0      85817
1.0      39546
<NA>       606
Name: count, dtype: int64

### wherebp
**Question:** Where does the respondent mostly check blood pressure?
- `1` = At home
- `2` = On a machine at a pharmacy, grocery, or similar location
- `3` = Do not check it
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [152]:
df_copy['wherebp'] = df_copy['wherebp'].replace([7, 9], pd.NA)
df_copy['wherebp'].value_counts(dropna=False)

wherebp
NaN     399155
1.0      35476
2.0       3599
<NA>       266
3.0        197
Name: count, dtype: int64

### sharebp
**Question:** How does the respondent share blood pressure numbers with a health professional?
- `1` = Telephone
- `2` = Other methods such as email, internet portal, or fax
- `3` = In person
- `4` = Do not share information
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [153]:
df_copy['sharebp'] = df_copy['sharebp'].replace([7, 9], pd.NA)
df_copy['sharebp'].value_counts(dropna=False)

sharebp
NaN     399168
3.0      24892
4.0       7055
2.0       3581
1.0       3512
<NA>       485
Name: count, dtype: int64

## Module 17: Sodium or Salt-Related Behavior

### wtchsalt
**Question:** What is the respondent's status for watching or reducing sodium or salt intake?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [154]:
df_copy['wtchsalt'] = df_copy['wtchsalt'].replace({2: 0})
df_copy['wtchsalt'] = df_copy['wtchsalt'].replace([7, 9], pd.NA)
df_copy['wtchsalt'].value_counts(dropna=False)

wtchsalt
NaN     402584
0.0      17973
1.0      17868
<NA>       268
Name: count, dtype: int64

### dradvise
**Question:** What is the respondent's status for ever advised to reduce sodium or salt intake?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [155]:
df_copy['dradvise'] = df_copy['dradvise'].replace({2: 0})
df_copy['dradvise'] = df_copy['dradvise'].replace([7, 9], pd.NA)
df_copy['dradvise'].value_counts(dropna=False)

dradvise
NaN     402613
0.0      26420
1.0       9377
<NA>       283
Name: count, dtype: int64

## Module 18: Cognitive Decline

### cimemlos
**Question:** What is the respondent's status for worsening confusion or memory loss?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [156]:
df_copy['cimemlos'] = df_copy['cimemlos'].replace({2: 0})
df_copy['cimemlos'] = df_copy['cimemlos'].replace([7, 9], pd.NA)
df_copy['cimemlos'].value_counts(dropna=False)

cimemlos
NaN     405542
0.0      28648
1.0       4107
<NA>       396
Name: count, dtype: int64

### cdhouse
**Question:** What is the respondent's status for confusion interfered household activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [157]:
df_copy['cdhouse'] = df_copy['cdhouse'].replace([7, 9], pd.NA)
df_copy['cdhouse'].value_counts(dropna=False)

cdhouse
NaN     434324
5.0       1934
3.0       1044
4.0        795
2.0        268
1.0        255
<NA>        73
Name: count, dtype: int64

### cdassist
**Question:** What is the respondent's status for need assistance day to day activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [158]:
df_copy['cdassist'] = df_copy['cdassist'].replace([7, 9], pd.NA)
df_copy['cdassist'].value_counts(dropna=False)

cdassist
NaN     434332
5.0       2209
3.0        897
4.0        824
1.0        215
2.0        170
<NA>        46
Name: count, dtype: int64

### cdhelp
**Question:** What is the respondent's status for gets needed help for activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- cleaning: set `7` and `9` to `pd.NA`

In [159]:
df_copy['cdhelp'] = df_copy['cdhelp'].replace([7, 9], pd.NA)
df_copy['cdhelp'].value_counts(dropna=False)

cdhelp
NaN     437414
1.0        467
3.0        346
2.0        244
4.0        124
5.0         86
<NA>        12
Name: count, dtype: int64

### cdsocial
**Question:** What is the respondent's status for confusion interfered social activities?
- `1` = Always
- `2` = Usually
- `3` = Sometimes
- `4` = Rarely
- `5` = Never
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [160]:
df_copy['cdsocial'] = df_copy['cdsocial'].replace([7, 9], pd.NA)
df_copy['cdsocial'].value_counts(dropna=False)

cdsocial
NaN     434342
5.0       2192
4.0        817
3.0        703
1.0        331
2.0        220
<NA>        88
Name: count, dtype: int64

### cddiscus
**Question:** What is the respondent's status for discussed confusion with health professional?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [161]:
df_copy['cddiscus'] = df_copy['cddiscus'].replace({2: 0})
df_copy['cddiscus'] = df_copy['cddiscus'].replace([7, 9], pd.NA)
df_copy['cddiscus'].value_counts(dropna=False)

cddiscus
NaN     434348
0.0       2551
1.0       1752
<NA>        42
Name: count, dtype: int64

## Module 19: Caregiver

### caregiv1
**Question:** What is the respondent's provided care past 30 days?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `8` = Caregiving recipient died in past 30 days
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [162]:
df_copy['caregiv1'] = df_copy['caregiv1'].replace([7, 9], pd.NA)
df_copy['caregiv1'].value_counts(dropna=False)

caregiv1
NaN     250465
2.0     148002
1.0      38863
<NA>      1035
8.0        328
Name: count, dtype: int64

### crgvrel4
**Question:** What is the respondent's status for care recipient relationship?
- `1-16` = relationship to person cared for
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [163]:
df_copy['crgvrel4'] = df_copy['crgvrel4'].replace([77, 99], pd.NA)
df_copy['crgvrel4'].value_counts(dropna=False)

crgvrel4
NaN     399892
1.0       8028
15.0      6778
6.0       4220
5.0       3466
7.0       3204
2.0       2994
14.0      2473
10.0      1714
3.0       1278
9.0       1249
11.0      1141
4.0        531
<NA>       504
8.0        465
12.0       387
13.0       369
Name: count, dtype: int64

### crgvlng1
**Question:** What is the respondent's caregiving duration?
- `1` = Less than 30 days
- `2` = 1 month to less than 6 months
- `3` = 6 months to less than 2 years
- `4` = 2 years to less than 5 years
- `5` = More than 5 years
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [164]:
df_copy['crgvlng1'] = df_copy['crgvlng1'].replace([7, 9], pd.NA)
df_copy['crgvlng1'].value_counts(dropna=False)

crgvlng1
NaN     399976
5.0      11726
4.0       8337
3.0       7332
1.0       5529
2.0       4921
<NA>       872
Name: count, dtype: int64

### crgvhrs1
**Question:** What is the respondent's caregiving hours per week?
- `1` = Up to 8 hours per week
- `2` = 9 to 19 hours per week
- `3` = 20 to 39 hours per week
- `4` = 40 hours or more
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [165]:
df_copy['crgvhrs1'] = df_copy['crgvhrs1'].replace([7, 9], pd.NA)
df_copy['crgvhrs1'].value_counts(dropna=False)

crgvhrs1
NaN     400062
1.0      19563
4.0       7005
2.0       5099
3.0       4179
<NA>      2785
Name: count, dtype: int64

### crgvprb3
**Question:** What is the respondent's status for care recipient main problem?
- `1-15` = main health problem, long-term illness, or disability
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [166]:
df_copy['crgvprb3'] = df_copy['crgvprb3'].replace([77, 99], pd.NA)
df_copy['crgvprb3'].value_counts(dropna=False)

crgvprb3
NaN     400179
15.0      9533
14.0      5713
5.0       3763
8.0       2960
3.0       2798
13.0      2325
<NA>      2135
7.0       1897
10.0      1650
6.0       1549
1.0       1527
4.0       1420
11.0       902
2.0        155
12.0       131
9.0         56
Name: count, dtype: int64

### crgvper1
**Question:** What is the respondent's status for provided personal care?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [167]:
df_copy['crgvper1'] = df_copy['crgvper1'].replace({2: 0})
df_copy['crgvper1'] = df_copy['crgvper1'].replace([7, 9], pd.NA)
df_copy['crgvper1'].value_counts(dropna=False)

crgvper1
NaN     400353
0.0      19730
1.0      18214
<NA>       396
Name: count, dtype: int64

### crgvhou1
**Question:** What is the respondent's status for provided household tasks?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [168]:
df_copy['crgvhou1'] = df_copy['crgvhou1'].replace({2: 0})
df_copy['crgvhou1'] = df_copy['crgvhou1'].replace([7, 9], pd.NA)
df_copy['crgvhou1'].value_counts(dropna=False)

crgvhou1
NaN     400422
1.0      29782
0.0       8106
<NA>       383
Name: count, dtype: int64

### crgvexpt
**Question:** What is the respondent's status for expect to provide care next 2 years?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [169]:
df_copy['crgvexpt'] = df_copy['crgvexpt'].replace({2: 0})
df_copy['crgvexpt'] = df_copy['crgvexpt'].replace([7, 9], pd.NA)
df_copy['crgvexpt'].value_counts(dropna=False)

crgvexpt
NaN     289886
0.0     117468
1.0      20371
<NA>     10968
Name: count, dtype: int64

## Module 21: Marijuana Use

### marijan1
**Question:** What is the respondent's marijuana use days past 30?
- `1-30` = number of days used marijuana in past 30 days
- `88` = None
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: recode `88 -> 0`; set `77` and `99` to `pd.NA`

In [170]:
df_copy['marijan1'] = df_copy['marijan1'].replace({88: 0})
df_copy['marijan1'] = df_copy['marijan1'].replace([77, 99], pd.NA)
df_copy['marijan1'].value_counts(dropna=False)

marijan1
NaN     301133
0.0     122516
30.0      5432
<NA>      1479
1.0       1267
2.0       1226
5.0        771
10.0       752
20.0       724
15.0       684
3.0        667
4.0        543
25.0       309
8.0        204
7.0        186
6.0        181
12.0       167
28.0       115
14.0        81
29.0        53
16.0        38
27.0        24
21.0        21
9.0         21
24.0        17
26.0        15
18.0        14
17.0        13
22.0        12
23.0        11
11.0        10
19.0         4
13.0         3
Name: count, dtype: int64

### usemrjn3
**Question:** What is the respondent's most frequent marijuana use method?
- `1-6` = most frequent way marijuana was used
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [171]:
df_copy['usemrjn3'] = df_copy['usemrjn3'].replace([7, 9], pd.NA)
df_copy['usemrjn3'].value_counts(dropna=False)

usemrjn3
NaN     425147
1.0       8871
2.0       2650
4.0       1185
5.0        312
6.0        293
3.0        136
<NA>        99
Name: count, dtype: int64

### rsnmrjn2
**Question:** What is the respondent's reason for marijuana use?
- `1` = For medical reasons
- `2` = For non-medical reasons
- `3` = For both medical and non-medical reasons
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: set `7` and `9` to `pd.NA`

In [172]:
df_copy['rsnmrjn2'] = df_copy['rsnmrjn2'].replace([7, 9], pd.NA)
df_copy['rsnmrjn2'].value_counts(dropna=False)

rsnmrjn2
NaN     425161
3.0       5025
2.0       4427
1.0       3951
<NA>       129
Name: count, dtype: int64

## Module 22: Tobacco Cessation

### lastsmk2
**Question:** What is the respondent's last smoked recency?
- `1` = Within the past month
- `2` = Within the past 3 months
- `3` = Within the past 6 months
- `4` = Within the past year
- `5` = Within the past 5 years
- `6` = Within the past 10 years
- `7` = 10 years or more
- `8` = Never smoked regularly
- `77` = Don't know / Not sure
- `99` = Refused
- cleaning: set `77` and `99` to `pd.NA`

In [173]:
df_copy['lastsmk2'] = df_copy['lastsmk2'].replace([77, 99], pd.NA)
df_copy['lastsmk2'].value_counts(dropna=False)

lastsmk2
NaN     386840
7.0      34422
5.0       6800
6.0       4974
4.0       1547
1.0       1279
2.0       1096
3.0        927
<NA>       534
8.0        274
Name: count, dtype: int64

### stopsmk2
**Question:** What is the respondent's status for stopped smoking one day?
- `1` = Yes
- `2` = No
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [174]:
df_copy['stopsmk2'] = df_copy['stopsmk2'].replace({2: 0})
df_copy['stopsmk2'] = df_copy['stopsmk2'].replace([7, 9], pd.NA)
df_copy['stopsmk2'].value_counts(dropna=False)

stopsmk2
NaN     414631
0.0      12087
1.0      11860
<NA>       115
Name: count, dtype: int64

## Module 24: Industry and Occupation

- no executable cleaning cells added for `typework` or `typeinds`
- the 2018 CSV in this repo does not include those free-text columns as structured fields

## Module 25: Random Child Selection

### rcsgendr
**Question:** What is the sex of the randomly selected child?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [175]:
df_copy['rcsgendr'] = df_copy['rcsgendr'].replace([7, 9, 77, 99], pd.NA)
df_copy['rcsgendr'].value_counts(dropna=False)

rcsgendr
NaN     381636
1.0      27709
2.0      25810
<NA>      3538
Name: count, dtype: int64

### rcsrltn2
**Question:** How is the randomly selected child related to the respondent?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [176]:
df_copy['rcsrltn2'] = df_copy['rcsrltn2'].replace([7, 9, 77, 99], pd.NA)
df_copy['rcsrltn2'].value_counts(dropna=False)

rcsrltn2
NaN     382013
1.0      44049
2.0       4655
4.0       2688
<NA>      2336
5.0       1452
6.0        776
3.0        724
Name: count, dtype: int64

## Module 26: Childhood Asthma Prevalence

### casthdx2
**Question:** Has a doctor, nurse, or other health professional ever said that the selected child has asthma?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [177]:
df_copy['casthdx2'] = df_copy['casthdx2'].replace([7, 9, 77, 99], pd.NA)
df_copy['casthdx2'].value_counts(dropna=False)

casthdx2
NaN     383874
2.0      46206
1.0       5770
<NA>      2843
Name: count, dtype: int64

### casthno2
**Question:** Does the selected child still have asthma?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [178]:
df_copy['casthno2'] = df_copy['casthno2'].replace([7, 9, 77, 99], pd.NA)
df_copy['casthno2'].value_counts(dropna=False)

casthno2
NaN     432927
1.0       3733
2.0       1867
<NA>       166
Name: count, dtype: int64

## Module 27: Sex at Birth

### birthsex
**Question:** What is the respondent's status for male?
- `1` = Male
- `2` = Female
- `7` = Don't know / Not sure
- `9` = Refused
- cleaning: recode `2 -> 0`; set `7` and `9` to `pd.NA`

In [179]:
df_copy['birthsex'] = df_copy['birthsex'].replace({2: 0})
df_copy['birthsex'] = df_copy['birthsex'].replace([7, 9], pd.NA)
df_copy['birthsex'].value_counts(dropna=False)

birthsex
NaN     340191
0.0      52392
1.0      45789
<NA>       321
Name: count, dtype: int64

## Module 28: Sexual Orientation and Gender Identity (SOGI)

### somale
**Question:** Which response best describes the respondent's sexual attraction to males?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [180]:
df_copy['somale'] = df_copy['somale'].replace([7, 9, 77, 99], pd.NA)
df_copy['somale'].value_counts(dropna=False)

somale
NaN     324524
2.0     104645
<NA>      3507
1.0       2487
3.0       2045
4.0       1485
Name: count, dtype: int64

### sofemale
**Question:** Which response best describes the respondent's sexual attraction to females?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [181]:
df_copy['sofemale'] = df_copy['sofemale'].replace([7, 9, 77, 99], pd.NA)
df_copy['sofemale'].value_counts(dropna=False)

sofemale
NaN     307374
2.0     117780
<NA>      4802
3.0       4734
4.0       2076
1.0       1927
Name: count, dtype: int64

### trnsgndr
**Question:** Which response best describes the respondent's transgender status?
- retain valid categorical responses as recorded
- cleaning: set `7`, `9`, `77`, and `99` to `pd.NA`

In [182]:
df_copy['trnsgndr'] = df_copy['trnsgndr'].replace([7, 9, 77, 99], pd.NA)
df_copy['trnsgndr'].value_counts(dropna=False)

trnsgndr
4.0     240821
NaN     192949
<NA>      3715
3.0        443
2.0        383
1.0        382
Name: count, dtype: int64

### Rename Management Columns
Rename the cleaned diabetes-management variables to readable analysis names before EDA and export

In [183]:
df_copy = df_copy.rename(columns={
    'diabedu': 'Diabetes_Education',
    'feetchk3': 'Foot_Self_Check_Freq',
    'bldsugar': 'Blood_Sugar_Check_Freq',
    'doctdiab': 'Doctor_Visit_Diabetes_Freq',
    'chkhemo3': 'A1C_Check_Freq',
    'feetchk': 'Professional_Foot_Check_Freq',
    'eyeexam1': 'Eye_Exam_Recency',
    'genhlth': 'General_Health',
    'physhlth': 'Bad_Physical_Health_Days',
    'poorhlth': 'Poor_Health_Impact_Days',
    'medcost1': 'Skipped_Doctor_Due_To_Cost',
    'checkup1': 'Checkup_Recency',
    'exerany2': 'Any_Exercise',
    'bphigh6': 'High_Blood_Pressure_Status',
    'bpmeds': 'Taking_High_Blood_Pressure_Medicine',
    'cholchk3': 'Cholesterol_Check_Recency',
    'toldhi3': 'Told_Has_High_Cholesterol',
    'cholmed3': 'Taking_Cholesterol_Medicine',
    'fruit2': 'Fruit_Frequency',
    'fruitju2': 'Fruit_Juice_Frequency',
    'fvgreen1': 'Green_Vegetable_Frequency',
    'frenchf1': 'Fried_Potato_Frequency',
    'potatoe1': 'Other_Potato_Frequency',
    'vegetab2': 'Other_Vegetable_Frequency',
    'toldcfs': 'Told_Has_ME_CFS',
    'havecfs': 'Still_Has_ME_CFS',
    'workcfs': 'Work_Hours_Per_Week_With_ME_CFS',
    'toldhepc': 'Told_Has_Hepatitis_C',
    'trethepc': 'Treated_Hepatitis_C_2015_Or_After',
    'prirhepc': 'Treated_Hepatitis_C_Before_2015',
    'havehepc': 'Still_Has_Hepatitis_C',
    'havehepb': 'Told_Has_Hepatitis_B',
    'medshepb': 'Taking_Medicine_For_Hepatitis_B',
    'covidvac': 'Ever_Had_COVID_Vaccine',
    'covacget': 'COVID_Vaccine_Count',
    'covidnum': 'First_COVID_Vaccine_Date',
    'covidint': 'First_COVID_Vaccine_Location',
    'covidfst': 'Second_COVID_Vaccine_Date',
    'covidsec': 'Second_COVID_Vaccine_Location',
    'cvdinfr4': 'Heart_Attack',
    'cvdcrhd4': 'Coronary_Heart_Disease',
    'cvdstrk3': 'Stroke',
    'asthma3': 'Ever_Asthma',
    'asthnow': 'Current_Asthma',
    'chcscncr': 'Skin_Cancer',
    'chcocncr': 'Other_Cancer',
    'chccopd3': 'COPD',
    'havarth5': 'Arthritis',
    'chckdny2': 'Kidney_Disease',
    'x.hispanc': 'Hispanic',
    'x.mrace1': 'Race_Multi_Select',
    'x.prace1': 'Race_Best_Represents',
    'renthom1': 'Own_Or_Rent',
    'numhhol3': 'Multiple_Phones_In_Household',
    'numphon3': 'Residential_Phones',
    'cpdemo1b': 'Personal_Cell_Phones',
    'veteran3': 'Veteran_Status',
    'children': 'Children_In_Household',
    'weight2': 'Weight',
    'height3': 'Height',
    'pregnant': 'Pregnant',
    'deaf': 'Deaf_Or_Serious_Hearing_Difficulty',
    'blind': 'Blind_Or_Serious_Vision_Difficulty',
    'decide': 'Serious_Difficulty_Decisions',
    'diffwalk': 'Serious_Difficulty_Walking',
    'diffdres': 'Serious_Difficulty_Dressing',
    'diffalon': 'Serious_Difficulty_Doing_Errands',
    'menthlth': 'Bad_Mental_Health_Days',
    'educa': 'Education',
    'x.ageg5yr': 'Age_Group',
    'birthsex': 'Male',
    'marital': 'Marital_Status',
    'employ1': 'Employment_Status',
    'income3': 'Income',
    'x.urbstat': 'Urban_Rural_Status',
    'persdoc3': 'Personal_Doctor',
    'x.hlthpln': 'Health_Coverage',
    'addepev3': 'Depressive_Disorder',
    'diabete4': 'Diabetes_Status',
    'diabage3': 'Diabetes_Age',
    'smoke100': 'Smoked_100_Cigarettes',
    'smokday2': 'Smoke_Frequency',
    'stopsmk2': 'Stopped_Smoking_One_Day',
    'lastsmk2': 'Last_Smoked_Recency',
    'usenow3': 'Smokeless_Tobacco_Frequency',
    'alcday5': 'Alcohol_Frequency',
    'avedrnk3': 'Average_Drinks',
    'drnk3ge5': 'Binge_Drinking_Frequency',
    'maxdrnks': 'Max_Drinks',
    'flushot7': 'Flu_Shot',
    'pneuvac4': 'Pneumonia_Vaccine',
    'hadmam': 'Ever_Had_Mammogram',
    'howlong': 'Mammogram_Recency',
    'crvclcnc': 'Cervical_Cancer_Screening_Recency',
    'crvclpap': 'Pap_Test_At_Most_Recent_Cervical_Screening',
    'crvclhpv': 'HPV_Test_At_Most_Recent_Cervical_Screening',
    'hadhyst2': 'Had_Hysterectomy',
    'psatest1': 'Ever_Had_PSA_Test',
    'psatime1': 'PSA_Test_Recency',
    'pcpsars2': 'Reason_For_PSA_Test',
    'pcstalk': 'PSA_Discussion_Content',
    'hadsigm4': 'Ever_Had_Sigmoidoscopy_Or_Colonoscopy',
    'lastsig4': 'Sigmoidoscopy_Or_Colonoscopy_Recency',
    'colnsigm': 'Most_Recent_Lower_Endoscopy_Type',
    'colntes1': 'Most_Recent_Colonoscopy_Recency',
    'sigmtes1': 'Most_Recent_Sigmoidoscopy_Recency',
    'colncncr': 'Ever_Had_Other_Colorectal_Cancer_Test',
    'vircolo1': 'Ever_Had_Virtual_Colonoscopy',
    'vclntes1': 'Virtual_Colonoscopy_Recency',
    'smalstol': 'Ever_Had_Blood_Stool_Test',
    'stoltest': 'Blood_Stool_Test_Recency',
    'stooldn1': 'Ever_Had_Cologuard_Test',
    'bldstfit': 'Blood_Stool_Test_Part_Of_Cologuard',
    'sdnates1': 'Cologuard_Test_Recency',
    'hivtst7': 'Ever_Had_HIV_Test',
    'hivtstd3': 'HIV_Test_Time',
    'pdiabtst': 'Prediabetes_Test_Past_3_Years',
    'prediab1': 'Told_Has_Prediabetes',
    'insulin1': 'Taking_Insulin',
    'diabeye': 'Diabetes_Affected_Eyes',
    'cimemlos': 'Worsening_Confusion_Or_Memory_Loss',
    'cdhouse': 'Confusion_Interfered_Household_Activities',
    'cdassist': 'Need_Assistance_Day_To_Day_Activities',
    'cdhelp': 'Gets_Needed_Help_For_Activities',
    'cdsocial': 'Confusion_Interfered_Social_Activities',
    'cddiscus': 'Discussed_Confusion_With_Health_Professional',
    'caregiv1': 'Provided_Care_Past_30_Days',
    'crgvrel4': 'Care_Recipient_Relationship',
    'crgvlng1': 'Caregiving_Duration',
    'crgvhrs1': 'Caregiving_Hours_Per_Week',
    'crgvprb3': 'Care_Recipient_Main_Problem',
    'crgvper1': 'Provided_Personal_Care',
    'crgvhou1': 'Provided_Household_Tasks',
    'crgvexpt': 'Expect_To_Provide_Care_Next_2_Years',
    'ecignow1': 'E_Cigarette_Frequency',
    'marijan1': 'Marijuana_Use_Days_Past_30',
    'usemrjn3': 'Most_Frequent_Marijuana_Use_Method',
    'rsnmrjn2': 'Reason_For_Marijuana_Use',
    'lcsfirst': 'Age_Started_Smoking_Regularly',
    'lcslast': 'Age_Last_Smoked_Regularly',
    'lcsnumcg': 'Cigarettes_Per_Day_When_Smoking',
    'lcsctscn': 'Had_Lung_Cancer_CT_Scan',
    'cncrdiff': 'Number_Of_Cancer_Types',
    'cncrage': 'Age_First_Diagnosed_Cancer',
    'cncrtyp1': 'Most_Recent_Cancer_Type',
    'csrvtrt3': 'Currently_Receiving_Cancer_Treatment',
    'csrvdoc1': 'Cancer_Care_Doctor_Type',
    'csrvsum': 'Received_Cancer_Treatment_Summary',
    'csrvrtrn': 'Received_Follow_Up_Instructions',
    'csrvinst': 'Follow_Up_Instructions_Written',
    'csrvinsr': 'Insurance_Paid_For_Cancer_Treatment',
    'csrvdein': 'Denied_Insurance_Because_Of_Cancer',
    'csrvclin': 'Participated_In_Cancer_Clinical_Trial',
    'csrvpain': 'Current_Physical_Pain_From_Cancer_Treatment',
    'csrvctl2': 'Cancer_Pain_Control_Status',
    'hombpchk': 'Recommended_Home_Blood_Pressure_Check',
    'homrgchk': 'Regularly_Checks_Blood_Pressure_Outside_Office',
    'wherebp': 'Where_Blood_Pressure_Is_Checked',
    'sharebp': 'How_Blood_Pressure_Is_Shared',
    'wtchsalt': 'Watching_Or_Reducing_Sodium_Or_Salt',
    'dradvise': 'Advised_To_Reduce_Sodium_Or_Salt',
    'hpvadvc4': 'HPV_Vaccine_Status',
    'hpvadsht': 'HPV_Vaccine_Shot_Count',
    'tetanus1': 'Tetanus_Tdap_Status',
    'shingle2': 'Shingles_Vaccine',
    'somale': 'Sex_Attracted_To_Males',
    'sofemale': 'Sex_Attracted_To_Females',
    'trnsgndr': 'Transgender_Status',
    'rcsgendr': 'Random_Child_Gender',
    'rcsrltn2': 'Child_Relationship_To_Respondent',
    'casthdx2': 'Child_Ever_Diagnosed_With_Asthma',
    'casthno2': 'Child_Current_Asthma',
})

### Normalize Missing Values
Convert any remaining `NaN` values to `pd.NA` and switch columns to pandas nullable dtypes before reporting missingness and saving

In [184]:
df_copy = df_copy.mask(df_copy.isna(), pd.NA).convert_dtypes()
df_copy.dtypes

General_Health                      Float64
Bad_Physical_Health_Days            Float64
Bad_Mental_Health_Days              Float64
Poor_Health_Impact_Days             Float64
priminsr                            Float64
                                     ...
Sex_Attracted_To_Males              Float64
Sex_Attracted_To_Females            Float64
Transgender_Status                  Float64
Child_Ever_Diagnosed_With_Asthma    Float64
Child_Current_Asthma                Float64
Length: 171, dtype: object

In [185]:
missing_pct = (
    df_copy.isna().mean().mul(100).round(2).sort_values(ascending=False).rename('missing_pct').to_frame()
)
missing_pct

                                   missing_pct
Told_Has_ME_CFS                         100.00
Still_Has_ME_CFS                        100.00
Work_Hours_Per_Week_With_ME_CFS         100.00
Most_Recent_Sigmoidoscopy_Recency        99.99
Taking_Medicine_For_Hepatitis_B          99.98
...                                        ...
Other_Cancer                              0.31
Skipped_Doctor_Due_To_Cost                0.31
General_Health                            0.26
Diabetes_Status                           0.22
Any_Exercise                              0.21

[171 rows x 1 columns]

In [186]:
df_copy

,General_Health,Bad_Physical_Health_Days,Bad_Mental_Health_Days,Poor_Health_Impact_Days,priminsr,Personal_Doctor,Skipped_Doctor_Due_To_Cost,Checkup_Recency,Any_Exercise,High_Blood_Pressure_Status,Taking_High_Blood_Pressure_Medicine,Cholesterol_Check_Recency,Told_Has_High_Cholesterol,Taking_Cholesterol_Medicine,Heart_Attack,Coronary_Heart_Disease,Stroke,Ever_Asthma,Current_Asthma,Skin_Cancer,Other_Cancer,COPD,Depressive_Disorder,Kidney_Disease,Diabetes_Status,Diabetes_Age,Arthritis,arthexer,arthedu,lmtjoin3,arthdis2,joinpai2,Age_Group,Hispanic,Race_Multi_Select,Race_Best_Represents,Marital_Status,Education,Own_Or_Rent,Urban_Rural_Status,Multiple_Phones_In_Household,Residential_Phones,Personal_Cell_Phones,Veteran_Status,Employment_Status,Children_In_Household,Income,Pregnant,Weight,Height,Deaf_Or_Serious_Hearing_Difficulty,Blind_Or_Serious_Vision_Difficulty,Serious_Difficulty_Decisions,Serious_Difficulty_Walking,Serious_Difficulty_Dressing,Serious_Difficulty_Doing_Errands,Smoked_100_Cigarettes,Smoke_Frequency,Smokeless_Tobacco_Frequency,E_Cigarette_Frequency,Alcohol_Frequency,Average_Drinks,Binge_Drinking_Frequency,Max_Drinks,Flu_Shot,Pneumonia_Vaccine,Ever_Had_HIV_Test,HIV_Test_Time,Fruit_Frequency,Fruit_Juice_Frequency,Green_Vegetable_Frequency,Fried_Potato_Frequency,Other_Potato_Frequency,Other_Vegetable_Frequency,Prediabetes_Test_Past_3_Years,Told_Has_Prediabetes,Taking_Insulin,Blood_Sugar_Check_Freq,Foot_Self_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Diabetes_Affected_Eyes,Diabetes_Education,Told_Has_ME_CFS,Still_Has_ME_CFS,Work_Hours_Per_Week_With_ME_CFS,Told_Has_Hepatitis_C,Treated_Hepatitis_C_2015_Or_After,Treated_Hepatitis_C_Before_2015,Still_Has_Hepatitis_C,Told_Has_Hepatitis_B,Taking_Medicine_For_Hepatitis_B,HPV_Vaccine_Status,HPV_Vaccine_Shot_Count,Tetanus_Tdap_Status,Shingles_Vaccine,Age_Started_Smoking_Regularly,Age_Last_Smoked_Regularly,Cigarettes_Per_Day_When_Smoking,Had_Lung_Cancer_CT_Scan,Ever_Had_Mammogram,Mammogram_Recency,Cervical_Cancer_Screening_Recency,Pap_Test_At_Most_Recent_Cervical_Screening,HPV_Test_At_Most_Recent_Cervical_Screening,Had_Hysterectomy,Ever_Had_PSA_Test,PSA_Test_Recency,Reason_For_PSA_Test,PSA_Discussion_Content,Ever_Had_Sigmoidoscopy_Or_Colonoscopy,Most_Recent_Lower_Endoscopy_Type,Most_Recent_Colonoscopy_Recency,Most_Recent_Sigmoidoscopy_Recency,Sigmoidoscopy_Or_Colonoscopy_Recency,Ever_Had_Other_Colorectal_Cancer_Test,Ever_Had_Virtual_Colonoscopy,Virtual_Colonoscopy_Recency,Ever_Had_Blood_Stool_Test,Blood_Stool_Test_Recency,Ever_Had_Cologuard_Test,Blood_Stool_Test_Part_Of_Cologuard,Cologuard_Test_Recency,Number_Of_Cancer_Types,Age_First_Diagnosed_Cancer,Most_Recent_Cancer_Type,Currently_Receiving_Cancer_Treatment,Cancer_Care_Doctor_Type,Received_Cancer_Treatment_Summary,Received_Follow_Up_Instructions,Follow_Up_Instructions_Written,Insurance_Paid_For_Cancer_Treatment,Denied_Insurance_Because_Of_Cancer,Participated_In_Cancer_Clinical_Trial,Current_Physical_Pain_From_Cancer_Treatment,Cancer_Pain_Control_Status,Recommended_Home_Blood_Pressure_Check,Regularly_Checks_Blood_Pressure_Outside_Office,Where_Blood_Pressure_Is_Checked,How_Blood_Pressure_Is_Shared,Watching_Or_Reducing_Sodium_Or_Salt,Advised_To_Reduce_Sodium_Or_Salt,Worsening_Confusion_Or_Memory_Loss,Confusion_Interfered_Household_Activities,Need_Assistance_Day_To_Day_Activities,Gets_Needed_Help_For_Activities,Confusion_Interfered_Social_Activities,Discussed_Confusion_With_Health_Professional,Provided_Care_Past_30_Days,Care_Recipient_Relationship,Caregiving_Duration,Caregiving_Hours_Per_Week,Care_Recipient_Main_Problem,Provided_Personal_Care,Provided_Household_Tasks,Expect_To_Provide_Care_Next_2_Years,Marijuana_Use_Days_Past_30,Most_Frequent_Marijuana_Use_Method,Reason_For_Marijuana_Use,Last_Smoked_Recency,Stopped_Smoking_One_Day,Random_Child_Gender,Child_Relationship_To_Respondent,Male,Sex_Attracted_To_Males,Sex_Attracted_To_Females,Transgender_Status,Child_Ever_Diagnosed_With_Asthma,Child_Current_Asthma
0,5.0,20.0,10.0,0.0,3.0,1.0,0.0,2.0,0.0,3.0,<NA>,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,3.0,<NA>,1.0,2,2,2,1,8,11,0,1.0,1.0,1.0,4.0,1.0,1,1.0,1.0,1.0,0.0,7.0,0.0,5.0,<NA>,72.0,411.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,3.0,3.0,3.0,888.0,<NA>,<NA>,<NA>,1.0,1.0,0.0,<NA>,101.0,555.0,204.0,203.0,201.0,101.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
1,3.0,0.0,0.0,<NA>,1.0,2.0,0.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,0.0,1.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,1.0,1.0,<NA>,1.0,1,2,1,1,10,10,0,2.0,2.0,<NA>,6.0,1.0,1,0.0,<NA>,1.0,0.0,8.0,0.0,<NA>,<NA>,<NA>,506.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,<NA>,3.0,3.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,<NA>,101.0,555.0,201.0,555.0,201.0,207.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
2,2.0,0.0,0.0,<NA>,0.0,2.0,0.0,1.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,1.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,11,0,2.0,2.0,3.0,4.0,1.0,1,0.0,<NA>,1.0,0.0,7.0,0.0,3.0,<NA>,170.0,505.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,3.0,3.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,<NA>,101.0,555.0,555.0,201.0,201.0,203.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,2.0,0.0,10.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,1.0,56.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,9,0,1.0,1.0,1.0,4.0,1.0,1,0.0,<NA>,1.0,0.0,7.0,0.0,7.0,<NA>,195.0,504.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,3.0,3.0,101.0,3.0,1.0,6.0,1.0,0.0,0.0,<NA>,203.0,205.0,303.0,204.0,308.0,205.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
4,5.0,30.0,0.0,30.0,3.0,1.0,0.0,1.0,1.0,4.0,<NA>,2.0,1.0,1.0,1.0,<NA>,1.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,1.0,65.0,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,12,0,7.0,1.0,1.0,3.0,1.0,1,0.0,<NA>,8.0,0.0,8.0,0.0,4.0,<NA>,206.0,511.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,<NA>,2.0,3.0,888.0,<NA>,<NA>,<NA>,1.0,1.0,1.0,<NA>,101.0,555.0,101.0,202.0,202.0,101.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,2.0,0.0,20.0,0.0,88.0,3.0,1.0,4.0,1.0,1.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,3,0,<NA>,<NA>,5.0,4.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,1.0,1.0,5.0,0.0,135.0,502.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,3.0,3.0,204.0,2.0,88.0,2.0,0.0,1.0,1.0,12016.0,210.0,201.0,202.0,201.0,315.0,103.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.0,1.0,<NA>,<NA>,<NA>,<NA>,2.0,<NA>
438689,3.0,0.0,0.0,<NA>,77.0,1.0,0.0,1.0,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,1.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,13,0,6.0,6.0,3.0,4.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,8.0,0.0,1.0,<NA>,<NA>,502.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,<NA>,3.0,4.0,888.0,<NA>,<NA>,<NA>,0.0,0.0,0.0,<NA>,101.0,101.0,101.0,201.0,201.0,202.0,<NA>,<NA>,0.0,101.0,101.0,4.0,4.0,4.0,1.0,1.0,1.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
438690,2.0,0.0,0.0,<NA>,10.0,1.0,0.0,1.0,1.0,3.0,<NA>,2.0,1.0,0.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7,0,2.0,2.0,1.0,6.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,7.0,0.0,10.0,<NA>,220.0,511.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,3.0,3.0,210.0,2.0,88.0,3.0,0.0,0.0,1.0,772019.0,102.0,555.0,202.0,555.0,201.0,101.0,0.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
438691,2.0,0.0,0.0,<NA>,3.0,2.0,0.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,10,0,<NA>,<NA>,2.0,4.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,7.0,0.0,6.0,<NA>,175.0,600.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,3.0,4.0,203.0,2.0,88.0,3.0,0.0,0.0,1.0,<NA>,101.0,555.0,203.0,555.0,304.0,101.0,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
438692,1.0,2.0,2.0,0.0,10.0,2.0,0.0,1.0,1.0,3.0,<NA>,2.0,1.0,0.0,0.0,0.0,0.0,0.0,<NA>,0.0,0.0,0.0,0.0,0.0,3.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,6,0,2.0,2.0,2.0,6.0,1.0,<NA>,<NA>,<NA>,1.0,0.0,1.0,0.0,6.0,0.0,179.0,503.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,<NA>,3.0,3.0,201.0,1.0,88.0,1.0,0.0,0.0,1.0,22019.0,305.0,305.0,203.0,301.0,301.0,305.0,1.0,3.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>

### Data Path

In [187]:
# data_path = '../../data/clean'

### Save Dataset

In [190]:
# missing_pct.to_csv(f'{year}_missing_pct.csv')
# df_copy.to_csv(f'{year}_brfss_data.csv', index=False)