# Getting Data

### Imports
- import the libraries used for data loading, cleaning, and sampling

In [41]:
import pandas as pd

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

### Survey Year
- set the BRFSS year used to build the file path

In [2]:
year = '2021'

### Load CSV
- load the 2021 BRFSS CSV into a dataframe

In [3]:
brfss_2021_df = pd.read_csv("brfss2021.csv")

### Dataset Shape
- inspect the number of rows and columns in the raw 2021 BRFSS file

In [4]:
brfss_2021_df.shape

(438693, 304)

### Display Settings
- show more columns when previewing the dataframe
- display the first few rows of the raw dataset

In [5]:
pd.set_option('display.max_columns', 500)
brfss_2021_df.head()

,Unnamed: 0,x.state,fmonth,idate,imonth,iday,iyear,dispcode,seqno,x.psu,ctelenm1,pvtresd1,colghous,statere1,celphon1,ladult1,colgsex,numadult,landsex,nummen,numwomen,respslct,safetime,ctelnum1,cellfon5,cadult1,cellsex,pvtresd3,cclghous,cstate1,landline,hhadult,sexvar,genhlth,physhlth,menthlth,poorhlth,priminsr,persdoc3,medcost1,checkup1,exerany2,bphigh6,bpmeds,cholchk3,toldhi3,cholmed3,cvdinfr4,cvdcrhd4,cvdstrk3,asthma3,asthnow,chcscncr,chcocncr,chccopd3,addepev3,chckdny2,diabete4,diabage3,havarth5,arthexer,arthedu,lmtjoin3,arthdis2,joinpai2,marital,educa,renthom1,numhhol3,numphon3,cpdemo1b,veteran3,employ1,children,income3,pregnant,weight2,height3,deaf,blind,decide,diffwalk,diffdres,diffalon,smoke100,smokday2,usenow3,ecignow1,alcday5,avedrnk3,drnk3ge5,maxdrnks,flushot7,flshtmy3,imfvpla2,pneuvac4,hivtst7,hivtstd3,fruit2,fruitju2,fvgreen1,frenchf1,potatoe1,vegetab2,pdiabtst,prediab1,insulin1,bldsugar,feetchk3,doctdiab,chkhemo3,feetchk,eyeexam1,diabeye,diabedu,toldcfs,havecfs,workcfs,toldhepc,trethepc,prirhepc,havehepc,havehepb,medshepb,hpvadvc4,hpvadsht,tetanus1,shingle2,lcsfirst,lcslast,lcsnumcg,lcsctscn,hadmam,howlong,cervscrn,crvclcnc,crvclpap,crvclhpv,hadhyst2,psatest1,psatime1,pcpsars2,pcstalk,hadsigm4,colnsigm,colntes1,sigmtes1,lastsig4,colncncr,vircolo1,vclntes1,smalstol,stoltest,stooldn1,bldstfit,sdnates1,cncrdiff,cncrage,cncrtyp1,csrvtrt3,csrvdoc1,csrvsum,csrvrtrn,csrvinst,csrvinsr,csrvdein,csrvclin,csrvpain,csrvctl2,hombpchk,homrgchk,wherebp,sharebp,wtchsalt,dradvise,cimemlos,cdhouse,cdassist,cdhelp,cdsocial,cddiscus,caregiv1,crgvrel4,crgvlng1,crgvhrs1,crgvprb3,crgvalzd,crgvper1,crgvhou1,crgvexpt,acedeprs,acedrink,acedrugs,aceprisn,acedivrc,acepunch,acehurt1,aceswear,acetouch,acetthem,acehvsex,aceadsaf,aceadned,marijan1,usemrjn3,rsnmrjn2,lastsmk2,stopsmk2,firearm5,gunload,loadulk2,rcsgendr,rcsrltn2,casthdx2,casthno2,birthsex,somale,sofemale,trnsgndr,qstver,qstlang,x.metstat,x.urbstat,mscode,x.ststr,x.strwt,x.rawrake,x.wt2rake,x.imprace,x.chispnc,x.crace1,x.cprace1,cageg,x.cllcpwt,x.dualuse,x.dualcor,x.llcpwt2,x.llcpwt,x.rfhlth,x.phys14d,x.ment14d,x.hlthpln,x.hcvu652,x.totinda,x.rfhype6,x.cholch3,x.rfchol3,x.michd,x.ltasth1,x.casthm1,x.asthms1,x.drdxar3,x.lmtact3,x.lmtwrk3,x.prace1,x.mrace1,x.hispanc,x.race,x.raceg21,x.racegr3,x.raceprv,x.sex,x.ageg5yr,x.age65yr,x.age80,x.age.g,htin4,htm4,wtkg3,x.bmi5,x.bmi5cat,x.rfbmi5,x.chldcnt,x.educag,x.incomg1,x.smoker3,x.rfsmok3,x.cureci1,drnkany5,drocdy3.,x.rfbing5,x.drnkwk1,x.rfdrhv7,x.flshot7,x.pneumo3,x.aidtst4,ftjuda2.,frutda2.,grenda1.,frnchda.,potada1.,vegeda2.,x.misfrt1,x.misveg1,x.frtres1,x.vegres1,x.frutsu1,x.vegesu1,x.frtlt1a,x.veglt1a,x.frt16a,x.veg23a,x.fruite1,x.vegete1
0,1,1,1,1192021,1,19,2021,1100,2021000001,2021000001,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,5.0,20.0,10.0,88.0,3.0,1.0,2.0,2.0,2.0,3.0,NaN,2.0,1.0,1.0,2.0,2.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,3.0,NaN,1.0,2.0,2.0,2.0,1.0,8.0,1.0,4.0,1.0,1.0,1.0,1.0,2.0,7.0,88.0,5.0,NaN,72.0,411.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,3.0,3.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,2.0,NaN,101.0,555.0,204.0,203.0,201.0,101.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,39.766158,2.0,79.532315,1,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,744.745531,2,3,2,1,9,2,1,1,2.0,2.0,2,2,1,1.0,2.0,1.0,1.0,1.0,2,1,1,1,1,2,11,2,70,6,59.0,150.0,3266.0,1454.0,1.0,1,1,2,3,3,1,1,2,0,1,0,1,1.0,1.0,2.0,0.0,100.0,57.0,43.0,14.0,100.0,0,0,1,1,100.0,214.0,1,1,1,1,0,0
1,2,1,1,1212021,1,21,2021,1100,2021000002,2021000002,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,3.0,88.0,88.0,NaN,1.0,2.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,1.0,1.0,98.0,1.0,1.0,2.0,1.0,1.0,10.0,9.0,6.0,1.0,2.0,NaN,1.0,2.0,8.0,88.0,77.0,NaN,7777.0,506.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,201.0,555.0,201.0,207.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,2.0,11011,39.766158,2.0,79.532315,2,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,299.137394,1,1,1,1,9,1,2,1,2.0,1.0,1,1,3,1.0,1.0,1.0,2.0,2.0,2,2,2,2,2,2,10,2,67,6,66.0,168.0,NaN,NaN,NaN,9,1,4,9,4,1,1,2,0,1,0,1,2.0,2.0,2.0,0.0,100.0,14.0,0.0,14.0,100.0,0,0,1,1,100.0,128.0,1,1,1,1,0,0
2,3,1,1,1212021,1,21,2021,1100,2021000003,2021000003,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,88.0,NaN,2.0,2.0,2.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,1.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,98.0,2.0,NaN,NaN,NaN,NaN,NaN,3.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,3.0,NaN,170.0,505.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,888.0,NaN,NaN,NaN,2.0,NaN,NaN,2.0,2.0,NaN,101.0,555.0,555.0,201.0,201.0,203.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,1.0,11011,39.766158,2.0,79.532315,2,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,587.862986,1,1,1,1,9,2,2,1,1.0,1.0,1,1,3,2.0,3.0,3.0,2.0,2.0,2,2,2,2,2,2,11,2,72,6,65.0,165.0,7711.0,2829.0,3.0,2,1,2,2,4,1,1,2,0,1,0,1,2.0,2.0,2.0,0.0,100.0,0.0,14.0,14.0,43.0,0,0,1,1,100.0,71.0,1,2,1,1,0,0
3,4,1,1,1172021,1,17,2021,1100,2021000004,2021000004,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2.0,88.0,10.0,88.0,2.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,56.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,4.0,1.0,2.0,NaN,1.0,2.0,7.0,88.0,7.0,NaN,195.0,504.0,2.0,2.0,2.0,2.0,2.0,2.0,2.0,NaN,3.0,3.0,101.0,3.0,1.0,6.0,1.0,102020.0,1.0,2.0,2.0,NaN,203.0,205.0,303.0,204.0,308.0,205.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,1.0,2.0,2.0,2.0,2.0,1.0,3.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,1.0,1.0,3.0,11011,39.766158,2.0,79.532315,1,9.0,NaN,NaN,NaN,NaN,1,0.519019,874.242902,1099.621573,1,1,2,1,1,1,2,1,2.0,2.0,1,1,3,2.0,3.0,3.0,1.0,1.0,2,1,1,1,1,2,9,1,62,5,64.0,163.0,8845.0,3347.0,4.0,2,1,2,5,4,1,1,1,14,2,300,1,NaN,NaN,2.0,71.0,43.0,10.0,57.0,27.0,71.0,0,0,1,1,114.0,165.0,1,1,1,1,0,0
4,5,1,1,1152021,1,15,2021,1100,2021000005,2021000005,1.0,1.0,NaN,1.0,2.0,1.0,NaN,2.0,NaN,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5.0,30.0,88.0,30.0,3.0,1.0,2.0,1.0,1.0,4.0,NaN,2.0,1.0,1.0,1.0,7.0,1.0,2.0,NaN,2.0,2.0,2.0,2.0,2.0,1.0,65.0,2.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0,1.0,2.0,NaN,8.0,2.0,8.0,88.0,4.0,NaN,206.0,511.0,1.0,2.0,2.0,1.0,2.0,2.0,2.0,NaN,2.0,3.0,888.0,NaN,NaN,NaN,1.0,92020.0,1.0,1.0,1.0,777777.0,101.0,555.0,101.0,202.0,202.0,101.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,2.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,1,2.0,1.0,2.0,11011,39.766158,2.0,79.532315,6,9.0,NaN,NaN,NaN,NaN,9,NaN,2144.768999,1711.825866,2,3,1,1,9,1,1,1,2.0,1.0,1,1,3,2.0,3.0,3.0,1.0,7.0,2,7,2,4,7,1,12,2,76,6,71.0,180.0,9344.0,2873.0,3.0,2,1,1,2,4,1,1,2,0,1,0,1,1.0,1.0,1.0,0.0,100.0,100.0,29.0,29.0,100.0,0,0,1,1,100.0,258.0,1,1,1,1,0,0

### Diabetes Status Subset
- (Ever told) (you had) diabetes
- create a full-population dataframe using only `diabete4`
- drop missing values for the diabetes-status variable

In [6]:
diabetes_status_df = brfss_2021_df[['diabete4']].dropna()
diabetes_status_df.shape

(438690, 1)

### Clean Diabetes Status
- remove invalid `diabete4` codes for don't know and refused
- inspect the remaining diabetes-status counts

In [7]:
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete4'] != 7]
diabetes_status_df = diabetes_status_df[diabetes_status_df['diabete4'] != 9]
diabetes_status_df['diabete4'].value_counts().sort_index()

diabete4
1.0     57616
2.0      3808
3.0    366342
4.0      9942
Name: count, dtype: int64

### Recode Diabetes Target
- convert BRFSS diabetes codes into the `0/1/2` target used in the reference notebook

In [8]:
diabetes_status_df['Diabetes_012'] = diabetes_status_df['diabete4'].replace({
    2: 0,
    4: 0,
    3: 1,
    1: 2,
})

diabetes_status_df.groupby(['Diabetes_012']).size()

Diabetes_012
0.0     13750
1.0    366342
2.0     57616
dtype: int64

### Feature List
- define the diabetes-management variables and covariates used in the paper-style analysis dataframe

In [13]:
columns = [
"diabedu",
"feetchk3",
"bldsugar",
"doctdiab",
"chkhemo3",
"feetchk",
"eyeexam1",
"menthlth",
"educa",
"x.ageg5yr",
"birthsex",
"marital",
"employ1",
"income3",
"x.urbstat",
"persdoc3",
"x.hlthpln",
"addepev3",
"diabete4",
"diabage3"
]

### Select Analysis Columns
- build `features_df` from the selected diabetes-management variables

In [14]:
features_df = brfss_2021_df[columns].copy()

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [15]:
features_df.shape

(438693, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [16]:
features_df.head()

,diabedu,feetchk3,bldsugar,doctdiab,chkhemo3,feetchk,eyeexam1,menthlth,educa,x.ageg5yr,birthsex,marital,employ1,income3,x.urbstat,persdoc3,x.hlthpln,addepev3,diabete4,diabage3
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,4.0,11,NaN,1.0,7.0,5.0,1.0,1.0,1,2.0,3.0,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,6.0,10,NaN,9.0,8.0,77.0,1.0,2.0,1,2.0,1.0,98.0
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,4.0,11,NaN,3.0,7.0,3.0,1.0,2.0,1,2.0,1.0,98.0
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,4.0,9,NaN,1.0,7.0,7.0,1.0,1.0,1,2.0,1.0,56.0
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,88.0,3.0,12,NaN,1.0,8.0,4.0,1.0,1.0,1,2.0,1.0,65.0

# Cleaning

### Drop Missing Values
- remove rows with missing values across the selected diabetes-management variables

In [17]:
features_df = features_df.dropna()
features_df.shape

(4600, 20)

### diabedu
- whether respondent ever took a diabetes management class
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [18]:
features_df = features_df[features_df['diabedu'] != 7]
features_df = features_df[features_df['diabedu'] != 9]
features_df['diabedu'] = features_df['diabedu'].replace({2: 0})
features_df['diabedu'].unique()

array([0., 1.])

### feetchk3
- how often respondent checks their feet for sores or irritation
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [19]:
features_df = features_df[features_df['feetchk3'] != 777]
features_df = features_df[features_df['feetchk3'] != 999]
features_df['feetchk3'].unique()

array([103., 888., 201., 101., 301., 203., 404., 202., 401., 308., 204.,
       304., 102., 199., 302., 104., 207., 402., 499., 107., 412., 105.,
       191., 330., 403., 112., 206., 406., 130., 205., 320., 303., 110.,
       215., 150., 111., 408., 405., 315., 305., 436., 307., 310., 120.,
       106., 420., 306.])

### bldsugar
- how often respondent checks blood sugar
- remove `777` and `999` because they represent don't know / refused
- keep the remaining numeric values so you can later convert this into daily vs less-than-daily if needed

In [20]:
features_df = features_df[features_df['bldsugar'] != 777]
features_df = features_df[features_df['bldsugar'] != 999]
features_df['bldsugar'].unique()

array([102., 888., 101., 204., 103., 201., 404., 202., 203., 402., 104.,
       107., 205., 207., 301., 198., 108., 499., 120., 210., 401., 208.,
       199., 209., 406., 206., 304., 403., 307., 408., 115., 315., 302.,
       106., 303., 105., 412., 110., 221., 330., 410., 112., 360., 320.,
       130., 405., 188., 306., 440., 305., 109., 214., 312., 225., 308.,
       124., 420., 430., 125., 415., 310., 150., 212.])

### doctdiab
- number of times respondent saw a health professional for diabetes in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining counts as numeric values

In [21]:
features_df = features_df[features_df['doctdiab'] != 77]
features_df = features_df[features_df['doctdiab'] != 99]
features_df['doctdiab'].unique()

array([ 3., 88.,  1.,  2.,  4.,  8., 12.,  5.,  6.,  7., 30., 50., 24.,
       40., 20., 10., 76.,  9., 52., 16., 15., 27., 11., 18., 26., 60.,
       72., 48., 13., 14., 33.])

### chkhemo3
- number of A1c checks in the past year
- remove `77` and `99` because they represent don't know / refused
- keep the remaining numeric counts so you can later convert this into at least twice per year vs less than twice

In [22]:
features_df = features_df[features_df['chkhemo3'] != 77]
features_df = features_df[features_df['chkhemo3'] != 99]
features_df['chkhemo3'].unique()

array([ 3.,  1., 88.,  2.,  9., 98.,  8.,  4., 12.,  6.,  5., 20.,  7.,
       76., 40., 30., 24., 10., 25., 28., 11., 52., 15., 16.])

### feetchk
- number of times respondent had their feet checked by a health professional in the past 12 months
- remove `77` and `99` because they represent don't know / refused
- keep the remaining values as valid counts so this can later be recoded into annual foot check vs not annual foot check

In [23]:
features_df = features_df[features_df['feetchk'] != 77]
features_df = features_df[features_df['feetchk'] != 99]
features_df['feetchk'].unique()

array([ 1., 88.,  3.,  2.,  4., 12.,  5., 10.,  6., 76.,  9.,  8., 25.,
       20., 11., 15.,  7., 52., 30., 35., 24., 48., 26., 60., 45., 40.,
       27., 18., 51., 36., 14.])

### eyeexam1
- how recently respondent had a dilated eye exam
- remove `7` and `9` because they represent don't know / refused
- keep the remaining categories so you can later convert this into annual exam vs not annual

In [24]:
features_df = features_df[features_df['eyeexam1'] != 7]
features_df = features_df[features_df['eyeexam1'] != 9]
features_df['eyeexam1'].unique()

array([4., 2., 3., 1., 8.])

### menthlth
- number of bad mental health days in the past 30 days
- change `88` to `0` because BRFSS uses `88` for none
- remove `77` and `99` because they indicate don't know / refused
- keep this as a count variable from `0` to `30`

In [25]:
features_df['menthlth'] = features_df['menthlth'].replace({88: 0})
features_df = features_df[features_df['menthlth'] != 77]
features_df = features_df[features_df['menthlth'] != 99]
features_df['menthlth'].unique()

array([ 0., 10., 25., 15., 20.,  2., 30., 16.,  5.,  1.,  4.,  6.,  3.,
       28., 14.,  7., 29.,  8.,  9., 26., 12., 27., 19., 23., 21., 11.,
       13., 17.])

### educa
- respondent education level
- remove `9` because it represents refused / missing
- keep the remaining categories as an ordinal education variable

In [26]:
features_df = features_df[features_df['educa'] != 9]
features_df['educa'].unique()

array([2., 5., 4., 3., 6., 1.])

### x.ageg5yr
- respondent age group
- remove `14` because it corresponds to missing / refused rather than a real age group
- keep the remaining ordered age-group categories as valid responses

In [27]:
features_df = features_df[features_df['x.ageg5yr'] != 14]
features_df['x.ageg5yr'].unique()

array([ 9, 11, 13, 12, 10,  5,  7,  8,  6,  4,  1,  3,  2])

### birthsex
- whether respondent is male
- change `2` to `0` so female is `0` and male remains `1`
- this makes the variable binary and easier to interpret in modeling

In [29]:
features_df['birthsex'] = features_df['birthsex'].replace({2: 0})
features_df['birthsex'].unique()

array([1., 0., 9., 7.])

### marital
- respondent marital or partnered status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into married/partnered vs not married/partnered

In [30]:
features_df = features_df[features_df['marital'] != 9]
features_df['marital'].unique()

array([4., 2., 3., 1., 5., 6.])

### employ1
- respondent employment status
- remove `9` because it represents refused
- keep the remaining categories so you can later collapse them into employed vs not employed

In [31]:
features_df = features_df[features_df['employ1'] != 9]
features_df['employ1'].unique()

array([7., 5., 8., 1., 3., 6., 2., 4.])

### income3
- annual household income category
- remove `77` and `99` because they represent don't know / refused
- keep the remaining categories as an ordinal income variable

In [32]:
features_df = features_df[features_df['income3'] != 77]
features_df = features_df[features_df['income3'] != 99]
features_df['income3'].unique()

array([ 5.,  4.,  1.,  6.,  3.,  7.,  2.,  8.,  9., 10., 11.])

### x.urbstat
- whether respondent lives in an urban or rural county
- inspect values here because this is a derived variable
- if only valid categories are present, no additional cleaning is needed

In [33]:
features_df['x.urbstat'].unique()

array([1., 2.])

### persdoc3
- whether respondent has at least one personal health care provider
- remove `7` and `9` because they represent don't know / refused
- keep the valid categories, then collapse later if you want at least one provider vs none

In [42]:
features_df = features_df[features_df['persdoc3'] != 7]
features_df = features_df[features_df['persdoc3'] != 9]
features_df['persdoc3'].unique()

array([1., 3., 2.])

### x.hlthpln
- whether respondent has any health care coverage
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no coverage is `0` and yes remains `1`

In [43]:
features_df = features_df[features_df['x.hlthpln'] != 7]
features_df = features_df[features_df['x.hlthpln'] != 9]
features_df['x.hlthpln'] = features_df['x.hlthpln'].replace({2: 0})
features_df['x.hlthpln'].unique()

array([1, 0])

### addepev3
- whether respondent was ever told they had a depressive disorder
- remove `7` and `9` because they represent don't know / refused
- change `2` to `0` so no is `0` and yes remains `1`

In [38]:
features_df = features_df[features_df['addepev3'] != 7]
features_df = features_df[features_df['addepev3'] != 9]
features_df['addepev3'] = features_df['addepev3'].replace({2: 0})
features_df['addepev3'].unique()

array([0., 1.])

### diabete4
- remove `7` and `9` because they represent don't know / refused
- inspect the remaining diabetes-status values in the diabetes-management subset
- keep this as an inspection step rather than forcing the dataset to diagnosed diabetes only

In [39]:
features_df = features_df[features_df['diabete4'] != 7]
features_df = features_df[features_df['diabete4'] != 9]
features_df.groupby(['diabete4']).size()

diabete4
1.0    3254
dtype: int64

### diabage3
- respondent age when first told they had diabetes
- remove `98` and `99` because they represent don't know / refused
- keep the remaining values as a numeric age-at-diagnosis variable

In [40]:
features_df = features_df[features_df['diabage3'] != 98]
features_df = features_df[features_df['diabage3'] != 99]
features_df['diabage3'].unique()

array([72., 35., 51., 50., 60., 48., 65., 40., 22., 28., 55., 62., 57.,
       58., 30., 70., 64., 80., 69., 38., 39., 54., 74., 42., 61., 71.,
       47., 63., 76., 67., 52., 49., 59., 45., 75., 81., 56., 53., 32.,
       68., 12., 46., 44., 66., 36., 34., 31., 15., 88., 24., 94., 13.,
       25., 43., 77., 21., 27., 26., 18., 17., 41.,  5., 23., 73., 78.,
       37.,  2., 20., 14., 19., 16.,  6.,  4., 11., 29., 79., 33.,  1.,
       86., 85.,  9.,  3.,  8.,  7., 10., 87., 84., 83., 82.])

### Rename Management Columns
- rename the cleaned diabetes-management variables to readable analysis names before EDA and export

In [44]:
features_df = features_df.rename(columns={
    'diabedu': 'Diabetes_Class',
    'feetchk3': 'Foot_Self_Check_Freq',
    'bldsugar': 'Blood_Sugar_Check_Freq',
    'doctdiab': 'Doctor_Visit_Diabetes_Freq',
    'chkhemo3': 'A1C_Check_Freq',
    'feetchk': 'Professional_Foot_Check_Freq',
    'eyeexam1': 'Eye_Exam_Recency',
    'menthlth': 'Bad_Mental_Health_Days',
    'educa': 'Education',
    'x.ageg5yr': 'Age_Group',
    'birthsex': 'Male',
    'marital': 'Marital_Status',
    'employ1': 'Employment_Status',
    'income3': 'Income',
    'x.urbstat': 'Urban_Rural_Status',
    'persdoc3': 'Personal_Doctor',
    'x.hlthpln': 'Health_Coverage',
    'addepev3': 'Depressive_Disorder',
    'diabete4': 'Diabetes_Status',
    'diabage3': 'Diabetes_Age'
})

In [47]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
58505,0.0,201.0,101.0,88.0,1.0,88.0,2.0,0.0,4.0,13,0.0,3.0,7.0,5.0,1.0,1.0,1,0.0,1.0,72.0
58522,0.0,101.0,888.0,88.0,88.0,88.0,3.0,0.0,5.0,12,1.0,3.0,7.0,5.0,1.0,3.0,1,0.0,1.0,35.0
58524,0.0,301.0,101.0,1.0,1.0,88.0,1.0,0.0,4.0,12,1.0,1.0,7.0,4.0,1.0,2.0,1,0.0,1.0,51.0
58551,0.0,101.0,103.0,2.0,98.0,88.0,2.0,0.0,6.0,13,0.0,3.0,7.0,6.0,1.0,2.0,1,0.0,1.0,50.0
58557,1.0,888.0,201.0,2.0,2.0,88.0,3.0,0.0,3.0,13,1.0,1.0,8.0,3.0,2.0,1.0,1,0.0,1.0,60.0

### Analysis Shape
- inspect the current size of the diabetes-management analysis dataframe

In [48]:
features_df.shape

(3160, 20)

### Analysis Preview
- show the first few rows of the diabetes-management analysis dataframe

In [49]:
features_df.head()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
58505,0.0,201.0,101.0,88.0,1.0,88.0,2.0,0.0,4.0,13,0.0,3.0,7.0,5.0,1.0,1.0,1,0.0,1.0,72.0
58522,0.0,101.0,888.0,88.0,88.0,88.0,3.0,0.0,5.0,12,1.0,3.0,7.0,5.0,1.0,3.0,1,0.0,1.0,35.0
58524,0.0,301.0,101.0,1.0,1.0,88.0,1.0,0.0,4.0,12,1.0,1.0,7.0,4.0,1.0,2.0,1,0.0,1.0,51.0
58551,0.0,101.0,103.0,2.0,98.0,88.0,2.0,0.0,6.0,13,0.0,3.0,7.0,6.0,1.0,2.0,1,0.0,1.0,50.0
58557,1.0,888.0,201.0,2.0,2.0,88.0,3.0,0.0,3.0,13,1.0,1.0,8.0,3.0,2.0,1.0,1,0.0,1.0,60.0

In [50]:
features_df.tail()

,Diabetes_Class,Foot_Self_Check_Freq,Blood_Sugar_Check_Freq,Doctor_Visit_Diabetes_Freq,A1C_Check_Freq,Professional_Foot_Check_Freq,Eye_Exam_Recency,Bad_Mental_Health_Days,Education,Age_Group,Male,Marital_Status,Employment_Status,Income,Urban_Rural_Status,Personal_Doctor,Health_Coverage,Depressive_Disorder,Diabetes_Status,Diabetes_Age
253904,1.0,101.0,103.0,4.0,3.0,88.0,3.0,0.0,2.0,8,0.0,5.0,8.0,1.0,1.0,1.0,1,1.0,1.0,25.0
253917,1.0,202.0,203.0,2.0,2.0,2.0,1.0,2.0,6.0,11,1.0,1.0,7.0,8.0,1.0,1.0,1,1.0,1.0,55.0
253921,0.0,101.0,101.0,88.0,88.0,88.0,8.0,1.0,2.0,8,0.0,3.0,1.0,1.0,1.0,1.0,1,1.0,1.0,49.0
253951,1.0,102.0,101.0,4.0,4.0,5.0,2.0,0.0,6.0,10,0.0,2.0,7.0,7.0,1.0,2.0,1,0.0,1.0,48.0
253963,1.0,101.0,301.0,2.0,2.0,2.0,2.0,0.0,5.0,8,0.0,1.0,5.0,7.0,1.0,1.0,1,1.0,1.0,39.0

### Save Management Dataset
- save the cleaned diabetes module dataframe to CSV

In [51]:
'''
# export cleaned data
features_df.to_csv('2021_brfss_diabetes_module_features.csv', index=False)
'''